/**
 * Repository-safe READY-RECIPE CATALOGUE fixtures (Agent B).
 *
 * METADATA ONLY — no ingredient composition, no doses, no engine numbers. These
 * are illustrative TEST cards used to exercise the matching + selection logic;
 * they are NOT real catalogue records and make no claim about real recipes,
 * images or ingredient amounts. Image paths are fixture placeholders.
 */
import type { CatalogueRecipeCard } from '../readyRecipeMatching';

export const CATALOGUE_FIXTURES: readonly CatalogueRecipeCard[] = [
  {
    id: 'cat-vanilla-classic',
    version: 'v1',
    title: 'Vanilla (classic) — fixture',
    description: 'Fixture card for matching tests.',
    flavorCode: 'vanilla',
    secondaryFlavorCode: null,
    imageCode: 'img_vanilla',
    imagePath: 'fixtures/img_vanilla.placeholder',
    productType: 'gelato',
    internalProfile: 'standard_gelato',
    flavorTags: ['vanilla'],
    dietaryTags: [],
    deviceCompatibility: ['ninja-creami', 'professional-machine'],
    servingProfile: 'display-minus-11',
    availability: 'available',
    gramVisibilityEntitlement: 'exact_grams',
  },
  {
    id: 'cat-chocolate-orange',
    version: 'v1',
    title: 'Chocolate & orange — fixture',
    description: 'Fixture card for matching tests.',
    flavorCode: 'chocolate',
    secondaryFlavorCode: 'orange',
    imageCode: 'img_choc_orange',
    imagePath: 'fixtures/img_choc_orange.placeholder',
    productType: 'gelato',
    internalProfile: 'chocolate_gelato',
    flavorTags: ['chocolate', 'orange'],
    dietaryTags: [],
    deviceCompatibility: ['professional-machine'],
    servingProfile: 'display-minus-11',
    availability: 'available',
    gramVisibilityEntitlement: 'exact_grams',
  },
  {
    id: 'cat-pistachio',
    version: 'v2',
    title: 'Pistachio — fixture',
    description: 'Fixture card for matching tests.',
    flavorCode: 'pistachio',
    secondaryFlavorCode: null,
    imageCode: 'img_pistachio',
    imagePath: 'fixtures/img_pistachio.placeholder',
    productType: 'gelato',
    internalProfile: 'standard_gelato',
    flavorTags: ['pistachio'],
    dietaryTags: [],
    deviceCompatibility: ['ninja-creami'],
    servingProfile: 'display-minus-12',
    availability: 'available',
    gramVisibilityEntitlement: 'exact_grams',
  },
  {
    id: 'cat-raspberry-sorbet',
    version: 'v1',
    title: 'Raspberry sorbet — fixture',
    description: 'Fixture card for matching tests.',
    flavorCode: 'raspberry',
    secondaryFlavorCode: null,
    imageCode: 'img_raspberry',
    imagePath: 'fixtures/img_raspberry.placeholder',
    productType: 'sorbet',
    internalProfile: 'sorbet',
    flavorTags: ['raspberry'],
    dietaryTags: ['lactose_free'],
    deviceCompatibility: ['professional-machine'],
    servingProfile: 'display-minus-11',
    availability: 'available',
    gramVisibilityEntitlement: 'exact_grams',
  },
  {
    id: 'cat-mango-sorbet',
    version: 'v1',
    title: 'Mango sorbet — fixture',
    description: 'Fixture card for matching tests.',
    flavorCode: 'mango',
    secondaryFlavorCode: null,
    imageCode: 'img_mango',
    imagePath: 'fixtures/img_mango.placeholder',
    productType: 'sorbet',
    internalProfile: 'sorbet',
    flavorTags: ['mango'],
    dietaryTags: ['lactose_free'],
    deviceCompatibility: ['professional-machine'],
    servingProfile: 'display-minus-11',
    availability: 'available',
    gramVisibilityEntitlement: 'exact_grams',
  },
  {
    id: 'cat-lemon-sorbet',
    version: 'v1',
    title: 'Lemon sorbet — fixture',
    description: 'Fixture card for matching tests.',
    flavorCode: 'lemon',
    secondaryFlavorCode: null,
    imageCode: 'img_lemon',
    imagePath: 'fixtures/img_lemon.placeholder',
    productType: 'sorbet',
    internalProfile: 'sorbet',
    flavorTags: ['lemon'],
    dietaryTags: ['lactose_free'],
    deviceCompatibility: ['professional-machine'],
    servingProfile: 'display-minus-13',
    availability: 'available',
    gramVisibilityEntitlement: 'exact_grams',
  },
  {
    id: 'cat-vegan-chocolate',
    version: 'v1',
    title: 'Vegan chocolate — fixture',
    description: 'Fixture card for matching tests.',
    flavorCode: 'chocolate',
    secondaryFlavorCode: null,
    imageCode: 'img_vegan_choc',
    imagePath: 'fixtures/img_vegan_choc.placeholder',
    productType: 'vegan',
    internalProfile: 'vegan_gelato',
    flavorTags: ['chocolate'],
    dietaryTags: ['vegan', 'lactose_free'],
    deviceCompatibility: ['professional-machine'],
    servingProfile: 'display-minus-11',
    availability: 'available',
    gramVisibilityEntitlement: 'exact_grams',
  },
  {
    // Deliberately NOT available — must never be offered by the matcher.
    id: 'cat-hazelnut-comingsoon',
    version: 'v1',
    title: 'Hazelnut (coming soon) — fixture',
    description: 'Fixture card that is not yet available.',
    flavorCode: 'hazelnut',
    secondaryFlavorCode: null,
    imageCode: 'img_hazelnut',
    imagePath: 'fixtures/img_hazelnut.placeholder',
    productType: 'gelato',
    internalProfile: 'standard_gelato',
    flavorTags: ['hazelnut'],
    dietaryTags: [],
    deviceCompatibility: ['ninja-creami'],
    servingProfile: 'display-minus-11',
    availability: 'coming_soon',
    gramVisibilityEntitlement: 'exact_grams',
  },
];
