// Deterministic Markdown reports rendered from the registry and the DB plan.
// Every number in these reports is computed here from registry.json; nothing
// is typed by hand, so the reports cannot drift from the data.

const SLOTS = ['MILK', 'CREAM', 'SMP', 'DEXTROSE', 'STABILIZER'];
const GAP_ROLES = ['CREAM', 'SMP', 'DEXTROSE', 'TARA'];
const OWNER_GAP_LISTS = Object.freeze({
  CREAM: ['CR', 'DZ', 'JP', 'UY'],
  SMP: ['BE', 'BH', 'CR', 'DO', 'ID', 'IL', 'JP', 'KW', 'LT', 'LV', 'MY', 'SA', 'SK', 'UY', 'VN', 'ZA'],
  DEXTROSE: [
    'AE', 'AR', 'AU', 'BD', 'BH', 'BR', 'CA', 'CL', 'CN', 'CO', 'CR', 'DO', 'DZ', 'EG', 'GH', 'HK', 'ID',
    'IL', 'IN', 'JP', 'KE', 'KR', 'KW', 'LK', 'MA', 'MX', 'MY', 'NG', 'NZ', 'PA', 'PH', 'PK', 'SA', 'SG',
    'TH', 'TN', 'TR', 'TW', 'US', 'UY', 'VN', 'ZA',
  ],
});
const OWNER_GAP_TOTALS = Object.freeze({ CREAM: 4, SMP: 16, DEXTROSE: 42, TARA: 47 });

const compare = (left, right) => {
  const a = String(left ?? '');
  const b = String(right ?? '');
  if (a < b) return -1;
  if (a > b) return 1;
  return 0;
};

const esc = (value) => {
  if (value === null || value === undefined || value === '') return '—';
  return String(value).replace(/\|/g, '\\|').replace(/\r?\n/g, '<br>');
};

const table = (headers, rows) => [
  `| ${headers.join(' | ')} |`,
  `| ${headers.map(() => '---').join(' | ')} |`,
  ...rows.map((row) => `| ${row.map(esc).join(' | ')} |`),
];

const count = (list, predicate) => list.filter(predicate).length;

function header(registry, title) {
  return [
    `# ${title}`,
    '',
    `Generated by \`scripts/countryProducts/importGelatoBaseV12.mjs\` from \`${registry.source.workbook}\` (sha256 \`${registry.source.sha256}\`) and the read-only catalog snapshot captured ${registry.catalogSnapshot.capturedAt} (project \`${registry.catalogSnapshot.projectRef}\`, shared by staging and production). Regenerate instead of editing; \`--check\` fails on any drift.`,
    '',
    `Workbook state (${registry.source.workbookStateRef}): “${registry.source.workbookState}”`,
    '',
  ];
}

function gapComparison(registry) {
  const lines = [];
  for (const role of GAP_ROLES) {
    const gaps = registry.openGaps.filter((gap) => gap.workbookRole === role);
    const countries = [...new Set(gaps.map((gap) => gap.country))].sort(compare);
    const ownerList = OWNER_GAP_LISTS[role];
    const header = registry.counts.openGaps.workbookHeader[role];
    let ownerCheck = `owner total ${OWNER_GAP_TOTALS[role]}`;
    if (ownerList) {
      const missing = ownerList.filter((iso) => !countries.includes(iso));
      const extra = countries.filter((iso) => !ownerList.includes(iso));
      ownerCheck +=
        missing.length === 0 && extra.length === 0
          ? ', owner country list matches exactly'
          : `, DISCREPANCY missing ${missing.join(',') || '—'} extra ${extra.join(',') || '—'}`;
    }
    lines.push([
      role === 'TARA' ? 'STABILIZER (workbook role TARA)' : role,
      gaps.length,
      header,
      gaps.length === header && gaps.length === OWNER_GAP_TOTALS[role] ? 'MATCH' : 'DISCREPANCY',
      ownerCheck,
      countries.join(', '),
    ]);
  }
  return table(['Role', 'Rows in 40_POZOSTALE_V12', 'Workbook header', 'Result', 'Owner check', 'Countries'], lines);
}

const STABILIZER_STATEMENT =
  '**Stabilizer 47 ≠ 47 missing TARA markets.** The 47 entries are open research cases on the product currently chosen for the functional STABILIZER slot (energy convention, label fields, allergens, delivery, lot documents, one US legal hold). TARA is not mandatory in any market; the slot may be filled by local TARA → local existing Gellatti stabilizer → local premix/blend → verified cross-border fallback → BRAK/REVIEW_REQUIRED, and a non-TARA stabilizer needs its own PR identity, composition, Engine readiness and recalculated grams.';

function cellState(selection) {
  if (selection.selectionState === 'SELECTION_CLOSED') {
    switch (selection.route.decision) {
      case 'ROUTE_ALREADY_PRESENT':
        return 'closed · route present';
      case 'ROUTE_CREATABLE_NOW':
        return 'closed · route now';
      default:
        return selection.route.blockers.includes('MARKET_NOT_IN_CATALOG_MARKET_COUNTRIES')
          ? 'closed · FK'
          : selection.route.blockers.some((b) => b.startsWith('EXISTING_PRIMARY'))
            ? 'closed · conflict'
            : 'closed · blocked';
    }
  }
  return `${selection.selectionState === 'BLOCKED' ? 'blocked' : 'open'} ${selection.openGapId}`;
}

export function renderCoverageReport(registry, plan) {
  const exact = registry.selections.filter((selection) => selection.selectionKind === 'EXACT_PRODUCT');
  const products = registry.products;
  const selectionByKey = new Map(registry.selections.map((selection) => [selection.selectionKey, selection]));
  const lines = [...header(registry, 'Country products v12 — coverage')];

  lines.push('## Headline', '');
  lines.push(
    ...table(
      ['Measure', 'Value'],
      [
        ['Countries', registry.counts.countries],
        ['Base slots (1000 g Gelato base, existing PIs only)', registry.base.map((slot) => `${slot.slot} ${slot.grams} g → ${slot.piIngId}`).join('; ')],
        ['Country × slot selections', `${registry.counts.selections} (${registry.counts.exactProductSelections} exact-product + ${registry.counts.globalPiSelections} SUCROSE global PI, no PR needed)`],
        ['Exact PR product identities (deduplicated)', registry.counts.products],
        ['Reused existing PR-ING', `${registry.counts.productCatalogDecisions.REUSE_EXISTING_PR ?? 0} (${products.filter((p) => p.catalog.decision === 'REUSE_EXISTING_PR').map((p) => p.catalog.existingPrIng).join(', ')})`],
        ['New PR-ING required', registry.counts.productCatalogDecisions.NEW_PR_REQUIRED ?? 0],
        ['Duplicates prevented (proposals merged into another identity)', `${registry.counts.duplicatesPrevented.total} = ${registry.counts.duplicatesPrevented.alreadyGroupedByWorkbookProposalKey} already grouped by the workbook's own proposal keys + ${registry.counts.duplicatesPrevented.additionalMergesBySameBrandArticlePack} additional (same brand + article code + pack) + ${registry.counts.duplicatesPrevented.additionalMergesBySameGtin} additional same-GTIN`],
        ['Possible duplicates NOT merged (review)', registry.counts.possibleDuplicatesNotMerged],
        ['Routes creatable now', plan.routeCounts.creatableNow],
        ['Routes already present', plan.routeCounts.alreadyPresent],
        ['Routes blocked by market FK (country not in catalog_market_countries)', plan.routeCounts.blockedByMarketForeignKey],
        ['Routes blocked otherwise (market row present)', plan.routeCounts.blockedOtherwise],
        ['New PI-ING created', registry.invariants.newPiCreated],
        ['Mapper modified', registry.invariants.mapperModified ? 'YES' : 'no'],
        ['Silent substitutes', registry.invariants.silentSubstitutes],
      ],
    ),
  );

  lines.push('', '## Open cases (v12 is PARTIAL — not forced to 75/75)', '');
  lines.push(...gapComparison(registry));
  lines.push('', STABILIZER_STATEMENT);

  lines.push('', '## PR products by slot', '');
  lines.push(
    ...table(
      ['Slot', 'PI-ING', 'Identities', 'With ≥1 closed selection', 'All selections open/blocked', 'Selections closed', 'Selections open', 'Selections blocked', 'Reused', 'New'],
      SLOTS.map((slot) => {
        const inSlot = products.filter((product) => product.slot === slot);
        const states = registry.counts.selectionStates[slot];
        return [
          slot,
          registry.base.find((row) => row.slot === slot).piIngId,
          inSlot.length,
          count(inSlot, (product) => product.marketRoutes.some((route) => route.selectionState === 'SELECTION_CLOSED')),
          count(inSlot, (product) => product.marketRoutes.every((route) => route.selectionState !== 'SELECTION_CLOSED')),
          states.SELECTION_CLOSED ?? 0,
          states.RESEARCH_OPEN ?? 0,
          states.BLOCKED ?? 0,
          count(inSlot, (product) => product.catalog.decision === 'REUSE_EXISTING_PR'),
          count(inSlot, (product) => product.catalog.decision === 'NEW_PR_REQUIRED'),
        ];
      }),
    ),
  );

  lines.push('', '## Country × slot matrix', '');
  lines.push('`closed` = selection closed in v12; `open`/`blocked` = case id in 40_POZOSTALE_V12. Route: `now` creatable now, `present` already in DB, `FK` market row missing, `conflict` another active primary, `blocked` other blocker. SUCROSE is the global PI PI-ING-000514 in every country (no PR).', '');
  const countries = registry.countries.map((country) => country.iso2);
  lines.push(
    ...table(
      ['ISO2', 'Market row', ...SLOTS],
      countries.map((iso) => [
        iso,
        registry.countries.find((country) => country.iso2 === iso).catalogMarketRowPresent ? 'yes' : 'no',
        ...SLOTS.map((slot) => cellState(selectionByKey.get(`V12:${iso}:${slot}`))),
      ]),
    ),
  );

  lines.push('', '## Exact PR products (all identities)', '');
  for (const slot of SLOTS) {
    const inSlot = products.filter((product) => product.slot === slot);
    lines.push(`### ${slot} — ${inSlot.length} identities`, '');
    lines.push(
      ...table(
        ['Product key', 'Exact name', 'Brand', 'Pack', 'Identity', 'Markets (closed / open)', 'Catalog', 'Engine profile'],
        inSlot.map((product) => {
          const closed = product.marketRoutes.filter((route) => route.selectionState === 'SELECTION_CLOSED').map((route) => route.country);
          const open = product.marketRoutes.filter((route) => route.selectionState !== 'SELECTION_CLOSED').map((route) => route.country);
          return [
            product.productKey,
            product.exactName,
            product.brand,
            product.package.text,
            product.identity.gtin ? `GTIN ${product.identity.gtin}` : `${product.identity.basis}${product.identity.articleCode ? ` ${product.identity.articleCode}` : ''}`,
            `${closed.join(' ') || '—'} / ${open.join(' ') || '—'}`,
            product.catalog.decision === 'REUSE_EXISTING_PR' ? `REUSE ${product.catalog.existingPrIng}` : product.catalog.decision,
            product.readiness.engineProfileExpectation,
          ];
        }),
      ),
      '',
    );
  }

  lines.push('## Deduplication', '');
  lines.push(`Rule: ${registry.dedupe.rule}`, '');
  const additional = exact.filter((selection) => selection.duplicateBasis === 'SAME_BRAND_ARTICLE_PACK');
  lines.push('Additional merges beyond the workbook’s own proposal keys:', '');
  lines.push(
    ...table(
      ['Selection', 'Merged into', 'Workbook key', 'Basis'],
      additional.map((selection) => [selection.selectionKey, selection.mergedIntoProposalKey, selection.workbook.proposalKey, selection.duplicateBasis]),
    ),
    '',
  );
  lines.push('Possible duplicates deliberately NOT merged (no shared GTIN or article code — REVIEW_REQUIRED):', '');
  lines.push(
    ...table(
      ['Slot', 'Shared brand / supplier', 'Product keys', 'Decision'],
      registry.dedupe.possibleDuplicatesNotMerged.map((entry) => [entry.slot, entry.root, entry.productKeys.join(', '), entry.decision]),
    ),
    '',
  );
  const related = products.filter((product) => product.catalog.relatedExisting.length > 0);
  lines.push('Same brand as an existing catalog product but a different GTIN/pack (never merged, informational):', '');
  lines.push(
    ...table(
      ['v12 product', 'v12 name / pack', 'Existing PR-ING (name, EAN)'],
      related.map((product) => [
        product.productKey,
        `${product.exactName} / ${product.package.text}`,
        product.catalog.relatedExisting.map((entry) => `${entry.productCode} (${entry.name}, ${entry.ean ?? 'no EAN'})`).join('; '),
      ]),
    ),
    '',
  );
  lines.push('Existing PR-ING codes named in the workbook:', '');
  lines.push(
    ...table(
      ['PR-ING', 'Workbook key', 'Product', 'EAN', 'Workbook status', 'In catalog snapshot'],
      registry.dedupe.workbookExistingPrReferences.map((entry) => [entry.prIng, entry.workbookProposalKey, entry.product, entry.ean, entry.workbookStatus, entry.inCatalogSnapshot ? 'yes' : 'no']),
    ),
    '',
  );

  lines.push('## Routes', '');
  lines.push(
    `Creatable now: ${plan.routeCounts.creatableNow} routes for ${plan.productsToCreate.length} new products (see reports/COUNTRY_PRODUCTS_V12_DB_PACKAGE.md). Already present: ${plan.routeCounts.alreadyPresent}. Blocked by the market FK: ${plan.routeCounts.blockedByMarketForeignKey}. Blocked with the market row present: ${plan.routeCounts.blockedOtherwise}.`,
    '',
  );
  const fkOk = exact.filter((selection) => selection.route.marketRowPresent);
  lines.push(
    ...table(
      ['Selection', 'State', 'Route decision', 'Blockers'],
      fkOk.map((selection) => [selection.selectionKey, selection.selectionState, selection.route.decision, selection.route.blockers.join('; ')]),
    ),
    '',
  );

  lines.push('## REVIEW_REQUIRED', '');
  lines.push('Universal (every product): ' + registry.universalReviewRequired.map((entry) => `\`${entry.field}\` — ${entry.reason}`).join(' '), '');
  const review = products.filter((product) => product.reviewRequired.length > 0);
  lines.push(`${review.length} of ${products.length} identities carry product-specific review items:`, '');
  lines.push(...table(['Product key', 'Review items'], review.map((product) => [product.productKey, product.reviewRequired.join('; ')])), '');

  lines.push('## No silent substitutes', '');
  lines.push(
    `${registry.alternatives.length} alternative products are recorded from 39_SYNC_V12 and 34_PRODUKTY_DE_AT. None replaces a selection: every alternative keeps status ALTERNATIVE_LEAD_NOT_SELECTED or REJECTED_NOT_PURE_DEXTROSE and points at the selection it does NOT replace. The twelve EU dextrose markets that v11 moved to the cross-border buXtrade 25 kg stay on that selection exactly as v12 records it (“nie otwierać ponownie”).`,
    '',
  );
  lines.push(
    ...table(
      ['Country', 'Slot', 'Alternative', 'Code', 'Status', 'Selection kept', 'Source'],
      registry.alternatives.map((entry) => [entry.country, entry.slot, entry.name, entry.code ? `${entry.codeLabel ?? ''} ${entry.code}`.trim() : '—', entry.status, entry.selectedProductKey, entry.sourceRef]),
    ),
    '',
  );

  lines.push('## Invariants', '');
  lines.push(
    ...table(
      ['Invariant', 'Value'],
      Object.entries(registry.invariants).map(([key, value]) => [key, String(value)]),
    ),
  );
  lines.push('', 'Consistency checks (all computed from the workbook):', '');
  lines.push(...table(['Check', 'Passed', 'Detail'], registry.consistencyChecks.map((entry) => [entry.id, entry.passed ? 'yes' : 'NO', entry.detail])));
  return `${lines.join('\n')}\n`;
}

export function renderOpenGapsReport(registry) {
  const lines = [...header(registry, 'Country products v12 — open gaps')];
  lines.push(
    `Source: 40_POZOSTALE_V12 (${registry.openGaps.length} rows) cross-checked against 27_CHECKLIST_AKTYWNA and the 39_SYNC_V12 count (${registry.source.openCasesV11} → ${registry.source.openCasesV12}). Each row names the product currently selected for that country and slot, what is still missing, and the checklist cell with the full evidence trail. Closing a case means adding the missing evidence to the next workbook; the delta tool (\`scripts/countryProducts/diffGelatoBaseRegistry.mjs\`) then reports it as newly completed.`,
    '',
  );
  lines.push(...gapComparison(registry), '', STABILIZER_STATEMENT, '');
  lines.push(
    'Global gates that stay open for every product (not counted in the 109): ' +
      registry.globalGates.map((gate) => `${gate.id} (${gate.area}: ${gate.subject})`).join('; ') +
      '.',
    '',
  );
  for (const role of GAP_ROLES) {
    const gaps = registry.openGaps.filter((gap) => gap.workbookRole === role);
    lines.push(`## ${role === 'TARA' ? 'STABILIZER slot — research on the selected TARA product' : role} — ${gaps.length}`, '');
    lines.push(
      ...table(
        ['ID', 'Priority', 'State', 'Country', 'Selected product', 'Conditions', 'What is still missing', 'Checklist', 'v12 note'],
        gaps.map((gap) => [gap.id, gap.priority, gap.state, gap.countryLabel, gap.product, gap.conditions.join(', '), gap.missing, gap.checklistRef, gap.notesV12]),
      ),
      '',
    );
  }
  return `${lines.join('\n')}\n`;
}

export function renderDbPackageReport(registry, plan) {
  const lines = [...header(registry, 'Country products v12 — DB package (NOT executed)')];
  lines.push(
    '> Nothing in this package has been run. The Supabase project `tunabqqrwabacxjcxxkz` is shared by staging AND production, so every write below is a production write. The apply script refuses to mutate unless it receives all three arguments shown under “Approval”.',
    '',
  );
  lines.push('## Approval', '');
  lines.push(
    '```',
    '# default: dry run — reads docs/country-products/gelato-base-v12/registry.json, prints the plan, touches nothing',
    'node scripts/countryProducts/applyGelatoBaseV12.mjs',
    '',
    '# mutation (owner only, after reviewing this report):',
    `node scripts/countryProducts/applyGelatoBaseV12.mjs --project-ref=${plan.projectRef} --apply --owner-db-approval=${plan.approvalToken}`,
    '```',
    '',
    `Approval token: \`${plan.approvalToken}\`. Any other value, a missing flag, or an unknown argument is refused before any network call.`,
    '',
  );
  lines.push('## Scope', '', plan.scope, '');
  lines.push(
    ...table(
      ['Measure', 'Count'],
      [
        ['Exact PR identities in the registry', registry.counts.products],
        ['Reused existing PR-ING (no write)', `${plan.reuse.length} (${plan.reuse.map((entry) => `${entry.prIng}: route ${entry.routesAlreadyPresent.join(',')} already present`).join('; ')})`],
        ['New PR-ING products created by this package', plan.productsToCreate.length],
        ['New PR-ING products deferred (not written)', plan.deferredProducts.length],
        ['Routes created (PRIMARY_DEFAULT)', plan.routeCounts.creatableNow],
        ['Routes already present (no write)', plan.routeCounts.alreadyPresent],
        ['Routes blocked by the market FK', plan.routeCounts.blockedByMarketForeignKey],
        ['Routes blocked otherwise', plan.routeCounts.blockedOtherwise],
        ['Existing primaries that conflict (never replaced here)', plan.routeCounts.existingPrimaryConflicts],
      ],
    ),
    '',
  );
  lines.push('## Rows per table', '');
  lines.push(...table(['Table', 'Rows written'], Object.entries(plan.tableCounts).map(([key, value]) => [key, value])), '');
  lines.push('Side rows written by the sanctioned RPCs, per created product:', '');
  lines.push(...table(['Table / effect', 'Per product'], Object.entries(plan.sideEffectsPerProduct).map(([key, value]) => [key, value])), '');
  lines.push('## Sanctioned write path (modeled on scripts/seed-staging-canonical-country-milk.mjs)', '');
  lines.push(
    '1. Pre-flight (read-only): every planned GTIN is still absent from `products`/`product_variants`, every planned route has no active primary, every route country exists in `catalog_market_countries`. Any mismatch stops the run before the first write.',
    '2. `gellatti_submit_product_request_v1` (QA Pro account, `p_market_country_code` = first route country, idempotency key `gellatti-v12-pr-ing:<productKey>`). An `existing_product` answer stops that product.',
    '3. `gellatti_admin_product_request_action_v1` `START_REVIEW`, then `ADMIN_EVIDENCE_PATCH` with the workbook evidence (declared values only — ESTIMATED values are never sent as label data).',
    '4. `preview_product_duplicates_v1`; a candidate with the same GTIN stops the product, a different-GTIN candidate is recorded as `duplicateDecision: different` with distinguishing evidence.',
    '5. `catalog-submit` (`source: admin`, `requireApprovalReady: true`, idempotency `product-request:<requestId>:approve-v12`, `market` = first route country). `approval_not_ready` writes no product (fail-closed) and the product is reported, not retried with other data.',
    '6. `APPROVE_LINK`, then one `product_canonical_slot_reviews` row for the base-slot PI (version-bound).',
    '7. `gellatti_admin_catalog_action_v1` `ADD_MARKET` for each further route country (same variant).',
    '8. `country_product_slot_assignments` `PRIMARY_DEFAULT` per route. The script refuses to replace or deactivate any existing assignment.',
    '',
  );
  lines.push('## Routable now vs blocked by the market FK', '');
  lines.push(
    `\`country_product_slot_assignments.country_code\` and \`product_add_requests.market_country_code\` both reference \`catalog_market_countries(code)\`, which holds ${registry.catalogSnapshot.catalogMarketCountries.length} markets: ${registry.catalogSnapshot.catalogMarketCountries.join(' ')}. \`gellatti_admin_catalog_action_v1 ADD_MARKET\` has the same restriction.`,
    '',
  );
  lines.push(`Markets that need a \`catalog_market_countries\` row before any of their routes can exist (${plan.marketRowsNeeded.length}):`, '');
  lines.push(...table(['Country', 'Blocked routes', 'Slots'], plan.marketRowsNeeded.map((entry) => [entry.country, entry.blockedRoutes, entry.slots.join(', ')])), '');
  lines.push('## Engine routability', '');
  lines.push(
    '`resolve_country_product_slots_v1` only returns a product that passes `private.exact_product_has_picker_profile_v1`: an active slot review on the current version, `engineUsable = true`, `BASE_RECIPE` permission, and numeric `water`, `totalSolids`, `fat`, `protein`, `carbohydrate`, `sugars`, `salt`. Identity-only or ESTIMATED products will not route even if an assignment exists.',
    '',
  );
  lines.push(
    ...table(
      ['Engine profile expectation', 'Products'],
      Object.entries(registry.counts.engineProfileExpectation).map(([key, value]) => [key, value]),
    ),
    '',
  );
  lines.push('Only DECLARED_PROFILE_COMPLETE products with a stated metric pack are in the package. The server still decides: catalog-submit may answer `approval_not_ready`, in which case no product is written for that item.', '');
  lines.push('## Existing routes', '');
  lines.push(
    ...table(
      ['Country', 'Slot PI', 'Active primary', 'v12 selection', 'Decision'],
      registry.catalogSnapshot.activePrimaryAssignments.map((row) => {
        const selection = registry.selections.find((entry) => entry.country === row.countryCode && entry.piIngId === row.mapperIngredientId);
        const conflict = plan.routeConflicts.find((entry) => entry.selectionKey === selection?.selectionKey);
        return [
          row.countryCode,
          row.mapperIngredientId,
          `${row.productCode} (EAN ${row.productEan})`,
          selection ? `${selection.productKey} — ${selection.localName}` : '—',
          conflict ? conflict.decision : selection?.route.decision ?? '—',
        ];
      }),
    ),
    '',
  );
  if (plan.routeConflicts.length > 0) {
    lines.push('Workbook instructions for the conflicting routes (quoted, not executed):', '');
    for (const conflict of plan.routeConflicts) {
      lines.push(`- ${conflict.selectionKey}: “${esc(conflict.workbookInstruction)}”`);
    }
    lines.push(
      '',
      'Replacing a live primary is a separate owner decision (deactivate the old row with a reason, then insert the new one). This package never does it.',
      '',
    );
  }
  lines.push('## Products created by this package', '');
  lines.push(
    ...table(
      ['Product key', 'Slot', 'Identity', 'Request market', 'ADD_MARKET', 'Routes', 'Idempotency key'],
      plan.productsToCreate.map((product) => [
        product.productKey,
        product.slot,
        product.gtin ? `GTIN ${product.gtin}` : product.identityBasis,
        product.requestMarket,
        product.additionalMarkets.join(' ') || '—',
        product.routes.map((route) => route.country).join(' '),
        product.requestIdempotencyKey,
      ]),
    ),
    '',
  );
  lines.push('## Deferred products (not written)', '');
  lines.push(
    ...table(
      ['Product key', 'Slot', 'Markets', 'Engine profile', 'Reasons'],
      plan.deferredProducts.map((product) => [product.productKey, product.slot, product.markets.join(' '), product.engineProfileExpectation, product.reasons.join(', ')]),
    ),
    '',
  );
  lines.push('## Rollback', '');
  lines.push(
    'Every step goes through an audited RPC or an RLS-guarded table; nothing is deleted. The apply run prints a ledger of every id it created — keep it.',
    '',
    '1. Routes: `update public.country_product_slot_assignments set active = false, approval_reason = \'rollback: <reason>\' where id = <assignment id>` as a CATALOG admin (the validation trigger re-stamps approved_by/approved_at). Deactivated rows stay for audit.',
    '2. Slot reviews: `update public.product_canonical_slot_reviews set active = false, approval_reason = \'rollback: <reason>\' where id = <review id>`.',
    '3. Extra markets: `gellatti_admin_catalog_action_v1(<product id>, \'REMOVE_MARKET\', {"market": "<ISO2>", "reason": "rollback"})`.',
    '4. Products: `gellatti_admin_catalog_action_v1(<product id>, \'UNPUBLISH\', {"reason": "rollback"})` hides the product and is reversible with `PUBLISH`. `RETIRE` runs the sanctioned `ingest_product_v1` retire operation and is final. An EAN keeps its single `product_variants` row forever, so prefer UNPUBLISH if the product may come back.',
    '5. Requests: approved requests stay APPROVED (terminal history). A request whose approval returned `approval_not_ready` stays open; close it with `REJECT` and a reason.',
    '6. Side rows (request events, notifications, the requester’s favourite, audit rows) are history and are not removed.',
    '',
  );
  lines.push('## Impact', '');
  lines.push(
    `- Production: the catalogue gains ${plan.productsToCreate.length} shared PR-ING products and ${plan.routeCounts.creatableNow} country defaults. Users whose product country is one of the routed markets will get these exact products as the country default in the HOME/PRO picker (user preferences still win).`,
    '- Mapper (`mapper_basement`, frozen 2541 file): untouched. No PI-ING is created.',
    '- Existing routes PL/ES milk stay as they are; FR milk is already correct.',
    '- The QA Pro account (requester) receives a favourite and a notification per approved product, as in the milk seed.',
    '',
  );
  return `${lines.join('\n')}\n`;
}
