/**
 * GELATO base v12 country products — types and loader for the registry
 * generated by scripts/countryProducts/importGelatoBaseV12.mjs from the owner
 * workbook GELLATTI_BAZA_GELATO_75_KRAJOW_v12_SYNC.xlsx.
 *
 * Exact country products are PR-ING proposals; they never create PI-ING. The six
 * base slots map only to existing Mapper PIs. PR-ING codes are issued by the
 * database at ingest — the registry carries proposal keys, not PR numbers.
 */

export const GELATO_BASE_V12_REGISTRY_SCHEMA = 'gellatti.country-products.gelato-base.registry/v1';
export const GELATO_BASE_V12_REGISTRY_ID = 'GELATO_BASE_V12';
export const GELATO_BASE_V12_REGISTRY_PATH = 'docs/country-products/gelato-base-v12/registry.json';
export const GELATO_BASE_V12_MANIFEST_PATH = 'docs/country-products/gelato-base-v12/manifest.json';
export const GELATO_BASE_V12_SOURCE_WORKBOOK = 'GELLATTI_BAZA_GELATO_75_KRAJOW_v12_SYNC.xlsx';
export const GELATO_BASE_V12_SOURCE_SHA256 =
  '09864e8602a6a7d3a89838091ce83dec7659bd2143517b5831d86f8d2f356172';

export const GELATO_BASE_SLOTS = ['MILK', 'CREAM', 'SMP', 'SUCROSE', 'DEXTROSE', 'STABILIZER'] as const;
export type GelatoBaseSlot = (typeof GELATO_BASE_SLOTS)[number];
export type ExactProductSlot = Exclude<GelatoBaseSlot, 'SUCROSE'>;
export const EXACT_PRODUCT_SLOTS: readonly ExactProductSlot[] = [
  'MILK',
  'CREAM',
  'SMP',
  'DEXTROSE',
  'STABILIZER',
];

/** Existing Mapper PIs of the 1000 g Gelato base (01_BAZA_PI). */
export const GELATO_BASE_SLOT_PI: Readonly<Record<GelatoBaseSlot, string>> = Object.freeze({
  MILK: 'PI-ING-000236',
  CREAM: 'PI-ING-000180',
  SMP: 'PI-ING-000270',
  SUCROSE: 'PI-ING-000514',
  DEXTROSE: 'PI-ING-000494',
  STABILIZER: 'PI-ING-000492',
});

/** Existing stabilizer PIs a STABILIZER slot may use (TARA is not mandatory). */
export const EXISTING_STABILIZER_PI_IDS = Object.freeze([
  'PI-ING-000492',
  'PI-ING-000472',
  'PI-ING-000475',
  'PI-ING-001384',
  'PI-ING-002114',
] as const);

export type NutrientField =
  | 'energyKcal'
  | 'fat'
  | 'saturatedFat'
  | 'carbohydrate'
  | 'sugars'
  | 'protein'
  | 'salt'
  | 'fibre';
export type NutrientValues = Readonly<Record<NutrientField, number | null>>;

export type SelectionState = 'SELECTION_CLOSED' | 'RESEARCH_OPEN' | 'BLOCKED' | 'GLOBAL_PI_READY';
export type DedupeDecision =
  | 'REUSE_EXISTING_PR'
  | 'NEW_PR_REQUIRED'
  | 'DUPLICATE_WITHIN_V12'
  | 'BLOCKED_EAN_HELD_BY_OTHER_CATALOG_ROW'
  | 'NOT_APPLICABLE_GLOBAL_PI';
export type RouteDecision =
  | 'ROUTE_ALREADY_PRESENT'
  | 'ROUTE_CREATABLE_NOW'
  | 'ROUTE_BLOCKED'
  | 'NOT_APPLICABLE_GLOBAL_PI';
export type EngineProfileExpectation =
  | 'DECLARED_PROFILE_COMPLETE'
  | 'ESTIMATED_OR_MISSING_LABEL_FIELDS'
  | 'DECLARED_BUT_DISPUTED_OPEN_CASE';
export type IdentityBasis = 'GTIN' | 'BRAND_ARTICLE_CODE' | 'LISTING_CODE' | 'NAME_HASH';

export interface GelatoBaseProduct {
  readonly productKey: string;
  readonly canonicalProposalKey: string;
  readonly slot: ExactProductSlot;
  readonly functionalSlot: ExactProductSlot;
  readonly workbookRole: string;
  readonly piIngId: string;
  readonly identity: {
    readonly basis: IdentityBasis;
    readonly gtin: string | null;
    readonly gtin14: string | null;
    readonly gtinSymbology: string | null;
    readonly gtinCheckDigitValid: boolean | null;
    readonly gtinRestrictedCirculation: boolean | null;
    readonly articleCode: string | null;
    readonly skuTexts: readonly string[];
  };
  readonly exactName: string | null;
  readonly brand: string | null;
  readonly brandKnown: boolean;
  readonly manufacturerOrSupplier: string | null;
  readonly origin: string | null;
  readonly labelLanguage: string | null;
  readonly package: {
    readonly text: string | null;
    readonly stated: boolean;
    readonly quantity: number | null;
    readonly unit: string | null;
    readonly multipackCount: number | null;
    readonly normalizedQuantity: number | null;
    readonly normalizedUnit: 'g' | 'ml' | null;
  };
  readonly ingredientsText: string | null;
  readonly allergensText: string | null;
  readonly nutrition: {
    readonly declaredBasis: string;
    readonly rawBasisText: string | null;
    readonly workingBasis: 'PER_100G';
    readonly normalization: 'GELLATTI_1ML_1G_NORMALIZATION' | null;
    readonly derivations: readonly string[];
    readonly declared: NutrientValues;
    readonly workingProfile: NutrientValues;
    readonly estimatedFields: readonly NutrientField[];
    readonly missingFields: readonly NutrientField[];
    readonly estimatedFieldsAcrossMarkets: readonly NutrientField[];
    readonly missingFieldsAcrossMarkets: readonly NutrientField[];
    readonly fibreDeclarationText: string | null;
    readonly workbookCompleteness: string | null;
    readonly carbohydrateConvention: string | null;
  };
  readonly technicalSpec: Readonly<Record<string, unknown>>;
  readonly sourceIds: readonly string[];
  readonly evidence: { readonly auditDates: readonly string[]; readonly latestEvidenceDate: string | null };
  readonly markets: readonly string[];
  readonly marketRoutes: ReadonlyArray<{
    readonly country: string;
    readonly proposalKey: string;
    readonly selectionState: SelectionState;
    readonly routeDecision: RouteDecision;
  }>;
  readonly readiness: {
    readonly engineProfileExpectation: EngineProfileExpectation;
    readonly expectedPickerRoutability: string;
    readonly blockers: readonly string[];
  };
  readonly catalog: {
    readonly decision: DedupeDecision;
    readonly existingPrIng: string | null;
    readonly existingProductName: string | null;
    readonly relatedExisting: ReadonlyArray<{ readonly productCode: string; readonly reason: string }>;
  };
  readonly dedupe: {
    readonly mergedProposalCount: number;
    readonly mergeBasis: readonly string[];
    readonly possibleDuplicates: readonly string[];
  };
  readonly reviewRequired: readonly string[];
}

export interface GelatoBaseSelection {
  readonly selectionKey: string;
  readonly country: string;
  readonly slot: GelatoBaseSlot;
  readonly functionalSlot: GelatoBaseSlot;
  readonly workbookRole: string;
  readonly piIngId: string;
  readonly grams: number;
  readonly selectionKind: 'EXACT_PRODUCT' | 'GLOBAL_PI';
  readonly proposalKey: string | null;
  readonly productKey: string | null;
  readonly dedupeDecision: DedupeDecision;
  readonly mergedIntoProposalKey?: string | null;
  readonly duplicateBasis?: string | null;
  readonly selectionState: SelectionState;
  readonly openGapId?: string | null;
  readonly localName?: string | null;
  readonly offerChannel?: string | null;
  readonly sourceIds?: readonly string[];
  readonly stabilizer?: {
    readonly stabilizerType: 'TARA';
    readonly taraMandatory: false;
    readonly offerChannel: string | null;
    readonly slotOption: string;
  } | null;
  readonly route: {
    readonly decision: RouteDecision;
    readonly blockers: readonly string[];
    readonly marketRowPresent?: boolean;
  };
}

export interface GelatoBaseOpenGap {
  readonly id: string;
  readonly priority: string;
  readonly state: 'OPEN' | 'BLOCKED';
  readonly country: string;
  readonly workbookRole: 'CREAM' | 'SMP' | 'DEXTROSE' | 'TARA';
  readonly slot: ExactProductSlot;
  readonly gapKind: string;
  readonly product: string;
  readonly conditions: readonly string[];
  readonly missing: string;
  readonly productKey: string | null;
  readonly stabilizerResearch?: {
    readonly taraMandatory: false;
    readonly missingMandatoryTara: false;
    readonly meaning: string;
  };
}

export interface GelatoBaseAlternative {
  readonly country: string;
  readonly slot: ExactProductSlot;
  readonly kind: string;
  readonly status: string;
  readonly name: string | null;
  readonly codeLabel: string | null;
  readonly code: string | null;
  readonly codeHasValidGs1CheckDigit: boolean | null;
  readonly selectedProductKey: string | null;
  readonly sourceRef: string;
}

export interface GelatoBaseRegistry {
  readonly schema: typeof GELATO_BASE_V12_REGISTRY_SCHEMA;
  readonly registryId: typeof GELATO_BASE_V12_REGISTRY_ID;
  readonly proposalNamespace: 'V12';
  readonly source: {
    readonly workbook: string;
    readonly sha256: string;
    readonly sheetsUsed: readonly string[];
    readonly openCasesV12: number | null;
  };
  readonly catalogSnapshot: {
    readonly capturedAt: string;
    readonly projectRef: string;
    readonly catalogMarketCountries: readonly string[];
  };
  readonly invariants: {
    readonly newPiCreated: number;
    readonly mapperModified: boolean;
    readonly prIngNumbersAssigned: boolean;
    readonly forcedTo75: boolean;
    readonly silentSubstitutes: number;
    readonly stabilizerTaraMandatory: boolean;
  };
  readonly base: ReadonlyArray<{
    readonly slot: GelatoBaseSlot;
    readonly grams: number;
    readonly piIngId: string;
    readonly stabilizerSlotRule: { readonly taraMandatory: false } | null;
  }>;
  readonly countries: ReadonlyArray<{
    readonly iso2: string;
    readonly iso3: string;
    readonly catalogMarketRowPresent: boolean;
  }>;
  readonly products: readonly GelatoBaseProduct[];
  readonly selections: readonly GelatoBaseSelection[];
  readonly openGaps: readonly GelatoBaseOpenGap[];
  readonly alternatives: readonly GelatoBaseAlternative[];
  readonly counts: {
    readonly products: number;
    readonly productsBySlot: Readonly<Record<ExactProductSlot, number>>;
    readonly newPiCreated: number;
    readonly proposalDecisions: Readonly<Record<string, number>>;
    readonly duplicatesPrevented: Readonly<Record<string, number>>;
    readonly openGaps: {
      readonly total: number;
      readonly byWorkbookRole: Readonly<Record<'CREAM' | 'SMP' | 'DEXTROSE' | 'TARA', number>>;
      readonly workbookHeader: Readonly<Record<'total' | 'CREAM' | 'SMP' | 'DEXTROSE' | 'TARA', number>>;
      readonly matchesWorkbookHeader: boolean;
    };
    readonly routes: Readonly<Record<string, unknown>>;
  };
  readonly sources: Readonly<Record<string, { readonly url: string }>>;
  readonly texts: Readonly<Record<string, string>>;
}

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

/** Validates the registry envelope; throws on any mismatch instead of guessing. */
export function parseGelatoBaseRegistry(raw: unknown): GelatoBaseRegistry {
  if (!isRecord(raw)) throw new Error('GELATO base registry: not a JSON object.');
  if (raw.schema !== GELATO_BASE_V12_REGISTRY_SCHEMA) {
    throw new Error(`GELATO base registry: unexpected schema ${String(raw.schema)}.`);
  }
  if (raw.registryId !== GELATO_BASE_V12_REGISTRY_ID) {
    throw new Error(`GELATO base registry: unexpected registryId ${String(raw.registryId)}.`);
  }
  const source = raw.source;
  if (!isRecord(source) || source.sha256 !== GELATO_BASE_V12_SOURCE_SHA256) {
    throw new Error('GELATO base registry: source workbook sha256 is not the pinned v12 workbook.');
  }
  for (const key of ['base', 'countries', 'products', 'selections', 'openGaps', 'alternatives']) {
    if (!Array.isArray(raw[key])) throw new Error(`GELATO base registry: ${key} must be an array.`);
  }
  if (!isRecord(raw.sources) || !isRecord(raw.texts) || !isRecord(raw.counts)) {
    throw new Error('GELATO base registry: sources, texts and counts must be objects.');
  }
  return raw as unknown as GelatoBaseRegistry;
}

export function loadGelatoBaseRegistryFromJson(json: string): GelatoBaseRegistry {
  return parseGelatoBaseRegistry(JSON.parse(json) as unknown);
}

const TEXT_ID = /^TXT-[0-9A-F]{10}$/;

/** Workbook notes longer than 120 characters are stored once in `texts`. */
export function resolveRegistryText(registry: GelatoBaseRegistry, value: string | null | undefined): string | null {
  if (value === null || value === undefined) return null;
  return TEXT_ID.test(value) ? (registry.texts[value] ?? value) : value;
}

export function sourceUrlsFor(registry: GelatoBaseRegistry, sourceIds: readonly string[]): string[] {
  return sourceIds.flatMap((id) => {
    const url = registry.sources[id]?.url;
    return url ? [url] : [];
  });
}

export function selectionFor(
  registry: GelatoBaseRegistry,
  country: string,
  slot: GelatoBaseSlot,
): GelatoBaseSelection | undefined {
  return registry.selections.find((selection) => selection.country === country && selection.slot === slot);
}

export function productFor(registry: GelatoBaseRegistry, productKey: string): GelatoBaseProduct | undefined {
  return registry.products.find((product) => product.productKey === productKey);
}

export function openGapsForRole(
  registry: GelatoBaseRegistry,
  role: GelatoBaseOpenGap['workbookRole'],
): GelatoBaseOpenGap[] {
  return registry.openGaps.filter((gap) => gap.workbookRole === role);
}
