/**
 * OWNER-LOCKED CONTRACT — GEL-P0-038.
 *
 * Ingredient availability is dormant internal capability. It is not customer
 * UX, while its persisted fields, writers and old-recipe readers remain intact.
 *
 * DO NOT EDIT THIS FILE TO MAKE AN IMPLEMENTATION PASS.
 * See `src/contracts/owner-locked/README.md`.
 */
import { describe, expect, it } from 'vitest';

import { DEFAULT_PRESET } from '@/data/demoPresets';
import { calculateRecipe, type RecipeInput } from '@/engine';
import { buildProductPickerSegments } from '@/features/ingredient-builder/productPickerCatalogPresentation';
import { savedToRecipeInput } from '@/features/recipes/recipePayload';

import { readCode } from './sourceContract';

const rowCode = () => readCode('features', 'ingredient-builder', 'IngredientRow.tsx');
const mobileCode = () =>
  readCode('features', 'ingredient-builder', 'IngredientLineControls.tsx');

describe('GEL-P0-038 — availability is hidden UX with preserved internal capability', () => {
  it('[AVAIL-UX-001] mobile ingredient editing renders no availability action or icon', () => {
    const row = rowCode();
    expect(row).not.toContain('icon="availability"');
    expect(row).not.toContain('Oznacz jako niedostępny');
    expect(row).not.toContain('Oznacz jako dostępny');
  });

  it('[AVAIL-UX-002] desktop ingredient editing uses the same action panel without availability', () => {
    const row = rowCode();
    expect(row).toContain('const articlePanelContent =');
    expect(row).toContain('{articlePanelContent}');
    expect(row).toContain('panelContent={articlePanelContent}');
    expect(row).not.toContain('actions.setIngredientUnavailable?.');
  });

  it('[AVAIL-UX-003] legacy availability metadata creates no visible badge or row state', () => {
    const row = rowCode();
    const mobile = mobileCode();
    const customerCopy = readCode('copy', 'en.ts');
    expect(row).not.toContain('data-unavailable=');
    expect(row).not.toContain('t.recipe.unavailableStatus');
    expect(mobile).not.toContain('t.recipe.unavailableStatus');
    expect(customerCopy).not.toContain('Oznacz jako niedostępny');
    expect(customerCopy).not.toContain('Oznacz jako dostępny');
    expect(customerCopy).not.toContain("unavailableStatus: 'NIEDOSTĘPNY'");
  });

  it('[AVAIL-UX-004] an old saved recipe retains availability metadata and calculates safely', () => {
    const legacy: RecipeInput = {
      items: structuredClone(DEFAULT_PRESET.items),
      mode: DEFAULT_PRESET.mode,
      category: DEFAULT_PRESET.category,
      target_temperature_c: DEFAULT_PRESET.target_temperature_c,
      target_batch_grams: DEFAULT_PRESET.target_batch_grams,
      machine_capacity_grams: DEFAULT_PRESET.machine_capacity_grams,
      goals: {
        flavor_intensity: DEFAULT_PRESET.flavor_intensity,
        cost_priority: DEFAULT_PRESET.cost_priority,
        excluded_ingredient_ids: ['PI-ING-000494'],
        unavailable_main_ingredient_ids: ['PI-ING-001553'],
      },
    };
    const before = calculateRecipe(legacy);
    const loaded = savedToRecipeInput(JSON.parse(JSON.stringify(legacy)));
    const after = calculateRecipe(loaded);

    expect(loaded.goals?.excluded_ingredient_ids).toEqual(['PI-ING-000494']);
    expect(loaded.goals?.unavailable_main_ingredient_ids).toEqual(['PI-ING-001553']);
    expect(after.total_batch_g).toBe(before.total_batch_g);
    expect(after.items.map((item) => [item.id, item.planned_grams])).toEqual(
      before.items.map((item) => [item.id, item.planned_grams]),
    );
  });

  it('[AVAIL-UX-005] central Search keeps canonical order, Recent and Favorites metadata', () => {
    const products = [
      {
        canonicalId: 'server-first',
        favorite: false,
        recent: false,
        sortTitle: 'Server',
        recentlyUsedAt: null,
      },
      {
        canonicalId: 'recent',
        favorite: false,
        recent: true,
        sortTitle: 'Recent',
        recentlyUsedAt: '2026-09-12T08:00:00.000Z',
      },
      {
        canonicalId: 'favorite',
        favorite: true,
        recent: false,
        sortTitle: 'Favorite',
        recentlyUsedAt: null,
      },
    ];

    expect(
      buildProductPickerSegments(products).map((segment) =>
        segment.items.map((product) => product.canonicalId),
      ),
    ).toEqual([['recent'], ['favorite', 'server-first']]);
    expect(
      buildProductPickerSegments(products, { activeQuery: true }).map((segment) =>
        segment.items.map((product) => product.canonicalId),
      ),
    ).toEqual([['recent'], ['server-first', 'favorite']]);
    expect(products.find((product) => product.canonicalId === 'favorite')?.favorite).toBe(true);
  });

  it('[AVAIL-UX-006] ProductBehavior, Engine and Solver authorities stay connected', () => {
    const builder = readCode('features', 'ingredient-builder', 'IngredientBuilder.tsx');
    const recipeInput = readCode('features', 'studio', 'buildRecipeInput.ts');
    const engineTypes = readCode('engine', 'types.ts');
    const solver = readCode('features', 'constraint-studio', 'applyPipeline.ts');

    expect(builder).toContain('productBehaviorModuleGate');
    expect(builder).toContain('productBehaviorBlockedMessage');
    expect(recipeInput).toContain('excluded_ingredient_ids');
    expect(recipeInput).toContain('unavailable_main_ingredient_ids');
    expect(engineTypes).toContain('excluded_ingredient_ids?: string[]');
    expect(engineTypes).toContain('unavailable_main_ingredient_ids?: string[]');
    expect(solver).toContain('excludedIngredientIds');
  });

  it('[AVAIL-UX-007] unrelated catalogue readiness and eligibility remain intact', () => {
    const mapper = readCode('services', 'productPicker', 'mapperSearch.ts');
    const library = readCode('features', 'ingredient-builder', 'ingredientLibrary.ts');
    const behavior = readCode(
      'features',
      'product-intelligence',
      'canonicalModuleEligibility.ts',
    );

    expect(mapper).toContain("kind: 'unavailable'; reason: CatalogueUnavailableReason");
    expect(library).toContain('unavailableMapperLibrary');
    expect(behavior).toContain('approvedForBase');
    expect(behavior).toContain('isActive');
  });

  it('[AVAIL-UX-008] Point 5B retains Crown, Replace, percent/grams and Info without availability', () => {
    const row = rowCode();
    const mobile = mobileCode();

    expect(row).toContain('<MainRoleTrigger');
    expect(row).toContain('label="Zamień produkt"');
    expect(row).toContain('label="Znajdź zamiennik"');
    expect(row).toContain('label="Dane składnika"');
    expect(mobile).toContain('row-mobile-percent-control-');
    expect(mobile).toContain('row-mobile-grams-control-');
    expect(row).not.toContain('icon="availability"');
  });

  it('retains the dormant model, writers and persisted recipe sidecars', () => {
    const rowMeta = readCode('features', 'ingredient-builder', 'ingredientTableUx.ts');
    const uxStore = readCode('features', 'ingredient-builder', 'ingredientTableUxStore.ts');
    const recipeStore = readCode('stores', 'recipeStore.ts');

    expect(rowMeta).toContain('unavailable: boolean');
    expect(uxStore).toContain('setUnavailable:');
    expect(recipeStore).toContain('markIngredientUnavailable:');
    expect(recipeStore).toContain('setIngredientUnavailable:');
    expect(recipeStore).toContain('excludedIngredientIds:');
    expect(recipeStore).toContain('unavailableMainIngredientIds:');
  });
});
