/**
 * OWNER-LOCKED CONTRACTS — nutrition/label permission for BASE_ONLY products.
 *
 * GEL-P0-028 A complete BASE_ONLY catalog product publishes nutrition and label
 *            facts. Nutrition permission is NOT derived from topping eligibility.
 *
 * Accepted 2026-09-05. `classify_catalog_product_behavior_v2` derived NUTRITION
 * and LABEL from `v_product_behavior_topping_accepted and v_topping`, so a
 * product whose owner-approved intendedUsageRole is BASE_ONLY could never hold
 * them, while the same classifier granted it PRODUCTION from the base path.
 * The resulting `PRODUCTION=true, NUTRITION=false` pair made the recipe
 * permanently non-current: the owner's CACAO PURO (PR-ING-007142, EAN
 * 8410109121551) could be recalculated and applied forever without the flow
 * ever completing.
 *
 * DO NOT EDIT THIS FILE TO MAKE AN IMPLEMENTATION PASS.
 * See `src/contracts/owner-locked/README.md`.
 */
import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

import { buildCurrentRecipeResultAuthority } from '@/features/pro-workbench/currentRecipeResultAuthority';
import { productBehaviorTestSnapshots } from '@/features/product-intelligence/productBehaviorTestFixture';
import { starterMilkBase } from '@/features/recipe-constraints/constraintFixtures';

import { SRC_ROOT, readCode } from './sourceContract';

const REPO_ROOT = resolve(SRC_ROOT, '..');

const readMigration = (name: string): string =>
  readFileSync(join(REPO_ROOT, 'supabase', 'migrations', name), 'utf8');

const permissionMigration = readMigration(
  '20260905120000_base_only_nutrition_label_permission.sql',
);
const reclassifyMigration = readMigration(
  '20260905120100_reclassify_base_only_nutrition_bindings.sql',
);

/**
 * The four independent inputs the classifier derives every catalog permission
 * from. `accepted` flags are the server-recomputed ProductBehavior authority;
 * `vBase` is engine usability plus a technical composition; `vTopping` is the
 * product's own label evidence — ingredients text, allergens text and a
 * nutrition object, on a product that is not verification-blocked.
 */
interface ClassifierInputs {
  baseAccepted: boolean;
  vBase: boolean;
  toppingAccepted: boolean;
  vTopping: boolean;
}

const IDENTIFIERS: Record<string, keyof ClassifierInputs> = {
  v_product_behavior_accepted: 'baseAccepted',
  v_base: 'vBase',
  v_product_behavior_topping_accepted: 'toppingAccepted',
  v_topping: 'vTopping',
};

/**
 * Extracts a permission expression from the migration's published replacement
 * block and evaluates its truth table. This asserts the derivation itself
 * rather than its spelling: a rewrite that changes the answer fails even if it
 * keeps every word.
 */
function permissionExpression(permission: string): (inputs: ClassifierInputs) => boolean {
  const block = permissionMigration.slice(permissionMigration.indexOf('v_new :='));
  const start = block.indexOf(`'${permission}',`);
  expect(start, `${permission} is not derived in the migration`).toBeGreaterThan(-1);
  const rest = block.slice(start + `'${permission}',`.length);
  // The last permission in the replacement block is terminated by the dollar
  // quote rather than by the next line, so accept whichever terminator is first.
  const end = [rest.indexOf(',\n'), rest.indexOf(',$new$')]
    .filter((index) => index !== -1)
    .sort((left, right) => left - right)[0];
  expect(end, `${permission} expression is unterminated`).toBeGreaterThan(0);
  const raw = rest.slice(0, end).trim();

  let js = raw.replace(/\s+/g, ' ');
  for (const [sqlName, key] of Object.entries(IDENTIFIERS)) {
    js = js.split(sqlName).join(`i.${key}`);
  }
  js = js.split(' and ').join(' && ').split(' or ').join(' || ');
  expect(js, `${permission} expression carries an unexpected token: ${raw}`).toMatch(
    /^[()\si.a-zA-Z&|]+$/,
  );
  return new Function('i', `return Boolean(${js});`) as (inputs: ClassifierInputs) => boolean;
}

const NUTRITION = permissionExpression('NUTRITION');
const LABEL = permissionExpression('LABEL');

const inputs = (overrides: Partial<ClassifierInputs> = {}): ClassifierInputs => ({
  baseAccepted: false,
  vBase: false,
  toppingAccepted: false,
  vTopping: false,
  ...overrides,
});

/** A BASE_ONLY product: accepted for base use, never topping-eligible. */
const BASE_ONLY_COMPLETE = inputs({ baseAccepted: true, vBase: true, vTopping: true });

describe('GEL-P0-028 A — a complete BASE_ONLY product is fully executable', () => {
  it('grants NUTRITION without any topping eligibility', () => {
    expect(BASE_ONLY_COMPLETE.toppingAccepted).toBe(false);
    expect(NUTRITION(BASE_ONLY_COMPLETE)).toBe(true);
    expect(LABEL(BASE_ONLY_COMPLETE)).toBe(true);
  });

  it('reaches a CURRENT recipe result once every module is eligible', () => {
    const recipe = starterMilkBase();
    const snapshots = productBehaviorTestSnapshots(recipe);
    const baseOnlyLine = recipe.items[0]!.id;
    // A BASE_ONLY catalog line: base and production eligible, never a topping.
    snapshots[baseOnlyLine] = {
      ...snapshots[baseOnlyLine]!,
      moduleEligibility: {
        ...snapshots[baseOnlyLine]!.moduleEligibility,
        BASE_RECIPE: 'eligible',
        MONITOR: 'eligible',
        NUTRITION: 'eligible',
        PRODUCTION: 'eligible',
        TOPPING: 'blocked',
      },
    };

    const authority = buildCurrentRecipeResultAuthority({
      recipe,
      toppings: [],
      snapshots,
      draftRevision: 1,
      awaitingRecalculation: false,
      loading: false,
    });

    // The line is base-eligible and production-eligible while never a topping.
    expect(snapshots[baseOnlyLine]!.moduleEligibility.BASE_RECIPE).toBe('eligible');
    expect(snapshots[baseOnlyLine]!.moduleEligibility.PRODUCTION).toBe('eligible');
    expect(snapshots[baseOnlyLine]!.moduleEligibility.TOPPING).toBe('blocked');
    expect(authority.moduleGates.MONITOR.ready).toBe(true);
    expect(authority.moduleGates.NUTRITION.ready).toBe(true);
    expect(authority.blockedModules).toEqual([]);
    expect(authority.state).toBe('CURRENT');
    expect(authority.ready).toBe(true);
  });
});

describe('GEL-P0-028 B — missing nutrition evidence still blocks NUTRITION', () => {
  it('refuses NUTRITION when the product carries no label evidence', () => {
    // Base-accepted and engine-usable, but no ingredients/allergens/nutrition.
    const missingEvidence = inputs({ baseAccepted: true, vBase: true, vTopping: false });
    expect(NUTRITION(missingEvidence)).toBe(false);
    expect(LABEL(missingEvidence)).toBe(false);
  });

  it('keeps the evidence predicate as a required conjunct on every branch', () => {
    // No combination without label evidence may ever yield the permission.
    for (const baseAccepted of [false, true]) {
      for (const vBase of [false, true]) {
        for (const toppingAccepted of [false, true]) {
          const withoutEvidence = inputs({
            baseAccepted,
            vBase,
            toppingAccepted,
            vTopping: false,
          });
          expect(NUTRITION(withoutEvidence)).toBe(false);
          expect(LABEL(withoutEvidence)).toBe(false);
        }
      }
    }
  });

  it('reclassification never grants a permission the evidence does not support', () => {
    expect(reclassifyMigration).toContain('label_evidence_complete');
    expect(reclassifyMigration).toContain(
      'product(s) without label evidence were granted NUTRITION',
    );
  });
});

describe('GEL-P0-028 C — topping-only behaviour is unchanged', () => {
  it('keeps the historical topping branch as an untouched disjunct', () => {
    const toppingOnly = inputs({ toppingAccepted: true, vTopping: true });
    expect(toppingOnly.baseAccepted).toBe(false);
    expect(NUTRITION(toppingOnly)).toBe(true);
    expect(LABEL(toppingOnly)).toBe(true);
    // The accepted expression is preserved verbatim, not re-derived.
    expect(permissionMigration).toContain('or (v_product_behavior_topping_accepted and v_topping)');
  });

  it('leaves the TOPPING permission derivation itself alone', () => {
    expect(permissionMigration).toContain(
      "'TOPPING',v_product_behavior_topping_accepted and v_topping",
    );
    expect(permissionMigration).toContain('TOPPING derivation drifted');
  });
});

describe('GEL-P0-028 D — PRODUCTION and NUTRITION are never split', () => {
  it('grants NUTRITION for exactly the base products PRODUCTION is granted for, given evidence', () => {
    // PRODUCTION's base branch is `baseAccepted and vBase`. Whenever that holds
    // and the product's own label evidence is complete, NUTRITION must hold too,
    // so the classifier cannot emit the contradictory executable pair.
    for (const toppingAccepted of [false, true]) {
      const productionBase = inputs({
        baseAccepted: true,
        vBase: true,
        toppingAccepted,
        vTopping: true,
      });
      expect(NUTRITION(productionBase)).toBe(true);
    }
  });

  it('proves why the split is fatal: the recipe can never become current', () => {
    const recipe = starterMilkBase();
    const snapshots = productBehaviorTestSnapshots(recipe);
    const line = recipe.items[0]!.id;
    snapshots[line] = {
      ...snapshots[line]!,
      moduleEligibility: {
        ...snapshots[line]!.moduleEligibility,
        PRODUCTION: 'eligible',
        NUTRITION: 'blocked',
      },
    };

    const authority = buildCurrentRecipeResultAuthority({
      recipe,
      toppings: [],
      snapshots,
      draftRevision: 1,
      awaitingRecalculation: false,
      loading: false,
    });

    // Recalculating and applying cannot change any of this: the block is a
    // permission, not a freshness state.
    expect(authority.blockedModules).toEqual(['NUTRITION']);
    expect(authority.ready).toBe(false);
    expect(authority.state).toBe('STALE');
    expect(authority.blockedLineIds).toContain(line);
  });

  it('keeps Production completion gated on nutrition as well as production', () => {
    const source = readCode('features', 'production-workspace', 'productionSession.ts');
    expect(source).toContain("recipeBehaviorModuleGate(authority, 'PRODUCTION')");
    expect(source).toContain("recipeBehaviorModuleGate(authority, 'NUTRITION')");
    expect(source).toContain('!productionGate.ready || !nutritionGate.ready');
  });

  it('keeps the current-result authority gating all four modules together', () => {
    const source = readCode('features', 'pro-workbench', 'currentRecipeResultAuthority.ts');
    for (const module of ['MONITOR', 'NUTRITION', 'COST', 'SUMMARY']) {
      expect(source).toContain(`'${module}'`);
    }
    expect(source).toContain('blockedModules.length === 0');
  });
});

describe('GEL-P0-028 E — mapper-reference products are untouched', () => {
  it('never rewrites the mapper classifier', () => {
    expect(permissionMigration).not.toContain('classify_mapper_product_behavior_v2');
    expect(reclassifyMigration).toContain('mapper-reference NUTRITION changed for');
  });

  it('only ever reclassifies non-mapper catalog product versions', () => {
    expect(reclassifyMigration).toContain("p.product_kind <> 'mapper_reference'");
    expect(reclassifyMigration).toContain("'catalog_product_version'");
  });

  it('reclassifies through the canonical queue, never by hand', () => {
    expect(reclassifyMigration).toContain('enqueue_product_behavior_reclassification_v1');
    expect(reclassifyMigration).toContain('process_product_behavior_reclassification_queue_v1');
    expect(reclassifyMigration).not.toMatch(
      /update\s+public\.product_behavior_bindings\s+set\s+profile_permissions/i,
    );
  });
});
