/**
 * OWNER-LOCKED CONTRACTS — Main / Crown.
 *
 * GEL-P0-001 Main at 1 g is active
 * GEL-P0-002 Crown ON at 0 g auto-seeds exactly 1 g
 * GEL-P0-003 Crown OFF restores 0 g only for an untouched auto-seed
 * GEL-P0-004 Crown preserves explicitly chosen user grams
 * GEL-P0-005 Crown MAXIMIZES — no fabricated ceiling
 * GEL-P0-006 Multi-Main preservation — one percent authority
 * GEL-P0-021 The Crown trigger is reachable in the ingredient row
 *
 * DO NOT EDIT THIS FILE TO MAKE AN IMPLEMENTATION PASS.
 * See `src/contracts/owner-locked/README.md`.
 */
import { describe, expect, it } from 'vitest';

import {
  CROWN_AUTO_SEED_GRAMS,
  clearCrownAutoSeeded,
  clearCrownAutoSeededLines,
  crownOffPlannedGrams,
  crownOnPlannedGrams,
  markCrownAutoSeeded,
} from '@/features/ingredient-builder/crownAutoSeed';

import { countOccurrences, readCode } from './sourceContract';

const applyPipeline = readCode('features', 'constraint-studio', 'applyPipeline.ts');
const mainEnvelope = readCode('features', 'product-intelligence', 'mainEnvelope.ts');
const ingredientRow = readCode('features', 'ingredient-builder', 'IngredientRow.tsx');
const lineControls = readCode('features', 'ingredient-builder', 'IngredientLineControls.tsx');
const recipeStore = readCode('stores', 'recipeStore.ts');

describe('GEL-P0-001 — a Main at 1 g is active', () => {
  // Accepted 2026-08-29 (616f65e6). A user-held / uncalibrated Main has no
  // published ceiling, so its proof can only ever be `best_achievable`. Gates
  // that accept `maximized` alone make every such Main inert on an on-batch
  // draft — the owner's "1 g dead zone".
  it('recognises a raised Main from either proof shape', () => {
    const predicate = applyPipeline.match(
      /const mainObjectiveRaisesMain[\s\S]*?startingMainGrams\) > MAIN_OBJECTIVE_EPSILON_G;/,
    )?.[0];
    expect(predicate, 'mainObjectiveRaisesMain must exist in applyPipeline').toBeTruthy();
    expect(predicate).toContain("'maximized'");
    expect(predicate).toContain("'best_achievable'");
  });

  it('consults that one predicate at every Preview production gate', () => {
    // ECO gate, OPTIMAL clean gate, and the `improved` clause. Three call
    // sites plus the declaration.
    expect(countOccurrences(applyPipeline, 'mainObjectiveRaisesMain')).toBeGreaterThanOrEqual(4);
  });
});

describe('GEL-P0-002 — Crown ON at 0 g seeds exactly one gram', () => {
  // A 0 g line is not a ProductBehavior "required" line, so no revalidation
  // pass ever visits it and the Standard->Crown transition strands the line
  // forever. Seeding 1 g is what makes the crowned line reachable again.
  it('seeds exactly 1 g and records the provenance', () => {
    expect(crownOnPlannedGrams(0)).toEqual({ plannedGrams: 1, autoSeeded: true });
    expect(CROWN_AUTO_SEED_GRAMS).toBe(1);
  });

  it('never seeds a value the owner did not ask for', () => {
    // No gram stack, no 2 g threshold, no solver workaround.
    expect(crownOnPlannedGrams(0).plannedGrams).toBe(1);
  });
});

describe('GEL-P0-003 — Crown OFF restores 0 g only for an untouched seed', () => {
  it('returns an untouched auto-seeded gram to zero', () => {
    expect(crownOffPlannedGrams(1, true)).toBe(0);
  });

  it('keeps a deliberately typed 1 g that we did not seed', () => {
    expect(crownOffPlannedGrams(1, false)).toBe(1);
  });

  it('keeps an auto-seeded line the user has since edited away from the seed', () => {
    expect(crownOffPlannedGrams(120, true)).toBe(120);
  });
});

describe('GEL-P0-004 — Crown preserves explicitly chosen user grams', () => {
  it('preserves a positive amount when the crown lands on it', () => {
    expect(crownOnPlannedGrams(170)).toEqual({ plannedGrams: 170, autoSeeded: false });
  });

  it('preserves pre-existing grams when the crown is removed', () => {
    expect(crownOffPlannedGrams(170, false)).toBe(170);
  });

  it('lets an explicit grams write clear the seed provenance', () => {
    const seeded = markCrownAutoSeeded([], 'line-a');
    expect(seeded).toEqual(['line-a']);
    expect(clearCrownAutoSeeded(seeded, 'line-a')).toEqual([]);
    expect(clearCrownAutoSeededLines(['line-a', 'line-b'], ['line-a'])).toEqual(['line-b']);
  });

  it('re-asserting an existing crown keeps the provenance', () => {
    expect(markCrownAutoSeeded(['line-a'], 'line-a')).toEqual(['line-a']);
  });

  it('never lets the transient seed flag reach a saved recipe', () => {
    // The flag is store state, not a RecipeItem field, so it can never reach
    // the Engine, a saved recipe_input, or a production payload.
    const partialize = recipeStore.match(
      /export function recipePersistPartialize[\s\S]*?\n}/,
    )?.[0];
    expect(partialize, 'recipePersistPartialize must exist').toBeTruthy();
    expect(partialize).not.toContain('crownAutoSeededLineIds');
  });
});

describe('GEL-P0-005 — Crown maximizes within the technical envelope', () => {
  // Owner rule: "There must be no arbitrary 200 g, 20%, or generic
  // uncalibrated ceiling." This enumerates every declared Main constant and
  // pins the accepted set, so a newly introduced cap fails the gate rather
  // than silently bounding the frontier.
  it('declares no Main constant that is a gram or percent ceiling', () => {
    const declared = [...applyPipeline.matchAll(/const (MAIN_[A-Z0-9_]+) = ([^;]+);/g)].map(
      (match) => [match[1], match[2]!.trim()] as const,
    );
    expect(Object.fromEntries(declared)).toEqual({
      // Whole-gram tolerance for "did the Main actually move".
      MAIN_OBJECTIVE_EPSILON_G: '0.05',
      // Search resolution — how many probes, never how large a Main may be.
      MAIN_OBJECTIVE_MAX_PROBES: '16',
      MAIN_TECHNICAL_MAXIMUM_ENABLED: 'true',
      MAIN_TECHNICAL_PROBE_BUDGET: '2_000',
      MAIN_TECHNICAL_NO_CEILING_COARSE_PROBES: '12',
      MAIN_TECHNICAL_NO_CEILING_REFINE_PROBES: '12',
    });
  });

  it('derives the frontier bounds from published product authority', () => {
    // Floor and ceiling come from the resolver snapshot; the upper bound comes
    // from the LP. None of them is invented in the pipeline.
    expect(applyPipeline).toContain('mainEnvelopeSearchFloorGrams');
    expect(applyPipeline).toContain('mainTechnicalLinearUpperBound');
    expect(mainEnvelope).toContain('export function mainEnvelopeSearchCeilingGrams');
    expect(mainEnvelope).toContain('export function mainEnvelopeSearchFloorGrams');
  });
});

describe('GEL-P0-006 — Multi-Main preservation', () => {
  it('keeps one percent authority with the batch as denominator', () => {
    // equivalent_grams = SUM(grams x factor); percent = equivalent /
    // target_batch_grams x 100, multiplied by 100 exactly once, inside the
    // authority. A second percent computation elsewhere is how the owner got
    // three different verdicts for one state.
    const formula = mainEnvelope.match(/const equivalentPercent =[\s\S]*?;\n/)?.[0];
    expect(formula, 'verifyMainEnvelope must compute the combined percent').toBeTruthy();
    expect(formula).toContain('input.recipe.target_batch_grams');
    expect(countOccurrences(formula!, '* 100')).toBe(1);
    // equivalent_grams = SUM(grams x factor) — the factor is the resolver's,
    // never a name-derived guess.
    expect(mainEnvelope).toContain('item.planned_grams * (snapshot.mainEquivalentFactor ?? 0)');
  });

  it('keeps verifyMainEnvelope as the single exported envelope authority', () => {
    expect(mainEnvelope).toContain('export function verifyMainEnvelope');
  });
});

describe('GEL-P0-021 — the Crown trigger is reachable in the ingredient row', () => {
  // 2026-08-26: `f5d57bdf` ("unify main badges") deleted the only control that
  // could crown a line, leaving a display-only badge. Staging shipped for ~9
  // hours with no way to set a Main from the row, on desktop or mobile.
  // `1c94d67c` restored it. This contract makes that deletion impossible to
  // repeat silently.
  it('exports a Main role trigger control', () => {
    expect(lineControls).toContain('export function MainRoleTrigger');
  });

  it('renders the trigger in the recipe row for a line that is not yet Main', () => {
    expect(ingredientRow).toContain('MainRoleTrigger');
    // Both responsive presentations must offer it: the desktop row and the
    // mobile line. One render site means one of them lost the control.
    expect(countOccurrences(ingredientRow, '<MainRoleTrigger')).toBeGreaterThanOrEqual(2);
  });

  it('wires the trigger to the Main role write', () => {
    expect(ingredientRow).toContain("setRole('main')");
  });
});
