/**
 * GEL-P0-032 The PRO label belongs only to the current recipe.
 *
 * The workbench always renders the accepted flow: label first, then the two
 * print/settings actions. Missing-data editing is intentionally absent from
 * the main surface and is shared by Settings and the pre-print dialog.
 * Persistent label settings stay on their canonical `/labels` screen and
 * never reappear inside PRO → Etykieta.
 * A completed Production snapshot may replace the live draft only when its
 * recipe id, recipe version and source fingerprint all match the current
 * recipe; changing recipes or recipe content falls back to the current draft.
 *
 * DO NOT EDIT THIS FILE TO MAKE AN IMPLEMENTATION PASS.
 * See `src/contracts/owner-locked/README.md`.
 */
import { describe, expect, it } from 'vitest';
import { readCode } from './sourceContract';

const panel = readCode('features', 'pro-workbench', 'RecipeProfilePanel.tsx');
const authority = readCode('features', 'pro-workbench', 'currentRecipeLabelSnapshot.ts');
const workspace = readCode('features', 'master-label', 'LabelWorkspace.tsx');
const draft = readCode('features', 'master-label', 'DraftLabelCard.tsx');
const router = readCode('app', 'router.tsx');

describe('GEL-P0-032 — the label belongs to the current recipe', () => {
  it('gates the completed snapshot through one current-recipe authority', () => {
    expect(panel).toContain('currentRecipeCompletionSnapshot(production)');
    expect(panel).not.toContain('production?.session?.completionSnapshot ?? null');
  });

  it('requires current recipe, version and source fingerprint agreement', () => {
    for (const guard of [
      'recipeId',
      'recipeVersionId',
      'recipeVersionNumber',
      'currentSourceFingerprint',
      'productionSourceFingerprint',
    ]) {
      expect(authority, guard).toContain(guard);
    }
  });
});

describe('GEL-P0-032 — PRO keeps the accepted label flow', () => {
  it('renders the label, then only the workbench actions on the main surface', () => {
    const label = workspace.indexOf('data-testid="consumer-print-boundary"');
    const actions = workspace.indexOf('data-testid="label-workbench-print-actions"');
    expect(label).toBeGreaterThan(-1);
    expect(actions).toBeGreaterThan(label);
    expect(workspace).not.toContain('data-testid="label-missing-data-stack"');
    expect(workspace).toContain('<MissingLabelDataSettings');
    expect(workspace).toContain('<PrintMissingDataDialog');
  });

  it('keeps settings out of both pre- and post-production PRO label surfaces', () => {
    expect(draft).not.toContain('label-settings-home-link');
    expect(workspace).not.toContain('label-settings-home-link');
    expect(workspace).not.toContain('to="/labels"');
  });

  it('preserves the separate canonical label settings screen', () => {
    expect(router).toContain('path="/labels"');
  });
});
