/**
 * OWNER-LOCKED CONTRACTS — Preview / Apply / Direction / Production Rescue.
 *
 * GEL-P0-013 Direction fallback
 * GEL-P0-014 Preview before Apply
 * GEL-P0-015 Apply / Undo
 * GEL-P0-018 Production Rescue protected contract
 *
 * DO NOT EDIT THIS FILE TO MAKE AN IMPLEMENTATION PASS.
 * See `src/contracts/owner-locked/README.md`.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { SRC_ROOT, countOccurrences, readCode } from './sourceContract';

const applyPipeline = readCode('features', 'constraint-studio', 'applyPipeline.ts');
const practicalRecipe = readCode('features', 'practical-recipe', 'practicalRecipe.ts');
const rescueManifest = JSON.parse(
  readFileSync(
    join(SRC_ROOT, '..', 'supabase/functions/_shared/generated/productionRescueEngine.manifest.json'),
    'utf8',
  ),
) as {
  bundle: { externalImports: number; dynamicImports: number };
  sourceClosure: unknown[];
};

describe('GEL-P0-013 — Direction fallback', () => {
  // The five-level sweep needs enough solver rounds to converge; dropping back
  // to 12 reintroduced the -2/-1/0 collapse the owner rejected, and measured
  // SLOWER because exhausted runs fell into expensive failure paths.
  it('keeps the accepted solver round budget', () => {
    expect(applyPipeline).toContain('export const MAX_SOLVER_ROUNDS = 18;');
  });

  it('keeps a truthful NEAREST path rather than failing closed', () => {
    // An unreached exact target must still be able to produce a truthful
    // NEAREST proposal that the user may consent to.
    expect(applyPipeline).toContain('direction_consent_required');
    expect(applyPipeline).toContain('hasActiveExactDirectionObjective');
  });

  it('keeps the Sorbet exact-point fast path reachable from the shared builder', () => {
    expect(applyPipeline).toContain('buildSorbetDirectionCandidatePreview');
  });
});

describe('GEL-P0-014 — Preview before Apply', () => {
  it('never applies without a verified whole-gram executable proof', () => {
    expect(applyPipeline).toContain("code: 'practicalization_invalid'");
    expect(applyPipeline).toContain("reason: 'missing_proof'");
  });

  it('re-derives the practicalization at the door instead of trusting the preview', () => {
    // The Apply door recomputes and compares, so a preview cannot smuggle a
    // candidate the pipeline would not produce again.
    expect(applyPipeline).toContain('practicalizeRecipeCandidate');
    expect(applyPipeline).toContain("'candidate_fingerprint_mismatch'");
  });

  it('keeps the zero-gram executable invariant on the shared boundary', () => {
    expect(practicalRecipe).toContain('isOmittableUnusedLine');
    expect(practicalRecipe).toContain('unusedZeroGramLineIds');
  });
});

describe('GEL-P0-015 — Apply / Undo', () => {
  it('keeps one verified Apply door', () => {
    expect(applyPipeline).toContain('export class VerifiedApply');
    expect(applyPipeline).toContain('export const commitPreview = VerifiedApply.commit.bind');
  });

  it('re-verifies both accepted Main proof shapes at the door', () => {
    // A user-held Main proves `best_achievable`; a calibrated one proves an
    // exact maximum. Accepting only one shape is what made user-held Mains
    // inert, so the door must still verify both.
    expect(applyPipeline).toContain('exactMaximumProof');
    expect(applyPipeline).toContain('boundedBestProof');
  });

  it('refuses to change material already physically in the vessel', () => {
    expect(applyPipeline).toContain("code: 'physical_actual_violated'");
  });

  it('refuses a Main identity or ingredient identity substitution without authority', () => {
    expect(applyPipeline).toContain("code: 'ingredient_identity_violated'");
    expect(applyPipeline).toContain("code: 'main_identity_violated'");
  });
});

describe('GEL-P0-018 — Production Rescue protected contract', () => {
  // The Rescue Edge bundle is a security-reviewed pure source closure. Editing
  // any bundled source (even reformatting it) without regenerating the bundle
  // ships an Edge function that no longer matches the audited sources.
  it('bundles only the audited pure closure', () => {
    expect(rescueManifest.bundle.externalImports).toBe(0);
    expect(rescueManifest.bundle.dynamicImports).toBe(0);
    expect(rescueManifest.sourceClosure.length).toBeGreaterThan(0);
  });

  it('keeps the rescue authority behind the service boundary', () => {
    expect(countOccurrences(applyPipeline, 'productionRescue')).toBeGreaterThanOrEqual(0);
    // The bundled sources are reviewed; practicalRecipe is one of them and must
    // stay import-light so the closure cannot silently grow.
    expect(practicalRecipe).not.toContain("from '@/stores/");
  });
});
