/**
 * OWNER-LOCKED CONTRACTS — Gellatti customer language.
 *
 * GEL-P0-030 The customer never makes a mistake, and never reads Engine
 *            internals. Customer-facing copy states the CURRENT STATE and the
 *            SOLUTION — never FAULT → BLAME → CORRECTION.
 *
 * Accepted 2026-09-05 as a global product rule. Gellatti does not judge what
 * happened in the vessel; it reads the physical state and solves it. The rule
 * applies wherever customer copy describes a deviation from an expected state —
 * HOME, PRO, Production, Rescue and the scanner flows.
 *
 * DO NOT EDIT THIS FILE TO MAKE AN IMPLEMENTATION PASS.
 * See `src/contracts/owner-locked/README.md`.
 */
import fs from 'node:fs';
import path from 'node:path';

import ts from 'typescript';
import { describe, expect, it } from 'vitest';

const SOURCE_ROOT = path.join(process.cwd(), 'src');
const SKIPPED_PATH =
  /(?:\.test\.|\.spec\.|\/pages\/dev\/|\/__fixtures__\/|\/__campaign__\/|\/qa\/)/;

interface LiteralEntry {
  file: string;
  line: number;
  text: string;
}

const sourceFiles = (): string[] => {
  const result: string[] = [];
  const visit = (directory: string) => {
    for (const item of fs.readdirSync(directory, { withFileTypes: true })) {
      const fullPath = path.join(directory, item.name);
      if (item.isDirectory()) visit(fullPath);
      else if (/\.tsx?$/.test(item.name) && !SKIPPED_PATH.test(fullPath)) result.push(fullPath);
    }
  };
  visit(SOURCE_ROOT);
  return result.sort();
};

const literalEntries = (): LiteralEntry[] => {
  const entries: LiteralEntry[] = [];
  for (const absolutePath of sourceFiles()) {
    const source = fs.readFileSync(absolutePath, 'utf8');
    const sourceFile = ts.createSourceFile(
      absolutePath,
      source,
      ts.ScriptTarget.Latest,
      true,
      absolutePath.endsWith('.tsx') ? ts.ScriptKind.TSX : ts.ScriptKind.TS,
    );
    const relative = path.relative(process.cwd(), absolutePath);
    const visit = (node: ts.Node) => {
      if (ts.isStringLiteralLike(node)) {
        const parent = node.parent;
        const isSpecifier =
          (ts.isImportDeclaration(parent) || ts.isExportDeclaration(parent)) &&
          parent.moduleSpecifier === node;
        if (!isSpecifier) {
          entries.push({
            file: relative,
            line: sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile)).line + 1,
            text: node.text.trim(),
          });
        }
      } else if (ts.isJsxText(node) && node.getText(sourceFile).trim()) {
        entries.push({
          file: relative,
          line: sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile)).line + 1,
          text: node.getText(sourceFile).trim(),
        });
      }
      ts.forEachChild(node, visit);
    };
    visit(sourceFile);
  }
  return entries;
};

/**
 * Customer copy lives in `.tsx` views and the copy modules. Diagnostics,
 * Owner reports and solver traces are deliberately outside this boundary —
 * they exist to carry exactly the vocabulary this rule keeps off the screen.
 */
const isCustomerCopyFile = (file: string): boolean =>
  (file.endsWith('.tsx') || file.startsWith('src/copy/')) &&
  !file.includes('/design-review/') &&
  !file.includes('Diagnostic') &&
  !file.includes('diagnostics');

const format = (entries: LiteralEntry[]): string =>
  entries.map((entry) => `${entry.file}:${entry.line} ${JSON.stringify(entry.text)}`).join('\n');

const ENTRIES = literalEntries();

describe('GEL-P0-030 — the customer never makes a mistake', () => {
  it('never blames, judges or attributes an error to the customer', () => {
    // Second person + fault. Gellatti reads the vessel, it does not accuse.
    const blame =
      /\b(?:zrobiłeś|popełniłeś|pomyliłeś|przekroczyłeś|źle\s+(?:odważ|wpisał|dodał|zmierzy))\w*\b|\bdodałeś\s+za\s+(?:dużo|mało)\b|\bbłąd\s+(?:użytkownika|operatora)\b|\bbłędna\s+ilość\b|\btwój\s+błąd\b/i;
    expect(format(ENTRIES.filter((e) => isCustomerCopyFile(e.file) && blame.test(e.text)))).toBe(
      '',
    );
  });

  it('never calls a physical quantity wrong or incorrect', () => {
    const judgement =
      /\b(?:nieprawidłow|niepoprawn|błędn)\w*\s+(?:ilość|ilości|waga|wagę|gramatur)\w*/i;
    expect(
      format(ENTRIES.filter((e) => isCustomerCopyFile(e.file) && judgement.test(e.text))),
    ).toBe('');
  });
});

describe('GEL-P0-030 — Engine internals stay out of customer copy', () => {
  // These are real, useful words — in diagnostics, tests and Owner reports.
  // They are never an answer to a person standing at a machine.
  const INTERNALS =
    /\b(?:NPAC|POD|PAC)\b|\bhard[- ]bound\b|\bsolver\b|\bdenominator\b|\bmianownik\b|\bfunkcja\s+celu\b|\bobjective\s+function\b/;

  /**
   * Surfaces a customer reaches while a batch is physically in front of them.
   * The rule is absolute here: a deviation is answered with the current state
   * and the solution, never with the vocabulary the solver reasons in.
   */
  const isProductionSurface = (file: string): boolean =>
    file.includes('/production-workspace/') ||
    file.includes('/pro-core/Production') ||
    /Production|Rescue/.test(path.basename(file));

  it('never reaches a customer anywhere in Production or Rescue', () => {
    const violations = ENTRIES.filter(
      (entry) =>
        isCustomerCopyFile(entry.file) &&
        isProductionSurface(entry.file) &&
        INTERNALS.test(entry.text),
    );
    expect(format(violations)).toBe('');
  });

  /**
   * The rest of the application carries a known, finite debt: Monitor axis
   * labels that pair a friendly name with its technical token, the education
   * surface that deliberately EXPLAINS the tokens, and the Studio optimization
   * panels. Pinning the exact set means the global rule still bites — a NEW
   * leak on any screen fails this contract — while this workstream is not
   * broadened into unrelated copy rewrites. Shrinking this list is always
   * allowed; growing it is an owner decision.
   */
  const KNOWN_DEBT = new Set([
    'src/copy/education.pl.ts',
    'src/copy/en.ts',
    'src/features/customer-shell/ui/gallery/CustomerUiGallery.tsx',
    'src/features/optimization/BranchWorkflowPreviewPanel.tsx',
    'src/features/optimization/OptimizationPreviewPanel.tsx',
  ]);

  it('appears on no customer screen outside the recorded debt', () => {
    const violations = ENTRIES.filter(
      (entry) =>
        isCustomerCopyFile(entry.file) && !KNOWN_DEBT.has(entry.file) && INTERNALS.test(entry.text),
    );
    expect(format(violations)).toBe('');
  });

  it('never states a raw composition percentage as the reason shown to a customer', () => {
    // "laktoza 6,19 %" is a diagnostic fact, not a customer sentence.
    const composition =
      /\b(?:laktoz|sucha\s+masa|total\s+solids|zawartość\s+wody)\w*\b[^.]{0,24}%|\b%\s*(?:laktozy|suchej\s+masy)\b/i;
    expect(
      format(ENTRIES.filter((e) => isCustomerCopyFile(e.file) && composition.test(e.text))),
    ).toBe('');
  });
});
