/**
 * OWNER-LOCKED CONTRACTS — machine + batch authority.
 *
 * GEL-P0-007 A fresh Professional recipe is 1000 g
 * GEL-P0-008 A Professional manual batch persists
 * GEL-P0-009 Home machine canonical defaults
 * GEL-P0-010 Custom machine batch stays fully manual
 *
 * DO NOT EDIT THIS FILE TO MAKE AN IMPLEMENTATION PASS.
 * See `src/contracts/owner-locked/README.md`.
 */
import { describe, expect, it } from 'vitest';

import { MACHINE_CATALOG } from '@/features/machine-catalog';
import { DEFAULT_NEW_RECIPE_BATCH_G } from '@/features/recipes/newRecipeStarter';
import {
  MACHINE_PREFERENCE_SCHEMA_VERSION,
  type MachinePreferenceRecord,
  effectiveDefaultBatchGrams,
  recommendedBatchGramsOf,
  usesCustomDefaultBatch,
  withUserDefaultBatch,
} from '@/features/machine-onboarding/preferenceContracts';
import { readCode } from './sourceContract';

const recipeStore = readCode('stores', 'recipeStore.ts');

/** A minimal real preference record: recommendation 700 g, no user override. */
const preferenceRecord = (
  overrides: Partial<MachinePreferenceRecord> = {},
): MachinePreferenceRecord =>
  ({
    schemaVersion: MACHINE_PREFERENCE_SCHEMA_VERSION,
    selection: { kind: 'catalog', machineId: MACHINE_CATALOG[0]!.id },
    market: 'EU',
    resolvedTechnology: 'batch_freezer',
    resolvedVisibleMode: 'gelato',
    capacity: {},
    defaultBatch: {
      kind: 'grams',
      grams: 700,
      source: 'manufacturer_batch_grams',
      safetyFactorApplied: null,
      ruleVersion: 'test',
      estimated: false,
    },
    userDefaultBatchGrams: null,
    customContainer: null,
    setAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    catalogVersion: 'test',
    ...overrides,
  }) as MachinePreferenceRecord;

describe('GEL-P0-007 — a fresh Professional recipe is 1000 g', () => {
  // 2026-08-28: `e00175d3` ("enforce canonical batch coherence") made
  // Professional inherit `defaults.targetBatchGrams` — a Home machine figure —
  // so a fresh Professional recipe stopped opening at the canonical batch.
  // `ee70985c` restored it hours later.
  it('pins the canonical fresh-recipe batch to 1000 g', () => {
    expect(DEFAULT_NEW_RECIPE_BATCH_G).toBe(1000);
  });

  it('defines the Professional default AS the canonical batch, not a copy of it', () => {
    // Asserted at source level on purpose: `recipeStore` participates in an
    // import cycle, so a value import of this constant resolves to `undefined`
    // in an isolated test. A duplicated literal here would also let the two
    // numbers drift apart silently, which is exactly what must not happen.
    expect(recipeStore).toContain(
      'export const PROFESSIONAL_DEFAULT_BATCH_GRAMS = DEFAULT_NEW_RECIPE_BATCH_G;',
    );
  });

  it('applies a machine batch to a fresh starter only for a Home machine', () => {
    // The gate is the machine KIND. Without it, a Professional account
    // silently inherits whichever machine figure happens to be stored.
    const starter = recipeStore.match(
      /buildCanonicalNewRecipeStarter\(\{[\s\S]*?targetBatchGrams:[\s\S]*?\}\)/,
    )?.[0];
    expect(starter, 'the fresh starter must choose its batch explicitly').toBeTruthy();
    expect(starter).toContain("defaults?.machineKind === 'home'");
    expect(starter).toContain('PROFESSIONAL_DEFAULT_BATCH_GRAMS');
  });
});

describe('GEL-P0-008 — a Professional manual batch persists', () => {
  it('carries the batch in the persisted recipe state', () => {
    const partialize = recipeStore.match(/export function recipePersistPartialize[\s\S]*?\n}/)?.[0];
    expect(partialize, 'recipePersistPartialize must exist').toBeTruthy();
    expect(partialize).toContain('target_batch_grams');
  });

  it('keeps an explicit user default batch as the effective batch', () => {
    const record = preferenceRecord({ userDefaultBatchGrams: 1500 });
    expect(effectiveDefaultBatchGrams(record)).toBe(1500);
    // The recommendation still exists underneath — it is not overwritten.
    expect(recommendedBatchGramsOf(record)).toBe(700);
  });
});

describe('GEL-P0-009 — Home machine canonical defaults', () => {
  it('ships a versioned, non-empty canonical machine catalog', () => {
    expect(MACHINE_CATALOG.length).toBeGreaterThan(0);
  });

  it('gives every canonical machine a stable identity and capacity', () => {
    for (const machine of MACHINE_CATALOG) {
      expect(machine.id, 'every catalog machine needs a stable id').toBeTruthy();
      expect(typeof machine.id).toBe('string');
    }
    const ids = MACHINE_CATALOG.map((machine) => machine.id);
    expect(new Set(ids).size, 'catalog machine ids must be unique').toBe(ids.length);
  });

  it('falls back to the recommendation when the user has set no default', () => {
    const record = preferenceRecord();
    expect(effectiveDefaultBatchGrams(record)).toBe(recommendedBatchGramsOf(record));
    expect(effectiveDefaultBatchGrams(record)).toBe(700);
  });
});

describe('GEL-P0-010 — custom machine batch stays fully manual', () => {
  // A custom container has no manufacturer figure to recommend from, so the
  // owner's number is the only authority. Nothing may overwrite it silently.
  it('treats a user default that diverges from the recommendation as custom', () => {
    expect(usesCustomDefaultBatch(preferenceRecord({ userDefaultBatchGrams: 1234 }))).toBe(true);
    expect(usesCustomDefaultBatch(preferenceRecord())).toBe(false);
  });

  it('accepts an explicit manual batch and offers clearing as the only way back', () => {
    const record = preferenceRecord();
    const manual = withUserDefaultBatch(record, 1500, '2026-01-02T00:00:00.000Z');
    expect(manual?.userDefaultBatchGrams).toBe(1500);
    const cleared = withUserDefaultBatch(manual!, null, '2026-01-03T00:00:00.000Z');
    expect(cleared?.userDefaultBatchGrams).toBeNull();
  });

  it('refuses a dishonest manual batch rather than coercing it', () => {
    const record = preferenceRecord();
    expect(withUserDefaultBatch(record, 0, '2026-01-02T00:00:00.000Z')).toBeNull();
    expect(withUserDefaultBatch(record, -5, '2026-01-02T00:00:00.000Z')).toBeNull();
    expect(withUserDefaultBatch(record, Number.NaN, '2026-01-02T00:00:00.000Z')).toBeNull();
  });
});
