/**
 * OWNER-LOCKED CONTRACTS — Mapper lineage resolution.
 *
 * GEL-P0-029 A catalog product's acceptance resolves against the CURRENT Mapper
 *            behaviour binding for its referenced ingredient. The stored
 *            `mapperBehaviorBindingId` is historical provenance only.
 *
 * Accepted 2026-09-05. `classify_catalog_product_behavior_v2` required the exact
 * historical binding row to still be `is_current`. The 2026-08-29
 * `canonical-module-eligibility-v1` sweep superseded every Mapper binding and
 * re-enqueued dependants by `catalog_binding.mapper_ingredient_id` — NULL for PR
 * products — so 9 of 12 active catalog products were left pointing at retired
 * rows. Reclassifying one set BASE_RECIPE, MONITOR, NUTRITION, PRODUCTION and
 * SAVE all false. A product mapped to PI-ING-001313 does not stop being mapped
 * to PI-ING-001313 because a newer behaviour row was published for it.
 *
 * DO NOT EDIT THIS FILE TO MAKE AN IMPLEMENTATION PASS.
 * See `src/contracts/owner-locked/README.md`.
 */
import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

import { SRC_ROOT } from './sourceContract';

const REPO_ROOT = resolve(SRC_ROOT, '..');
const migration = readFileSync(
  join(REPO_ROOT, 'supabase', 'migrations', '20260905150000_mapper_lineage_current_binding.sql'),
  'utf8',
);

/** Only the `v_new := $new$ … $new$` bodies are the published predicate. */
const PUBLISHED_BLOCKS = [...migration.matchAll(/v_new := \$new\$([\s\S]*?)\$new\$/g)].map(
  (match) => match[1] ?? '',
);
const PUBLISHED = PUBLISHED_BLOCKS.join('\n');

/**
 * The conjuncts the published predicate is required to carry. The scenario
 * model below evaluates exactly these, so a predicate that loses one fails here
 * before the model can disagree with it.
 */
const REQUIRED_CONJUNCTS = [
  'referenced_ingredient.ingredient_id=v_behavior_reference',
  'referenced_ingredient.is_active',
  'provenance_binding.id::text=',
  'provenance_binding.mapper_ingredient_id=v_behavior_reference',
  'authority_binding.mapper_ingredient_id=v_behavior_reference',
  'authority_binding.is_current',
] as const;

/** A world the classifier has to answer about. */
interface Lineage {
  /** productBehaviorAuthority.referenceMapperIngredientId */
  reference: string | null;
  /** Mapper ingredients that exist and are active. */
  activeIngredients: string[];
  /** The stored historical provenance row: which ingredient it belongs to. */
  storedBindingIngredient: string | null;
  /** Whether that stored row is itself still `is_current`. */
  storedBindingIsCurrent: boolean;
  /** Current bindings, by ingredient, with their BASE_RECIPE permission. */
  currentBindings: { ingredient: string; baseRecipe: boolean }[];
}

/**
 * The accepted resolution, expressed exactly as the published conjuncts:
 * a reference, an existing active ingredient, coherent provenance, and a
 * CURRENT binding for that SAME ingredient carrying BASE_RECIPE.
 */
function baseAccepted(world: Lineage): boolean {
  if (world.reference === null) return false;
  if (!world.activeIngredients.includes(world.reference)) return false;
  if (world.storedBindingIngredient !== world.reference) return false;
  return world.currentBindings.some(
    (binding) => binding.ingredient === world.reference && binding.baseRecipe,
  );
}

const world = (overrides: Partial<Lineage> = {}): Lineage => ({
  reference: 'PI-ING-001313',
  activeIngredients: ['PI-ING-001313'],
  storedBindingIngredient: 'PI-ING-001313',
  storedBindingIsCurrent: true,
  currentBindings: [{ ingredient: 'PI-ING-001313', baseRecipe: true }],
  ...overrides,
});

describe('GEL-P0-029 — published predicate', () => {
  it('never gates acceptance on the historical binding row still being current', () => {
    expect(PUBLISHED).not.toContain('authority_binding.id::text=');
    expect(migration).toContain('acceptance still gates on the historical binding id');
  });

  it('carries every conjunct in BOTH acceptance blocks', () => {
    // Per block, so reverting one branch cannot hide behind the other.
    expect(PUBLISHED_BLOCKS).toHaveLength(2);
    for (const [index, block] of PUBLISHED_BLOCKS.entries()) {
      for (const conjunct of REQUIRED_CONJUNCTS) {
        expect(block, `block ${index} is missing conjunct: ${conjunct}`).toContain(conjunct);
      }
      expect(block, `block ${index} still gates on the historical id`).not.toContain(
        'authority_binding.id::text=',
      );
    }
  });
});

describe('GEL-P0-029 A — a superseded provenance row does not revoke anything', () => {
  it('accepts when the same ingredient still has a valid current binding', () => {
    const stale = world({ storedBindingIsCurrent: false });
    // This is exactly Cacao Puro: stored 8b1147d3… is retired, PI-ING-001313
    // still has a current BASE_RECIPE binding.
    expect(baseAccepted(stale)).toBe(true);
  });
});

describe('GEL-P0-029 B — current policy wins over historical policy', () => {
  it('refuses when the current binding for the same ingredient withdrew the permission', () => {
    const withdrawn = world({
      storedBindingIsCurrent: false,
      currentBindings: [{ ingredient: 'PI-ING-001313', baseRecipe: false }],
    });
    expect(baseAccepted(withdrawn)).toBe(false);
  });
});

describe('GEL-P0-029 C — a foreign ingredient can never stand in', () => {
  it('refuses when only a different PI has a current eligible binding', () => {
    const foreign = world({
      reference: 'PI-ING-001313',
      activeIngredients: ['PI-ING-001313', 'PI-ING-000201'],
      storedBindingIsCurrent: false,
      currentBindings: [{ ingredient: 'PI-ING-000201', baseRecipe: true }],
    });
    expect(baseAccepted(foreign)).toBe(false);
  });

  it('refuses when the stored provenance belongs to a different ingredient', () => {
    const incoherent = world({ storedBindingIngredient: 'PI-ING-000201' });
    expect(baseAccepted(incoherent)).toBe(false);
  });
});

describe('GEL-P0-029 D — missing evidence fails closed', () => {
  it('refuses when the referenced ingredient has no current binding at all', () => {
    expect(baseAccepted(world({ currentBindings: [] }))).toBe(false);
  });

  it('refuses when the referenced ingredient does not exist or is inactive', () => {
    expect(baseAccepted(world({ activeIngredients: [] }))).toBe(false);
  });

  it('refuses when the product carries no reference at all', () => {
    expect(baseAccepted(world({ reference: null }))).toBe(false);
  });

  it('refuses when there is no stored provenance row', () => {
    expect(baseAccepted(world({ storedBindingIngredient: null }))).toBe(false);
  });
});

describe('GEL-P0-029 E — fresh lineage is unchanged', () => {
  it('accepts a product whose stored row is still current, exactly as before', () => {
    expect(baseAccepted(world())).toBe(true);
  });

  it('keeps the reference requirement itself', () => {
    expect(migration).toContain('v_behavior_reference is not null');
    expect(migration).toContain('reference requirement drifted');
  });
});

describe('GEL-P0-029 F — the Mapper itself is untouched', () => {
  it('only ever reads Mapper tables, never writes them', () => {
    const statements = migration.toLowerCase();
    for (const write of [
      'insert into public.mapper',
      'update public.mapper',
      'delete from public.mapper',
      'insert into mapper',
      'update mapper',
      'delete from mapper',
    ]) {
      expect(statements, `migration writes to the Mapper: ${write}`).not.toContain(write);
    }
  });

  it('never rewrites the mapper classifier', () => {
    expect(migration).not.toContain('classify_mapper_product_behavior_v2');
  });
});

describe('GEL-P0-029 G — no product facts are rewritten', () => {
  it('never writes product_versions, products or behaviour bindings', () => {
    const statements = migration.toLowerCase();
    for (const write of [
      'update public.product_versions',
      'update product_versions',
      'update public.products',
      'update public.product_behavior_bindings',
      'insert into public.product_behavior_bindings',
    ]) {
      expect(statements, `migration writes product state: ${write}`).not.toContain(write);
    }
  });

  it('leaves mapperBehaviorBindingId as provenance, read but never assigned', () => {
    // It may only ever be READ, inside the provenance comparison.
    expect(PUBLISHED).toContain(
      "provenance_binding.id::text=\n          v_public_data#>>'{productIntelligence,productBehaviorAuthority,mapperBehaviorBindingId}'",
    );
    expect(migration.toLowerCase()).not.toContain('set mapperbehaviorbindingid');
    expect(migration).not.toContain('jsonb_set');
  });
});
