/**
 * OWNER-LOCKED CONTRACTS — applied Mapper-lineage migration identity.
 *
 * SOL-014: staging already applied these operations under the versions below.
 * Their repository identity must match the applied ledger so a later migration
 * run cannot treat either operation as pending and execute it a second time.
 *
 * DO NOT EDIT THIS FILE TO MAKE AN IMPLEMENTATION PASS.
 * See `src/contracts/owner-locked/README.md`.
 */
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

import { SRC_ROOT } from './sourceContract';

const REPO_ROOT = resolve(SRC_ROOT, '..');
const MIGRATIONS_ROOT = join(REPO_ROOT, 'supabase', 'migrations');

const MAPPER_FILE = '20260906003955_mapper_lineage_current_binding.sql';
const RECLASSIFY_FILE = '20260906004154_reclassify_stale_mapper_lineage_bindings.sql';
const RETIRED_FILES = [
  '20260905150000_mapper_lineage_current_binding.sql',
  '20260906004500_reclassify_stale_mapper_lineage_bindings.sql',
] as const;

const APPLIED_RECLASSIFY_SHA256 =
  '0f294e71284329e5ab6eecb539529e8bab484a5bfc29d1821af2b4217888218d';
const APPLIED_MAPPER_EXECUTABLE_SHA256 =
  'a3ff979aea10a3b564e98299eefaa769c33cbac4b57e53ba4493c8b307e271eb';

const migrationFiles = readdirSync(MIGRATIONS_ROOT).filter((file) => file.endsWith('.sql'));
const readMigration = (file: string): string => readFileSync(join(MIGRATIONS_ROOT, file), 'utf8');
const sha256 = (value: string): string => createHash('sha256').update(value).digest('hex');
const withoutFinalNewline = (value: string): string => value.replace(/\n$/, '');
const executableSql = (value: string): string =>
  value
    .replace(/--[^\n]*/g, '')
    .replace(/\s+/g, '')
    .replace(/;;$/, ';');

describe('SOL-014 — repository migration identity matches the applied staging ledger', () => {
  it('uses the two exact versions already recorded by staging', () => {
    expect(migrationFiles).toContain(MAPPER_FILE);
    expect(migrationFiles).toContain(RECLASSIFY_FILE);
    for (const retired of RETIRED_FILES) {
      expect(existsSync(join(MIGRATIONS_ROOT, retired))).toBe(false);
    }
  });

  it('has exactly one canonical file for each operation', () => {
    expect(
      migrationFiles.filter((file) => file.endsWith('_mapper_lineage_current_binding.sql')),
    ).toEqual([MAPPER_FILE]);
    expect(
      migrationFiles.filter((file) =>
        file.endsWith('_reclassify_stale_mapper_lineage_bindings.sql'),
      ),
    ).toEqual([RECLASSIFY_FILE]);
  });

  it('does not reuse either applied version for another migration', () => {
    expect(migrationFiles.filter((file) => file.startsWith('20260906003955_'))).toEqual([
      MAPPER_FILE,
    ]);
    expect(migrationFiles.filter((file) => file.startsWith('20260906004154_'))).toEqual([
      RECLASSIFY_FILE,
    ]);
  });

  it('keeps the exact reclassification statement already stored in the ledger', () => {
    expect(sha256(withoutFinalNewline(readMigration(RECLASSIFY_FILE)))).toBe(
      APPLIED_RECLASSIFY_SHA256,
    );
  });

  it('keeps Mapper-lineage executable SQL semantically identical to the applied statement', () => {
    expect(sha256(executableSql(readMigration(MAPPER_FILE)))).toBe(
      APPLIED_MAPPER_EXECUTABLE_SHA256,
    );
  });

  it('contains no second copy of either semantic operation', () => {
    const mapperCopies = migrationFiles.filter((file) =>
      readMigration(file).includes("hashtextextended('mapper-lineage-current-binding-v1',0)"),
    );
    const reclassifyCopies = migrationFiles.filter((file) =>
      readMigration(file).includes("hashtextextended('reclassify-stale-mapper-lineage-v1',0)"),
    );

    expect(mapperCopies).toEqual([MAPPER_FILE]);
    expect(reclassifyCopies).toEqual([RECLASSIFY_FILE]);
  });

  it('retains the canonical queue path and never adds direct product or Mapper writes', () => {
    const reclassification = readMigration(RECLASSIFY_FILE).toLowerCase();
    expect(reclassification).toContain('enqueue_product_behavior_reclassification_v1');
    expect(reclassification).toContain('process_product_behavior_reclassification_queue_v1');

    for (const forbiddenWrite of [
      'update public.mapper',
      'insert into public.mapper',
      'delete from public.mapper',
      'update public.products',
      'update public.product_versions',
      'update public.product_behavior_bindings',
      'insert into public.product_behavior_bindings',
    ]) {
      expect(reclassification).not.toContain(forbiddenWrite);
    }
  });
});
