/**
 * OWNER-LOCKED CONTRACT — GEL-P0-037
 * PRO Crown at 0 g seeds 1 g for EVERY profile, at the STORE WIRING.
 *
 * Owner regression brief 2026-09-11. GEL-P0-002 pins the pure helper
 * (`crownOnPlannedGrams(0) -> 1`). That was not enough: 6e9a99bc stopped CALLING
 * it for Protein inside the shared store, every contract stayed green, and PRO
 * Protein lost `0 g + Crown -> 1 g` — Przelicz then refused with
 * "Minimalna ilość to 1 g". This contract pins the WIRING, per profile, through
 * the door every PRO control uses, so that gap cannot reopen.
 *
 * HOME is an additional layer over PRO. A HOME Crown rule may exist, but only
 * on HOME's own surface; it must never change what the PRO default does.
 *
 * DO NOT EDIT THIS FILE TO MAKE AN IMPLEMENTATION PASS.
 * See `src/contracts/owner-locked/README.md`.
 */
import { describe, expect, it } from 'vitest';
import { findDemoIngredient } from '@/data/demoIngredients';
import { productBehaviorTestSnapshots } from '@/features/product-intelligence/productBehaviorTestFixture';
import { buildRecipeInput } from '@/features/studio/buildRecipeInput';
import { useRecipeStore } from '@/stores/recipeStore';

import { readCode } from './sourceContract';

const FRUIT = {
  ...findDemoIngredient('raspberry')!,
  id: 'PI-ING-000405',
  canonical_ingredient_id: 'PI-ING-000405',
  name: 'WATERMELON · Fresh Fruit',
  category: 'fruit' as const,
};

const crownAtZero = (
  profile: 'gelato' | 'sorbet' | 'vegan' | 'protein',
  door: 'setMainIngredient' | 'setLockType',
) => {
  const store = useRecipeStore.getState();
  store.startNewRecipe(profile);
  const added = useRecipeStore.getState().addIngredient(FRUIT, 0);
  if (added.status !== 'added') throw new Error(added.status);
  const snapshots = productBehaviorTestSnapshots(buildRecipeInput(useRecipeStore.getState()));
  snapshots[added.lineId] = {
    ...snapshots[added.lineId]!,
    mainClassification: 'MAIN_ALLOWED',
    mainCapability: 'MAIN_CAPABLE_UNCALIBRATED',
  };
  useRecipeStore.getState().syncProductBehaviorSnapshots(snapshots);
  if (door === 'setMainIngredient') useRecipeStore.getState().setMainIngredient(added.lineId);
  else useRecipeStore.getState().setLockType(added.lineId, 'main');
  return useRecipeStore.getState().items.find((item) => item.id === added.lineId)!;
};

describe('GEL-P0-037 — PRO Crown at 0 g seeds 1 g for every profile', () => {
  for (const profile of ['gelato', 'sorbet', 'vegan', 'protein'] as const) {
    for (const door of ['setMainIngredient', 'setLockType'] as const) {
      it(`${profile} · ${door}`, () => {
        expect(crownAtZero(profile, door)).toMatchObject({ planned_grams: 1, lock_type: 'main' });
      });
    }
  }
});

describe('GEL-P0-037 — a HOME Crown rule stays on the HOME surface', () => {
  const recipeStore = readCode('stores', 'recipeStore.ts');
  const ingredientBuilder = readCode('features', 'ingredient-builder', 'IngredientBuilder.tsx');
  const ingredientRow = readCode('features', 'ingredient-builder', 'IngredientRow.tsx');

  it('the seed decision is unconditional on the PRO surface', () => {
    expect(recipeStore).toContain("surface === 'pro' ||");
    expect(recipeStore).toContain("setMainIngredient: (lineId, surface = 'pro') =>");
    expect(recipeStore).toContain("setLockType: (lineId, lockType, surface = 'pro') =>");
  });

  it('no PRO control names the HOME surface', () => {
    for (const source of [ingredientBuilder, ingredientRow]) {
      expect(source).not.toMatch(/setMainIngredient\([^)]*'home'/);
      expect(source).not.toMatch(/setLockType\([^)]*'home'/);
    }
  });
});
