/**
 * OWNER-LOCKED CONTRACTS — ProductBehavior / Mapper authority.
 *
 * GEL-P0-011 BASE_RECIPE eligibility is Mapper-derived, with no second registry
 * GEL-P0-012 A fresh canonical recipe carries no historical/unresolved product
 * GEL-P0-016 Topping isolation
 *
 * DO NOT EDIT THIS FILE TO MAKE AN IMPLEMENTATION PASS.
 * See `src/contracts/owner-locked/README.md`.
 */
import { existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import {
  BASE_ONLY_CATEGORIES,
  BASE_ONLY_SUBCATEGORIES,
  TOPPING_ONLY_CATEGORIES,
  canonicalModuleEligibility,
  canonicalProductRole,
} from '@/features/product-intelligence/canonicalModuleEligibility';
import { productBehaviorRequiredLineIds } from '@/features/product-intelligence/productBehaviorAccess';

import { SRC_ROOT, readCode } from './sourceContract';

const productIntelligenceDir = join(SRC_ROOT, 'features', 'product-intelligence');

describe('GEL-P0-011 — BASE_RECIPE eligibility is Mapper-derived only', () => {
  // Accepted 2026-08-29 (fa4b03cc). The owner rejected any second per-product
  // BASE_RECIPE registry: a new canonical product must never need a code change
  // to become usable. On 2026-08-29 a per-id allow-list keyed on PI-ING-000270 /
  // PI-ING-000514 was reintroduced (d7665157) and removed nine hours later.
  it('answers module eligibility from Mapper category and subcategory', () => {
    expect(canonicalProductRole('sweetener', null)).toBe('BASE_ONLY');
    expect(canonicalProductRole('confectionery_inclusion', null)).toBe('TOPPING_ONLY');
    expect(canonicalProductRole('fruit', null)).toBe('BASE_AND_TOPPING');
    // A declared `water` subcategory is base-only regardless of its category.
    expect(canonicalProductRole('liquid', 'water')).toBe('BASE_ONLY');
  });

  it('gates the answer on the Mapper approval flag, never on a product id', () => {
    const facts = {
      isActive: true,
      approvedForBase: true,
      ingredientCategory: 'fruit',
      ingredientSubcategory: null,
    };
    expect(canonicalModuleEligibility(facts).BASE_RECIPE).toBe(true);

    // Fail closed: not approved, or not active, is eligible for no module.
    expect(canonicalModuleEligibility({ ...facts, approvedForBase: false }).BASE_RECIPE).toBe(false);
    expect(canonicalModuleEligibility({ ...facts, isActive: false }).BASE_RECIPE).toBe(false);
    expect(canonicalModuleEligibility({ ...facts, isActive: false }).TOPPING).toBe(false);
  });

  it('carries no per-product identifier anywhere in the eligibility authority', () => {
    // The single most important assertion in this file: eligibility must not
    // mention a PI-ING id at all.
    const authority = readCode('features', 'product-intelligence', 'canonicalModuleEligibility.ts');
    expect(authority).not.toMatch(/PI-ING-\d+/);
  });

  it('ships no second per-product BASE_RECIPE registry module', () => {
    // Fails if a hand-keyed allow-list module returns under any name.
    const banned = join(productIntelligenceDir, 'canonicalRecipeProductBehaviorAuthority.ts');
    expect(
      existsSync(banned),
      'a per-id ProductBehavior allow-list must not exist — fix mapper_basement instead',
    ).toBe(false);

    const offenders = readdirSync(productIntelligenceDir)
      .filter((name) => name.endsWith('.ts') && !name.includes('.test.'))
      .filter((name) => {
        const source = readCode('features', 'product-intelligence', name);
        // An allow-list is a module that maps several product ids to authority.
        return (source.match(/'PI-ING-\d+':/g) ?? []).length >= 2;
      });
    expect(offenders, 'these modules hard-code per-product authority').toEqual([]);
  });
});

describe('GEL-P0-012 — a fresh canonical recipe carries no unresolved product', () => {
  // This is also what makes the Crown auto-seed necessary: a 0 g line is NOT a
  // required line, so no ProductBehavior revalidation pass ever visits it.
  // Removing this exclusion silently strands every zero-gram line.
  const line = (id: string, planned_grams: number) => ({
    id,
    planned_grams,
    ingredient: { id: 'ing', canonical_ingredient_id: 'PI-ING-000001', identity_provenance: 'mapper' },
  });

  it('requires resolver authority for every positive canonical line', () => {
    expect(productBehaviorRequiredLineIds({ items: [line('a', 120)] })).toEqual(['a']);
  });

  it('excludes a zero-gram line from the required set', () => {
    expect(productBehaviorRequiredLineIds({ items: [line('a', 0)] })).toEqual([]);
  });

  it('does not require authority for a synthetic line with no product lineage', () => {
    expect(
      productBehaviorRequiredLineIds({
        items: [{ id: 'synthetic', planned_grams: 100, ingredient: { id: 'local-only' } }],
      }),
    ).toEqual([]);
  });
});

describe('GEL-P0-016 — topping isolation', () => {
  it('keeps three distinct module roles', () => {
    expect(canonicalProductRole('bakery_inclusion', null)).toBe('TOPPING_ONLY');
    expect(canonicalProductRole('stabilizer', null)).toBe('BASE_ONLY');
    expect(canonicalProductRole('dairy', null)).toBe('BASE_AND_TOPPING');
  });

  it('never lets a topping-only category enter the base', () => {
    for (const category of TOPPING_ONLY_CATEGORIES) {
      const eligibility = canonicalModuleEligibility({
        isActive: true,
        approvedForBase: true,
        ingredientCategory: category,
        ingredientSubcategory: null,
      });
      expect(eligibility.BASE_RECIPE, `${category} must not be usable in base`).toBe(false);
      expect(eligibility.TOPPING, `${category} must stay a topping`).toBe(true);
    }
  });

  it('never lets a base-only category be served as a topping', () => {
    for (const category of BASE_ONLY_CATEGORIES) {
      const eligibility = canonicalModuleEligibility({
        isActive: true,
        approvedForBase: true,
        ingredientCategory: category,
        ingredientSubcategory: null,
      });
      expect(eligibility.TOPPING, `${category} must not be a topping`).toBe(false);
      expect(eligibility.BASE_RECIPE, `${category} must stay a base ingredient`).toBe(true);
    }
    for (const subcategory of BASE_ONLY_SUBCATEGORIES) {
      expect(canonicalProductRole('liquid', subcategory)).toBe('BASE_ONLY');
    }
  });

  it('keeps module eligibility independent of process evidence', () => {
    // Module eligibility, profile compatibility and process authority are three
    // separate questions. BASE_RECIPE must never consult process evidence.
    const authority = readCode('features', 'product-intelligence', 'canonicalModuleEligibility.ts');
    expect(authority).not.toContain('process');
    expect(authority).not.toContain('engineUsable');
  });
});
