/**
 * OWNER-LOCKED CONTRACT — ordinary Recalculate vs explicit Direction.
 *
 * GEL-P0-020 Direction progress is not a universal publication veto
 *
 * DO NOT EDIT THIS FILE TO MAKE AN IMPLEMENTATION PASS.
 * See `src/contracts/owner-locked/README.md`.
 *
 * This contract exists because `7edd90ea` used ONE strict-progress verdict for
 * TWO different questions. Strict progress compares BAND distances, which
 * cannot fall below zero, so from a draft already inside its bands the verdict
 * collapses to `reached` and every other candidate — including a valid,
 * on-batch, violation-free technical repair — became `no_proposal`. Since
 * `direction_targets_active` is unconditionally true for every recipe (owner
 * P1-A), that veto was armed on every recalculation in the product.
 *
 * Both behavioural and source-invariant assertions are used: the arithmetic is
 * checkable as a pure export, and the WIRING (which verdict each gate reads) is
 * exactly the kind of thing a previous regression silently deleted.
 */
import { describe, expect, it } from 'vitest';

import type { RecipeInput } from '@/engine';
import { assessDirectionCandidateProgress } from '@/features/constraint-studio/applyPipeline';

import { readCode } from './sourceContract';

const applyPipeline = readCode('features', 'constraint-studio', 'applyPipeline.ts');

/**
 * Minimal Gelato input with an ACTIVE neutral Direction — the state every fresh
 * recipe in the product is in.
 */
const draft = (grams: readonly number[]): RecipeInput =>
  ({
    mode: 'classic',
    category: 'milk_gelato',
    target_temperature_c: -12,
    target_batch_grams: 1_000,
    machine_capacity_grams: null,
    items: grams.map((planned_grams, index) => ({
      id: `line-${index}`,
      ingredient: {
        id: ['milk_3_5', 'cream_30', 'sucrose', 'tara_gum'][index] ?? `ing-${index}`,
        name: `line ${index}`,
        category: 'dairy',
        composition: {
          water_percent: 88.7,
          solids_percent: 11.3,
          fat_percent: 3.5,
          sugars_percent: 4.7,
          protein_percent: 3,
        },
      },
      planned_grams,
      actual_grams: null,
      lock_type: 'unlocked',
    })),
    goals: {
      formulation_strategy: 'optimal',
      direction_targets_active: true,
      direction_targets: { sweetness: 0, softness: 0, creaminess: 0, flavor: 0 },
    },
  }) as unknown as RecipeInput;

describe('GEL-P0-020 — Direction progress is not a universal publication veto', () => {
  it('publishes both verdicts, so one gate can never silently serve the other purpose', () => {
    const current = draft([600, 200, 150, 50]);
    const progress = assessDirectionCandidateProgress(current, draft([580, 210, 160, 50]));
    expect(progress).toHaveProperty('accepted');
    expect(progress).toHaveProperty('publishable');
  });

  it('ORDINARY RECALCULATE — a materially different candidate is publishable', () => {
    const current = draft([600, 200, 150, 50]);
    const changed = draft([580, 210, 160, 50]);
    const progress = assessDirectionCandidateProgress(current, changed);
    expect(progress.active).toBe(true);
    expect(progress.materiallyDifferent).toBe(true);
    expect(progress.publishable).toBe(true);
  });

  it('FAKE NEAREST STAYS CLOSED — an unchanged candidate is never publishable unless reached', () => {
    const current = draft([600, 200, 150, 50]);
    const progress = assessDirectionCandidateProgress(current, structuredClone(current));
    expect(progress.materiallyDifferent).toBe(false);
    expect(progress.publishable).toBe(progress.reached);
    expect(progress.accepted).toBe(progress.reached);
  });

  it('EXPLICIT DIRECTION — strict progress keeps its accepted definition', () => {
    // `accepted` must remain `reached || (materiallyDifferent && strictlyCloser)`.
    // Relaxing it would change Starter Pack Rescue and the owner Direction
    // fallback ladder, which are separately locked.
    expect(applyPipeline).toContain(
      'accepted: reached || (materiallyDifferent && strictlyCloser),',
    );
    expect(applyPipeline).toContain('publishable: reached || materiallyDifferent,');
  });

  it('the universal Preview exit reads the ORDINARY verdict', () => {
    // `enforceTargetBatchInvariant` is the single exit every executable ok:true
    // Preview leaves through. It must never re-acquire the strict verdict.
    const exit = applyPipeline.slice(applyPipeline.indexOf('function enforceTargetBatchInvariant'));
    const body = exit.slice(0, exit.indexOf('\nexport function buildOptimizePreview'));
    expect(body).toContain('!progress.publishable');
    expect(body).not.toContain('!progress.accepted');
  });

  it('the Starter Pack Rescue gate keeps the STRICT verdict', () => {
    expect(applyPipeline).toContain(
      "if (progress.active && !progress.accepted) return { ok: false, code: 'no_proposal' };",
    );
  });

  it('the Apply door selects its verdict by the route the Preview came from', () => {
    // Explicit Direction routes are identified by the metadata their own
    // producers attach; everything else is ordinary Recalculate.
    expect(applyPipeline).toContain('preview.directionFallback !== undefined');
    expect(applyPipeline).toContain('preview.starterPackRescue !== undefined');
    expect(applyPipeline).toContain('? directionProgress.accepted');
    expect(applyPipeline).toContain(': directionProgress.publishable');
  });

  it('Direction truth is still published for an unreached target', () => {
    // The shared presentation contract every Preview producer converges on.
    expect(applyPipeline).toContain('preview.directionTargetUnreached = true;');
  });
});
