/**
 * OWNER-LOCKED CONTRACTS — soft target vs hard capacity.
 *
 * GEL-P0-031 A recommended batch is guidance. Only a proven equipment maximum,
 *            or a capacity the customer explicitly declared, may refuse a
 *            larger rescued batch.
 *
 * Accepted 2026-09-05. Three different facts had been collapsed into one:
 *   A. `target_batch_grams`      — the batch the customer wants right now
 *   B. `recommendedBatchGrams`   — Gellatti's operating guidance for a container
 *   C. a proven hard equipment maximum
 * Only C may populate a hard capacity gate, and C is never inferred from A or B.
 *
 * The Ninja CREAMi Deluxe's 670 g is B: `vesselCapacityMl 706 × 0.95`, recorded
 * in the catalog as "a soft starting proposal, never a hard limit", with
 * `maxFillDefinedByManufacturer: false` and two vessels. Treating it as C made
 * every enlargement Rescue impossible — the owner's Case 1 refused a 721.9 g
 * solution that preserved everything already in the vessel.
 *
 * DO NOT EDIT THIS FILE TO MAKE AN IMPLEMENTATION PASS.
 * See `src/contracts/owner-locked/README.md`.
 */
import { describe, expect, it } from 'vitest';

import { MACHINE_CATALOG } from '@/features/machine-catalog/machineCatalogData';
import {
  deriveMachineSetup,
  planContainerSplit,
} from '@/features/machine-catalog/machineDerivation';
import {
  assessProductionRescue,
  productionContinuationPath,
} from '@/features/production-workspace/productionRescue';
import {
  confirmOwnerRescueLines,
  makeOwnerRescueSession,
} from '@/features/production-workspace/productionOwnerRescue.fixture';
import type { ProductionSession } from '@/features/production-workspace/productionSession';

/** Owner Case 1: three confirmed rows make the 670 g target unreachable. */
const CASE_ONE = [
  ['milk', 201],
  ['cream', 125],
  ['skimmed_milk', 55],
] as const;

const caseOneSession = (
  capacitySource: 'machine' | 'manual' | null,
  capacityGrams = 670,
): ProductionSession => {
  const source = makeOwnerRescueSession();
  return confirmOwnerRescueLines(
    {
      ...source,
      plannedInput: {
        ...source.plannedInput,
        machine_capacity_grams: capacityGrams,
        ...(capacitySource ? { machine_capacity_source: capacitySource } : {}),
      },
    },
    CASE_ONE,
  );
};

describe('GEL-P0-031 A — a soft recommended batch never blocks enlargement', () => {
  it('offers the smallest larger legal batch when no capacity authority exists', () => {
    const assessment = assessProductionRescue(caseOneSession(null));
    const enlargement = assessment.options.find((option) => option.id === 'enlarge_batch');

    // 670 is present as a number, but carries no provenance, so it is not a limit.
    expect(assessment.diagnostics.machineCapacityG).toBeNull();
    expect(assessment.diagnostics.machineCapacitySource).toBeNull();
    expect(assessment.hardSafety.capacityExceeded).toBe(false);

    expect(enlargement).toBeDefined();
    expect(enlargement!.finalMassG).toBeGreaterThan(assessment.diagnostics.originalTargetG!);
    expect(productionContinuationPath(assessment)).toBe('authorized_correction');
  });

  it('preserves every physically confirmed quantity in that solution', () => {
    const assessment = assessProductionRescue(caseOneSession(null));
    const enlargement = assessment.options.find((option) => option.id === 'enlarge_batch')!;
    const byLine = new Map(
      enlargement.candidateInput.items.map((item) => [item.id, item.planned_grams]),
    );
    // Confirmed rows may be topped up, never reduced below what is in the vessel.
    for (const [lineId, confirmedGrams] of CASE_ONE) {
      expect(byLine.get(lineId)).toBeGreaterThanOrEqual(confirmedGrams);
    }
  });
});

describe('GEL-P0-031 B — an explicitly declared capacity is a real limit', () => {
  it('refuses enlargement above a capacity the customer declared', () => {
    const assessment = assessProductionRescue(caseOneSession('manual'));
    expect(assessment.diagnostics.machineCapacityG).toBe(670);
    expect(assessment.diagnostics.machineCapacitySource).toBe('manual');
    expect(assessment.hardSafety.capacityExceeded).toBe(true);
    expect(assessment.options.find((option) => option.id === 'enlarge_batch')).toBeUndefined();
  });
});

describe('GEL-P0-031 C — a sourced machine maximum is a real limit', () => {
  it('refuses enlargement above a machine-sourced capacity', () => {
    const assessment = assessProductionRescue(caseOneSession('machine'));
    expect(assessment.diagnostics.machineCapacitySource).toBe('machine');
    expect(assessment.hardSafety.capacityExceeded).toBe(true);
    expect(assessment.options.find((option) => option.id === 'enlarge_batch')).toBeUndefined();
  });
});

describe('GEL-P0-031 D — no known hard maximum is not a fake ceiling', () => {
  it('keeps the recommended batch and the hard maximum separate for every machine', () => {
    for (const profile of MACHINE_CATALOG.filter((candidate) => candidate.active)) {
      const setup = deriveMachineSetup(profile);
      if (setup.hardMaximumBatchGrams === null) continue;
      // A stated hard maximum may never be the soft recommendation restated.
      expect(setup.hardMaximumBatchGrams).not.toBe(setup.recommendedBatchGrams);
    }
  });

  it('never derives a gram ceiling from a vessel volume', () => {
    for (const profile of MACHINE_CATALOG.filter((candidate) => candidate.active)) {
      const vesselMl = profile.capacity.vesselCapacityMl;
      const hard = deriveMachineSetup(profile).hardMaximumBatchGrams;
      if (hard === null || vesselMl === null) continue;
      // No `1 ml = 1 g`, and no `ml × 0.95`, may become a hard gram limit.
      expect(hard).not.toBe(vesselMl);
      expect(hard).not.toBe(Math.round(vesselMl * 0.95));
    }
  });
});

describe('GEL-P0-031 E — a larger batch is guidance, not a refusal', () => {
  it('splits a batch above the recommended container fill instead of rejecting it', () => {
    expect(planContainerSplit(900, 450)).toMatchObject({
      containers: 2,
      gramsPerContainer: 450,
      withinSingleContainer: false,
    });
    expect(planContainerSplit(1000, 450)?.containers).toBe(3);
    // The split never overfills a single container.
    const plan = planContainerSplit(1000, 450)!;
    expect(plan.gramsPerContainer).toBeLessThanOrEqual(450);
    expect(plan.totalGrams).toBe(1000);
  });
});
