/**
 * OWNER-LOCKED CONTRACTS — save/reopen + mobile functional architecture.
 *
 * GEL-P0-017 Save / reopen
 * GEL-P0-019 Mobile functional architecture
 *
 * DO NOT EDIT THIS FILE TO MAKE AN IMPLEMENTATION PASS.
 * See `src/contracts/owner-locked/README.md`.
 */
import { describe, expect, it } from 'vitest';

import { readCode, readSource } from './sourceContract';

const recipeStore = readCode('stores', 'recipeStore.ts');
const mobileLine = readSource('features', 'ingredient-builder', 'IngredientLineControls.tsx');

const partialize = recipeStore.match(/export function recipePersistPartialize[\s\S]*?\n}/)?.[0];

describe('GEL-P0-017 — save / reopen', () => {
  it('persists through one explicit allow-list', () => {
    // An allow-list, never a blocklist: a new store field is non-persistent by
    // default, so no transient value can leak into a saved recipe by accident.
    expect(partialize, 'recipePersistPartialize must exist').toBeTruthy();
    expect(partialize).toContain('return {');
  });

  it('persists the recipe identity needed to reopen the right version', () => {
    for (const field of [
      'target_batch_grams',
      'target_temperature_c',
      'formulation_strategy',
      'category',
    ]) {
      expect(partialize, `${field} must survive reopen`).toContain(field);
    }
  });

  it('never persists transient editor provenance', () => {
    // The crown auto-seed flag is store-only. If it ever persists it can reach
    // a saved recipe_input and a production payload.
    expect(partialize).not.toContain('crownAutoSeededLineIds');
  });

  it('resets transient editor provenance on every draft load path', () => {
    // Both load paths must clear it, or a reopened recipe inherits the previous
    // draft's seed provenance and Crown OFF silently zeroes a real line.
    const resets = recipeStore.match(/crownAutoSeededLineIds: \[\]/g) ?? [];
    expect(resets.length).toBeGreaterThanOrEqual(2);
  });

  it("reads Direction targets from the recipe's own goals, not the ambient profile", () => {
    // Reading the ambient profile first is how a reopened recipe inherited the
    // previous recipe's Direction.
    expect(recipeStore).toContain('input.goals?.direction_targets');
  });
});

describe('GEL-P0-019 — mobile functional architecture', () => {
  // One functional model, two responsive presentations. The mobile layer is a
  // presentation of the same actions — never a second implementation.
  const valueImports = mobileLine
    .split('\n')
    .filter((line) => line.startsWith('import ') && !line.startsWith('import type'))
    .join('\n');

  it('never reaches for a store or the Engine from the mobile presentation', () => {
    for (const forbidden of [
      '@/stores/',
      'constraintStudioStore',
      'recipeStore',
      'useRecipeStore',
      'recipeProfileStore',
      'calculateRecipe',
      'applyPipeline',
      'proposeCorrections',
    ]) {
      expect(valueImports, forbidden).not.toContain(forbidden);
    }
  });

  it('defines no arithmetic of its own', () => {
    expect(mobileLine).not.toMatch(/function\s+\w*(Rebalance|Recalc|Calculate|Solve)/i);
    expect(mobileLine).not.toContain('total_batch_g');
    expect(mobileLine).not.toContain('effective_grams');
  });

  it('offers the Main role control in the mobile presentation too', () => {
    // Parity is the point: a control that exists on desktop and not on mobile
    // is a functional difference, not a responsive one.
    expect(mobileLine).toContain('MainRoleTrigger');
  });
});
