/**
 * OWNER-LOCKED CONTRACTS — a fresh Sorbet without its Main is INCOMPLETE.
 *
 * GEL-P0-011 A user-supplied template role that is unfilled makes the draft incomplete
 * GEL-P0-012 The machine/user target batch is never collapsed to the scaffold mass
 * GEL-P0-013 No default flavour is ever invented for the customer
 * GEL-P0-014 An incomplete scaffold never surfaces a batch/solver failure
 * GEL-P0-015 Gelato / Vegan / Protein fresh starters stay complete
 *
 * DO NOT EDIT THIS FILE TO MAKE AN IMPLEMENTATION PASS.
 * See `src/contracts/owner-locked/README.md`.
 */
import { beforeEach, describe, expect, it } from 'vitest';

import { calculateRecipe } from '@/engine';
import { unfilledUserSuppliedRoles } from '@/features/formulation/formulate';
import { buildRecipeInput } from '@/features/studio/buildRecipeInput';
import { useRecipeStore } from '@/stores/recipeStore';
import { useRecipeProfileStore } from '@/features/pro-workbench/recipeProfileStore';
import { useConstraintStudioStore } from '@/features/constraint-studio/constraintStudioStore';
import { MAGIMIX_GELATO_EXPERT, deriveMachineSetup } from '@/features/machine-catalog';
import { machineDisplayName } from '@/features/machine-onboarding';
import { sorbetMultiMainBase } from '@/features/recipe-constraints/__fixtures__/sorbetAuthorityFixture';

const freshSorbet = () => {
  useRecipeProfileStore.getState().resetForTests();
  useConstraintStudioStore.getState().resetDraftSession();
  useRecipeStore.getState().startNewRecipe('sorbet');
};

const baseSum = () =>
  useRecipeStore.getState().items.reduce((sum, item) => sum + item.planned_grams, 0);

describe('GEL-P0-011 — an unfilled user-supplied role makes the draft incomplete', () => {
  beforeEach(freshSorbet);

  it('reports the fruit role as unfilled on every fresh Sorbet serving mode', () => {
    for (const temp of [-11, -12, -13]) {
      freshSorbet();
      useRecipeStore.getState().setTargetTemperature(temp);
      const unfilled = unfilledUserSuppliedRoles(buildRecipeInput(useRecipeStore.getState()));
      expect(
        unfilled.map((role) => role.role),
        `sorbet @${temp}`,
      ).toEqual(['fruit']);
      expect(unfilled[0]!.labelPl).toBe('Owoc');
      expect(unfilled[0]!.templateGrams).toBe(600);
    }
  });

  it('reports nothing once a real Sorbet Main is present', () => {
    // The owner-approved strawberry + lime Multi-Main over the same scaffold.
    expect(unfilledUserSuppliedRoles(sorbetMultiMainBase(-13, [2, 1]))).toEqual([]);
  });
});

describe('GEL-P0-012 — the machine/user target is never collapsed to the scaffold', () => {
  beforeEach(freshSorbet);

  it('keeps the Professional target at 1000 g while the scaffold is short', () => {
    const state = useRecipeStore.getState();
    expect(state.target_batch_grams).toBe(1000);
    expect(state.batch_source).toBe('PROFESSIONAL_DEFAULT');
    // The scaffold is deliberately lighter — that is the unchosen fruit.
    expect(baseSum()).toBeLessThan(state.target_batch_grams);
    expect(unfilledUserSuppliedRoles(buildRecipeInput(state))).toHaveLength(1);
  });

  it('keeps a Home machine target (Magimix Sorbet) at its canonical batch', () => {
    const setup = deriveMachineSetup(MAGIMIX_GELATO_EXPERT, 'sorbet');
    expect(setup.recommendedBatchGrams).toBe(1240);
    useRecipeStore.getState().setMachineSelection({
      kind: 'home',
      servingModeId: setup.resolvedVisibleMode!,
      machineId: MAGIMIX_GELATO_EXPERT.id,
      label: machineDisplayName(MAGIMIX_GELATO_EXPERT),
      temperatureC: -11,
      batchGrams: setup.recommendedBatchGrams,
      capacityGrams: setup.recommendedBatchGrams,
      batchSource: 'MACHINE_DEFAULT',
    });
    const state = useRecipeStore.getState();
    expect(state.target_batch_grams).toBe(1240);
    expect(state.batch_source).toBe('MACHINE_DEFAULT');
    expect(unfilledUserSuppliedRoles(buildRecipeInput(state))).toHaveLength(1);
  });
});

describe('GEL-P0-013 — no default flavour is ever invented', () => {
  beforeEach(freshSorbet);

  it('ships a fresh Sorbet with no fruit line at all', () => {
    const items = useRecipeStore.getState().items;
    expect(items.some((item) => item.ingredient.category === 'fruit')).toBe(false);
    // …and nothing claims a Main role on the customer's behalf.
    expect(items.some((item) => item.lock_type === 'main')).toBe(false);
  });
});

describe('GEL-P0-014 — an incomplete scaffold never reads as a batch/solver failure', () => {
  beforeEach(freshSorbet);

  it('stops on the missing role instead of running the optimizer', () => {
    useConstraintStudioStore.getState().createOptimizePreview();
    const studio = useConstraintStudioStore.getState();
    expect(studio.preview).toBeNull();
    expect(studio.previewIssue?.code).toBe('missing_required_role');
    if (studio.previewIssue?.code === 'missing_required_role') {
      expect(studio.previewIssue.role).toBe('fruit');
      expect(studio.previewIssue.messagePl).toContain('Owoc');
    }
    // The customer must never be told the batch or the solver failed.
    expect(JSON.stringify(studio.previewIssue)).not.toContain('batch_residual_unresolved');
    expect(JSON.stringify(studio.recalculationTerminal)).not.toContain('batch_residual_unresolved');
    expect(studio.recalculationTerminal?.state).not.toBe('ERROR');
  });

  it('reaches a coherent Professional batch once a Main is chosen', () => {
    const withMain = sorbetMultiMainBase(-13, [2, 1]);
    expect(unfilledUserSuppliedRoles(withMain)).toEqual([]);
    expect(withMain.items.reduce((sum, item) => sum + item.planned_grams, 0)).toBe(
      withMain.target_batch_grams,
    );
    expect(calculateRecipe(withMain).total_batch_g).toBeCloseTo(1000, 6);
  });
});

describe('GEL-P0-015 — the other fresh starters stay complete', () => {
  it('leaves Gelato, Vegan and Protein with no unfilled user-supplied role', () => {
    for (const product of ['gelato', 'vegan', 'protein'] as const) {
      useRecipeProfileStore.getState().resetForTests();
      useRecipeStore.getState().startNewRecipe(product);
      const state = useRecipeStore.getState();
      expect(unfilledUserSuppliedRoles(buildRecipeInput(state)), product).toEqual([]);
      // …and each still opens exactly on its target batch.
      expect(baseSum(), product).toBeCloseTo(state.target_batch_grams, 6);
    }
  });
});
