/**
 * GELLATTI AFFILIATE — the public commission calculator.
 *
 * Pure and deterministic: counts in, integer cents out. Every rate it uses
 * comes from `publicRateAuthority.ts`, which reads the ledger's own rate table
 * — there is no second rate source in the UI.
 *
 * The model (owner, §4):
 *
 *   annual_estimate =
 *       home_monthly_count × home_monthly_rate × 12
 *     + pro_monthly_count  × pro_monthly_rate  × 12
 *     + home_annual_count  × home_annual_rate
 *     + pro_annual_count   × pro_annual_rate
 *
 *   average_month_equivalent = annual_estimate / 12
 *
 * A monthly plan renews twelve times a year and an annual plan once, so the
 * ×12 belongs to the monthly counts only. `monthlyFromMonthlyCents` is the
 * per-month slice of the monthly component — NOT the annual total divided by
 * twelve — because those are different questions and the page shows both.
 *
 * ELITE HAS NO CALCULATOR NUMBER. `AffiliateCalculatorMode` is
 * `PublicAffiliateTier | 'elite'`, and `calculateAffiliateCommission` accepts
 * only a `PublicAffiliateTier`. The Elite mode is a UI state that routes to a
 * conversation; it can never reach this function, because passing 'elite' is a
 * type error.
 */

import { publicRate, type PublicAffiliateTier, CUSTOM_TERMS_TIER } from './publicRateAuthority';

/** Renewals of a monthly plan in one year. */
export const MONTHS_PER_YEAR = 12 as const;

/** The four inputs the page collects: active assigned customers per plan. */
export interface AffiliateCustomerCounts {
  readonly homeMonthly: number;
  readonly homeAnnual: number;
  readonly proMonthly: number;
  readonly proAnnual: number;
}

/**
 * What a form actually holds. A number input yields a STRING and can be empty
 * mid-typing, so the calculator's input type admits `unknown` per field and
 * normalises it — rather than forcing every caller to pre-parse and get the
 * empty-string case wrong.
 */
export type RawAffiliateCounts = Partial<Record<keyof AffiliateCustomerCounts, unknown>>;

export const EMPTY_COUNTS: AffiliateCustomerCounts = {
  homeMonthly: 0,
  homeAnnual: 0,
  proMonthly: 0,
  proAnnual: 0,
};

/** What the calculator shows. All money is integer cents. */
export interface AffiliateCommissionEstimate {
  readonly tier: PublicAffiliateTier;
  /** A — commission earned in ONE month from the monthly plans. */
  readonly monthlyFromMonthlyCents: number;
  /** B — commission generated by annual renewals across ONE year. */
  readonly fromAnnualRenewalsCents: number;
  /** C — estimated total commission per year. */
  readonly totalPerYearCents: number;
  /** D — average monthly equivalent (C / 12, rounded to whole cents). */
  readonly averagePerMonthCents: number;
  /**
   * E — commission from Starter Pack sales. A one-off product, so it enters
   * the YEAR once and is never multiplied by twelve.
   *
   * Its rate is passed IN rather than read from `publicRateAuthority`, and
   * that is deliberate: no Starter Pack commission has ever been frozen in
   * `commission_rules`, so this module must not be able to imply one exists.
   * The caller owns the pending proposal and says so on screen.
   */
  readonly fromStarterPacksCents: number;
}

/** Optional Starter Pack input. Absent means it contributes nothing. */
export interface StarterPackInput {
  readonly packs?: unknown;
  /** OWNER-PENDING proposal, supplied by the caller. */
  readonly rateCents?: number;
}

/**
 * The UI's mode selector. Elite is present as a state with no rate; every
 * rate-bearing path narrows to `PublicAffiliateTier` first.
 */
export type AffiliateCalculatorMode = PublicAffiliateTier | typeof CUSTOM_TERMS_TIER;

/** True when the mode carries no public rate and must route to a conversation. */
export const isCustomTermsMode = (
  mode: AffiliateCalculatorMode,
): mode is typeof CUSTOM_TERMS_TIER => mode === CUSTOM_TERMS_TIER;

/**
 * Coerce one input to a usable count. The page's number inputs can produce
 * `''`, `NaN`, `-3`, `2.7` and pasted values far beyond any real audience, so
 * every one of those is normalised here rather than in JSX:
 * NaN → 0, negative → 0, fractional → floor, above the cap (or +Infinity) → the cap.
 *
 * The cap keeps the arithmetic inside safe-integer cents no matter what is
 * pasted in; it is a display guard, not a business rule.
 */
export const MAX_CUSTOMERS_PER_PLAN = 1_000_000 as const;

export function normalizeCount(value: unknown): number {
  const numeric = typeof value === 'number' ? value : Number(value);
  // NaN (empty string, letters) and anything at or below zero are simply "none".
  if (Number.isNaN(numeric) || numeric <= 0) return 0;
  // +Infinity reaches here from a pasted `1e999`. It clamps to the cap like any
  // other absurd figure — a cliff where 1e30 caps but 1e999 silently became 0
  // would be the surprising behaviour, not the safe one.
  if (numeric >= MAX_CUSTOMERS_PER_PLAN) return MAX_CUSTOMERS_PER_PLAN;
  return Math.floor(numeric);
}

export function normalizeCounts(counts: RawAffiliateCounts): AffiliateCustomerCounts {
  return {
    homeMonthly: normalizeCount(counts.homeMonthly),
    homeAnnual: normalizeCount(counts.homeAnnual),
    proMonthly: normalizeCount(counts.proMonthly),
    proAnnual: normalizeCount(counts.proAnnual),
  };
}

/**
 * Estimate commission for one PUBLIC tier. Inputs are normalised first, so a
 * caller can hand this raw form state.
 */
export function calculateAffiliateCommission(
  tier: PublicAffiliateTier,
  rawCounts: RawAffiliateCounts,
  starterPack: StarterPackInput = {},
): AffiliateCommissionEstimate {
  const counts = normalizeCounts(rawCounts);

  const homeMonthlyRate = publicRate(tier, 'home', 'monthly').amountCents;
  const proMonthlyRate = publicRate(tier, 'pro', 'monthly').amountCents;
  const homeAnnualRate = publicRate(tier, 'home', 'annual').amountCents;
  const proAnnualRate = publicRate(tier, 'pro', 'annual').amountCents;

  const monthlyFromMonthlyCents =
    counts.homeMonthly * homeMonthlyRate + counts.proMonthly * proMonthlyRate;

  const fromAnnualRenewalsCents =
    counts.homeAnnual * homeAnnualRate + counts.proAnnual * proAnnualRate;

  // Starter Pack is a ONE-OFF sale: it enters the year once. Multiplying it
  // by twelve like a monthly plan would overstate the year by 11 packs.
  const starterPackRate =
    typeof starterPack.rateCents === 'number' && Number.isFinite(starterPack.rateCents)
      ? Math.max(0, Math.trunc(starterPack.rateCents))
      : 0;
  const fromStarterPacksCents = normalizeCount(starterPack.packs) * starterPackRate;

  const totalPerYearCents =
    monthlyFromMonthlyCents * MONTHS_PER_YEAR + fromAnnualRenewalsCents + fromStarterPacksCents;

  return Object.freeze({
    tier,
    monthlyFromMonthlyCents,
    fromAnnualRenewalsCents,
    fromStarterPacksCents,
    totalPerYearCents,
    // Whole cents: the page prints currency, and a fractional cent has no
    // meaning in a ledger that stores integers.
    averagePerMonthCents: Math.round(totalPerYearCents / MONTHS_PER_YEAR),
  });
}
