#!/usr/bin/env python3
"""Publish the per-country Starter Pack PDFs for staging QA (TEST_ACCOUNTS_ONLY) — plan first, then run.

Reads build/starter_local/manifest.json (publishable build; drafts are refused) and validation.json (every document must
pass). For each document it plans:
  1. an upload to the private bucket shop-documents at starter-pack-local/<version>/<iso>/<locale>-<sha256>.pdf
     (Supabase CLI `storage cp`, content type application/pdf; the CLI resolves the service key itself);
  2. one registry row: document STARTER_PACK_LOCAL_GUIDE, that market and locale, availability TEST_ACCOUNTS_ONLY,
     the two QA accounts, notifications to the controlled QA mailbox, is_current = true.
It never changes availability to ON and never touches an existing row (ON CONFLICT DO NOTHING on the unique keys).

usage: publish_starter_local.py --plan            writes publish/plan.json and publish/registry.sql, uploads nothing
       publish_starter_local.py --upload          uploads the planned files (after the plan was reviewed)
"""
import argparse, json, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
BUILD = os.path.join(HERE, 'build', 'starter_local')
OUT = os.path.join(HERE, 'publish')
PROJECT = 'tunabqqrwabacxjcxxkz'
DOCUMENT_KEY = 'STARTER_PACK_LOCAL_GUIDE'
VERSION = '1.0'
QA_USERS = ['e10ea1b3-6c5a-43b7-9173-a9a8baa43f15', 'cad05017-9efc-4cc5-ac77-842839db2061']   # QA A test1, QA B home
QA_RECIPIENT = 'info@gellatti.com'


def sql_str(s):
    return "'" + str(s).replace("'", "''") + "'"


def plan():
    manifest = json.load(open(os.path.join(BUILD, 'manifest.json')))
    if manifest.get('draft'):
        sys.exit('refusing a draft manifest')
    validation = json.load(open(os.path.join(BUILD, 'validation.json')))
    ok = {(d['iso'], d['locale']) for d in validation['documents'] if d['ok']}
    entries, refused = [], []
    for doc in manifest['documents']:
        if (doc['iso'], doc['locale']) not in ok:
            refused.append({'iso': doc['iso'], 'locale': doc['locale'], 'reason': 'validation_not_passed'})
            continue
        path = f'starter-pack-local/{VERSION}/{doc["iso"].lower()}/{doc["locale"].lower()}-{doc["sha256"]}.pdf'
        entries.append({'iso': doc['iso'], 'locale': doc['locale'], 'file': os.path.join(HERE, doc['pdf']), 'sha256': doc['sha256'],
                        'bytes': doc['bytes'], 'storage_path': path,
                        'download_file_name': f'Gellatti-Starter-Pack-{doc["iso"]}-{doc["locale"]}.pdf'})
    os.makedirs(OUT, exist_ok=True)
    json.dump({'document_key': DOCUMENT_KEY, 'version': VERSION, 'availability': 'TEST_ACCOUNTS_ONLY', 'entries': entries,
               'refused': refused}, open(os.path.join(OUT, 'plan.json'), 'w'), ensure_ascii=False, indent=1)
    values = ',\n'.join(
        f"  ({sql_str(DOCUMENT_KEY)}, {sql_str(VERSION)}, {sql_str(e['sha256'])}, {sql_str(e['storage_path'])}, {e['bytes']}, "
        f"{sql_str(e['download_file_name'])}, {sql_str(e['locale'])}, 'TEST_ACCOUNTS_ONLY', "
        f"array[{', '.join(sql_str(u) for u in QA_USERS)}]::uuid[], {sql_str(QA_RECIPIENT)}, true, {sql_str(e['iso'])})"
        for e in entries)
    sql = f"""-- Registry rows for the per-country Starter Pack PDFs (staging QA). Generated by publish_starter_local.py.
-- Every file must already be in storage: the order function refuses a row whose object is missing.
insert into public.shop_digital_documents
  (document_key, version, sha256, storage_path, byte_size, download_file_name, language, availability,
   qa_user_ids, qa_notification_recipient, is_current, country_iso2)
values
{values}
on conflict do nothing;
"""
    open(os.path.join(OUT, 'registry.sql'), 'w').write(sql)
    print(f'plan: {len(entries)} document(s), {len(refused)} refused → publish/plan.json, publish/registry.sql')


def upload():
    p = json.load(open(os.path.join(OUT, 'plan.json')))
    for e in p['entries']:
        cmd = ['supabase', 'storage', 'cp', '--experimental', '--project-ref', PROJECT, '--content-type', 'application/pdf',
               e['file'], f'ss:///shop-documents/{e["storage_path"]}']
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
        print(('OK  ' if r.returncode == 0 else 'ERR ') + e['storage_path'] + ('' if r.returncode == 0 else ' ' + r.stderr[-300:]))


if __name__ == '__main__':
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--plan', action='store_true')
    ap.add_argument('--upload', action='store_true')
    a = ap.parse_args()
    if a.plan:
        plan()
    elif a.upload:
        upload()
    else:
        ap.print_help()
