insert into public.catalog_market_countries (code, name_pl, name_en, is_active, sort_order)
values
  ('AE', 'Zjednoczone Emiraty Arabskie', 'United Arab Emirates', true, 190),
  ('AR', 'Argentyna', 'Argentina', true, 200),
  ('AU', 'Australia', 'Australia', true, 210),
  ('BD', 'Bangladesz', 'Bangladesh', true, 220),
  ('BG', 'Bułgaria', 'Bulgaria', true, 230),
  ('BH', 'Bahrajn', 'Bahrain', true, 240),
  ('BR', 'Brazylia', 'Brazil', true, 250),
  ('CA', 'Kanada', 'Canada', true, 260),
  ('CH', 'Szwajcaria', 'Switzerland', true, 270),
  ('CL', 'Chile', 'Chile', true, 280),
  ('CN', 'Chiny', 'China', true, 290),
  ('CO', 'Kolumbia', 'Colombia', true, 300),
  ('CR', 'Kostaryka', 'Costa Rica', true, 310),
  ('CY', 'Cypr', 'Cyprus', true, 320),
  ('DO', 'Dominikana', 'Dominican Republic', true, 330),
  ('DZ', 'Algieria', 'Algeria', true, 340),
  ('EE', 'Estonia', 'Estonia', true, 350),
  ('EG', 'Egipt', 'Egypt', true, 360),
  ('GH', 'Ghana', 'Ghana', true, 370),
  ('GR', 'Grecja', 'Greece', true, 380),
  ('HK', 'SRA Hongkong (Chiny)', 'Hong Kong SAR China', true, 390),
  ('HR', 'Chorwacja', 'Croatia', true, 400),
  ('HU', 'Węgry', 'Hungary', true, 410),
  ('ID', 'Indonezja', 'Indonesia', true, 420),
  ('IL', 'Izrael', 'Israel', true, 430),
  ('IN', 'Indie', 'India', true, 440),
  ('IS', 'Islandia', 'Iceland', true, 450),
  ('JP', 'Japonia', 'Japan', true, 460),
  ('KE', 'Kenia', 'Kenya', true, 470),
  ('KR', 'Korea Południowa', 'South Korea', true, 480),
  ('KW', 'Kuwejt', 'Kuwait', true, 490),
  ('LK', 'Sri Lanka', 'Sri Lanka', true, 500),
  ('LT', 'Litwa', 'Lithuania', true, 510),
  ('LU', 'Luksemburg', 'Luxembourg', true, 520),
  ('LV', 'Łotwa', 'Latvia', true, 530),
  ('MA', 'Maroko', 'Morocco', true, 540),
  ('MT', 'Malta', 'Malta', true, 550),
  ('MX', 'Meksyk', 'Mexico', true, 560),
  ('MY', 'Malezja', 'Malaysia', true, 570),
  ('NG', 'Nigeria', 'Nigeria', true, 580),
  ('NO', 'Norwegia', 'Norway', true, 590),
  ('NZ', 'Nowa Zelandia', 'New Zealand', true, 600),
  ('OM', 'Oman', 'Oman', true, 610),
  ('PA', 'Panama', 'Panama', true, 620),
  ('PK', 'Pakistan', 'Pakistan', true, 630),
  ('QA', 'Katar', 'Qatar', true, 640),
  ('RO', 'Rumunia', 'Romania', true, 650),
  ('SA', 'Arabia Saudyjska', 'Saudi Arabia', true, 660),
  ('SG', 'Singapur', 'Singapore', true, 670),
  ('SI', 'Słowenia', 'Slovenia', true, 680),
  ('TH', 'Tajlandia', 'Thailand', true, 690),
  ('TN', 'Tunezja', 'Tunisia', true, 700),
  ('TR', 'Turcja', 'Türkiye', true, 710),
  ('TW', 'Tajwan', 'Taiwan', true, 720),
  ('UY', 'Urugwaj', 'Uruguay', true, 730),
  ('VN', 'Wietnam', 'Vietnam', true, 740),
  ('ZA', 'Republika Południowej Afryki', 'South Africa', true, 750)
on conflict (code) do nothing
returning code;