/**
 * OCR label-intake copy (Polish canonical customer and reviewer language).
 *
 * ALL user-facing strings for the OCR intake feature live here (never in src/copy/en.ts,
 * which is owned by another slice). Pure data, no logic — the `satisfies` clauses below
 * are compile-time locks against the shared contract unions (intakeContracts.ts): a
 * vocabulary member added or removed there breaks this file loudly, never silently.
 */
import type {
  BatchItemOutcome,
  DuplicateVerdict,
  EvidenceProvenance,
  FieldReviewStatus,
  IntakeFieldKey,
  IntakeImageRole,
  IntakeImageState,
} from './intakeContracts';

export const ocrCopy = {
  page: {
    devTag: 'Narzędzie wewnętrzne',
    title: 'Odczyt etykiety',
    intro:
      'Dodaj zdjęcie etykiety, sprawdź odczytane pola i potwierdź dane produktu. Nic nie zapisze się bez Twojej decyzji.',
    privacyNote:
      'Zdjęcie pozostaje w tej karcie i nie jest nigdzie wysyłane. Przeglądarka pobiera tylko przypięte pliki modułu OCR: skrypt roboczy, rdzeń WASM i modele językowe.',
  },
  input: {
    chooseImage: 'Wybierz zdjęcie etykiety',
    accepted: 'Obsługiwane formaty: PNG, JPEG, WebP',
    rejectedType: 'Ten format nie jest obsługiwany. Użyj PNG, JPEG lub WebP.',
    tooLarge: 'Zdjęcie jest za duże',
    runOcr: 'Odczytaj etykietę',
    cancel: 'Anuluj',
    running: 'Odczytuję etykietę…',
    retry: 'Spróbuj ponownie',
  },
  failure: {
    unreadable:
      'Nie udało się odczytać tekstu. Dodaj ostre, dobrze oświetlone zdjęcie etykiety zrobione na wprost.',
    cancelled: 'Odczyt został anulowany. Niczego nie zapisaliśmy.',
    engineError: 'Nie udało się odczytać etykiety.',
  },
  review: {
    title: 'Sprawdź odczytane dane',
    rawTextTitle: 'Odczytany tekst',
    imageTitle: 'Oryginalne zdjęcie',
    confidence: 'Pewność odczytu',
    bandHigh: 'wysoka',
    bandMedium: 'średnia',
    bandLow: 'niska',
    bandUnknown: 'brak',
    needsConfirmation: 'wymaga potwierdzenia',
    confirm: 'Potwierdź',
    confirmed: 'potwierdzone',
    notFound: 'nie znaleziono na etykiecie',
    globalWarningsTitle: 'Miejsca wymagające uwagi',
    basisLabel: 'Podstawa wartości odżywczych',
    languageLabel: 'Rozpoznany język',
  },
  fields: {
    productName: 'Nazwa produktu',
    brand: 'Marka',
    eanCode: 'EAN / kod kreskowy',
    netQuantity: 'Ilość netto',
    energyKj: 'Energia (kJ)',
    energyKcal: 'Energia (kcal)',
    fat: 'Tłuszcz (g)',
    saturatedFat: 'w tym kwasy nasycone (g)',
    carbohydrates: 'Węglowodany (g)',
    sugars: 'w tym cukry (g)',
    protein: 'Białko (g)',
    salt: 'Sól (g)',
    ingredientsText: 'Składniki',
    allergens: 'Alergeny / zawiera',
    mayContain: 'Może zawierać',
    storageInstructions: 'Warunki przechowywania',
  },
  basis: {
    per_100g: 'na 100 g',
    per_100ml: 'na 100 ml',
    serving_only: 'tylko na porcję',
    unknown: 'nieznana',
  },
  handoff: {
    buildDraft: 'Potwierdź i przygotuj produkt',
    blocked: 'Potwierdź wszystkie oznaczone pola, aby przygotować produkt.',
    draftTitle: 'Szkic produktu — jeszcze niezapisany',
    draftNote: 'To podgląd produktu. Dane zostaną zapisane dopiero po Twoim potwierdzeniu.',
  },

  /* ── full multi-image session experience (contract-typed panels) ────────── */
  session: {
    title: 'Pełny odczyt produktu',
    intro: 'Dodaj kilka zdjęć opakowania, sprawdź kod kreskowy i potwierdź każde wymagane pole.',
    demoNote: 'To dane przykładowe. Nie pochodzą z prawdziwego zdjęcia i nie zostaną zapisane.',
    stateLabel: 'Stan odczytu',
    engineWired: 'Odczyt jest dostępny',
    engineNotWired: 'Tryb przykładowy',
    recheckDuplicate: 'Sprawdź duplikaty ponownie',
    recheckDuplicatePending: 'Sprawdzanie duplikatów pojawi się wkrótce',
    batchLink: 'Otwórz kolejkę produktów',
  },
  images: {
    title: 'Zdjęcia opakowania',
    addImages: 'Dodaj zdjęcia opakowania',
    dropZone: 'Przeciągnij zdjęcia tutaj lub wybierz je z urządzenia',
    camera: 'Zrób zdjęcie',
    cameraNote: 'Na telefonie otworzy się tylna kamera, a na komputerze wybór pliku.',
    acceptedNote: 'PNG, JPEG lub WebP — do 10 MB na zdjęcie.',
    heicRejected:
      'Ta przeglądarka nie odczytuje zdjęć HEIC/HEIF. Zapisz zdjęcie jako JPEG lub PNG i dodaj ponownie.',
    unsupportedType: 'Ten format nie jest obsługiwany. Użyj PNG, JPEG lub WebP.',
    empty: 'Nie dodano jeszcze zdjęć opakowania.',
    roleLabel: 'Co pokazuje zdjęcie',
    moveUp: 'Przenieś wcześniej',
    moveDown: 'Przenieś później',
    replace: 'Zastąp zdjęcie',
    remove: 'Usuń zdjęcie',
    retry: 'Spróbuj ponownie',
    checksumPending: 'sha256: pending',
    states: {
      uploaded: 'dodane',
      analysing: 'analizowane',
      needs_review: 'do sprawdzenia',
      ready: 'gotowe',
      failed: 'błąd',
    } satisfies Record<IntakeImageState, string>,
    roles: {
      front: 'Przód opakowania',
      back: 'Tył opakowania',
      nutrition_table: 'Tabela wartości odżywczych',
      ingredients: 'Wykaz składników',
      barcode: 'Kod kreskowy',
      claims_allergens: 'Oświadczenia / alergeny',
      other: 'Inne',
    } satisfies Record<IntakeImageRole, string>,
  },
  barcode: {
    title: 'Kod EAN / kod kreskowy',
    label: 'Wpisz kod EAN / kod kreskowy',
    help: 'Wpisz lub zeskanuj cyfry kodu. Litery i spacje zostaną pominięte.',
    normalized: 'Odczytany kod',
    incomplete: 'Kod EAN/GTIN ma 8, 12, 13 lub 14 cyfr.',
    checksumInvalid: 'Cyfry nie tworzą prawidłowego kodu EAN/GTIN. Sprawdź je i spróbuj ponownie.',
  },
  evidence: {
    title: 'Sprawdź źródła danych',
    intro:
      'Każde pole pokazuje, skąd pochodzi wartość i jak pewny jest odczyt. Brakująca wartość pozostaje pusta — nigdy nie zastępujemy jej zerem.',
    groups: {
      identity: 'Tożsamość produktu',
      nutrition: 'Wartości odżywcze',
      ingredients: 'Składniki i alergeny',
      claims: 'Oświadczenia',
    },
    missing: 'nie znaleziono — wpisz ręcznie lub oznacz jako nieznane',
    markedUnknown: 'oznaczono jako nieznane',
    provenance: {
      explicit: 'wprost z etykiety',
      calculated: 'obliczone',
      inferred: 'wywnioskowane',
      absent: 'brak',
    } satisfies Record<EvidenceProvenance, string>,
    status: {
      auto_accepted: 'przyjęte automatycznie',
      needs_confirmation: 'wymaga potwierdzenia',
      confirmed: 'potwierdzone',
      edited: 'edytowane',
      marked_unknown: 'oznaczone jako nieznane',
      conflict_unresolved: 'różne odczyty — wybierz wartość',
    } satisfies Record<FieldReviewStatus, string>,
    readConfidence: 'odczyt',
    normalizationConfidence: 'normalizacja',
    noConfidence: 'brak',
    source: 'Źródło',
    line: 'wiersz',
    conflictTitle: 'Znaleziono różne wartości. Wybierz właściwą:',
    useCandidate: 'Użyj tej wartości',
    chosen: 'wybrana',
    editAction: 'Edytuj',
    confirmAction: 'Potwierdź',
    markUnknownAction: 'Oznacz jako nieznane',
    warningsTitle: 'Wymaga uwagi',
    fields: {
      product_name: 'Nazwa produktu',
      brand: 'Marka',
      package_size: 'Wielkość opakowania',
      package_unit: 'Jednostka opakowania',
      ean_code: 'EAN / kod kreskowy',
      country: 'Kraj',
      supplier: 'Dostawca',
      category: 'Kategoria',
      subcategory: 'Podkategoria',
      nutrition_basis: 'Podstawa wartości odżywczych',
      energy_kcal: 'Energia (kcal)',
      energy_kj: 'Energia (kJ)',
      fat: 'Tłuszcz (g)',
      saturated_fat: 'w tym kwasy nasycone (g)',
      carbohydrate: 'Węglowodany (g)',
      sugars: 'w tym cukry (g)',
      protein: 'Białko (g)',
      salt: 'Sól (g)',
      sodium: 'Sód (g) — wartość źródłowa, bez automatycznego przeliczenia na sól',
      fibre: 'Błonnik (g)',
      ingredients_text: 'Składniki',
      allergens_text: 'Alergeny / zawiera',
      may_contain_text: 'Może zawierać',
      claim_vegan: 'Oświadczenie: wegański',
      claim_vegetarian: 'Oświadczenie: wegetariański',
      claim_gluten_free: 'Oświadczenie: bez glutenu',
      claim_lactose_free: 'Oświadczenie: bez laktozy',
      claims_other: 'Inne oświadczenia',
    } satisfies Record<IntakeFieldKey, string>,
  },
  duplicate: {
    title: 'Czy to ten sam produkt?',
    verdicts: {
      exact_duplicate: 'Ten produkt już istnieje',
      likely_duplicate: 'Prawdopodobnie ten sam produkt',
      new_product: 'Nowy produkt',
    } satisfies Record<DuplicateVerdict, string>,
    verdictNotes: {
      exact_duplicate:
        'Otworzymy istniejący wpis i dodamy go do Twoich Ulubionych. Nie tworzymy kopii.',
      likely_duplicate: 'Porównaj markę, nazwę, opakowanie, rynek i kluczowe różnice.',
      new_product: 'Nie znaleźliśmy odpowiednika. Produkt może wejść do wspólnego katalogu.',
    } satisfies Record<DuplicateVerdict, string>,
    reasons: {
      ean_match: 'EAN odpowiada istniejącemu produktowi',
      identity_hash_match: 'Identyfikator produktu jest zgodny',
      normalized_identity_match: 'Nazwa, marka i wariant są bardzo podobne',
    },
    score: 'zgodność',
    existingProduct: 'produkt',
    actions: {
      open_existing: 'Tak, to ten produkt',
      update_existing_with_review: 'Uzupełnij istniejący produkt',
      create_new: 'Nie, to inny produkt',
    },
  },
  catalog: {
    automaticContribution: 'Po zapisaniu dane etykiety trafią do wspólnego katalogu Gellatti.',
    reviewLimit: 'Osiągnięto limit zgłoszeń wymagających ręcznej weryfikacji.',
    rateLimit: 'Zbyt wiele prób. Spróbuj ponownie później.',
    riskChallenge: 'Potwierdź, że nie jesteś robotem, aby kontynuować.',
    existingResolved: 'Istniejący produkt został dodany do Twoich Ulubionych.',
    createdAndFavorited: 'Produkt dodano do katalogu i do Twoich Ulubionych.',
  },
  batch: {
    title: 'Kolejka produktów',
    intro:
      'Każdy produkt zachowuje miejsce w kolejce i pokazuje rzeczywisty wynik. Podsumowanie wynika z tych wyników.',
    empty: 'W tej kolejce nie ma jeszcze produktów.',
    itemLabel: 'produkt',
    outcomes: {
      saved: 'zapisany',
      duplicate: 'duplikat',
      needs_review: 'do sprawdzenia',
      failed: 'błąd',
      pending: 'oczekuje',
    } satisfies Record<BatchItemOutcome, string>,
    summaryLabels: {
      processed: 'przetworzone',
      saved: 'zapisane',
      duplicate: 'duplikaty',
      needsReview: 'do sprawdzenia',
      failed: 'błędy',
      pending: 'oczekujące',
    },
    retryFailed: 'Spróbuj ponownie dla błędów',
    exportCsv: 'Eksportuj CSV',
    exportCsvPending: 'Eksport CSV pojawi się po podłączeniu integracji',
  },
} as const;
