/** Tester-facing copy (Polish). Internal codes never appear here. */
export const copy = {
  title: 'Scan Lab — test aparatu (faza 0)',
  intro: {
    lead: 'Ten test mierzy, jak Twój telefon i przeglądarka radzą sobie z kodami kreskowymi na opakowaniach. Trwa ok. 6–8 minut.',
    whatWeRecord:
      'Co zapisujemy (tylko na tym telefonie, dopóki sam(a) nie wyślesz pliku): model telefonu wpisany przez Ciebie, wersję systemu i przeglądarki, ustawienia aparatu, czasy klatek i dekodowania, oraz kilka klatek z aparatu pokazujących opakowania.',
    noIds: 'Nie zapisujemy żadnych identyfikatorów urządzenia, lokalizacji ani nagrań dźwięku.',
    start: 'Zaczynamy',
  },
  device: {
    modelLabel: 'Model telefonu',
    modelPlaceholder: 'np. iPhone 15 Pro Max',
    declaredCode: 'Cyfry pod kodem kreskowym (opcjonalnie)',
    declaredHint:
      'Wpisz 13 cyfr z produktu, którego użyjesz w scenach z kodem. Dzięki temu policzymy błędne odczyty.',
    modeLabel: 'Tryb uruchomienia',
    next: 'Dalej',
  },
  camera: {
    heading: 'Aparat',
    enable: 'Włącz aparat',
    enabling: 'Uruchamiam aparat…',
    delivered: 'Aparat dostarcza',
    requested: 'Prosiliśmy o',
    choose: 'Wybierz kamerę',
    switching: 'Przełączam…',
    ultrawideWarning:
      'Uwaga: wybrana kamera wygląda na ultraszerokokątną. Do kodów kreskowych wybierz główny aparat tylny.',
    next: 'Dalej',
    insecure:
      'Aparat działa tylko na bezpiecznym adresie (https). Otwórz stronę przez adres z certyfikatem.',
    unsupported: 'Ta przeglądarka nie udostępnia aparatu stronom internetowym.',
    ended: 'Aparat został zatrzymany (aplikacja była w tle). Włącz go ponownie.',
  },
  probe: {
    heading: 'Sprawdzam sterowanie aparatem i dekoder',
    running: 'Sprawdzam zoom, latarkę i uruchamiam dekoder…',
    zoom: 'Zoom',
    torch: 'Latarka',
    focus: 'Tryb ostrości widoczny dla strony',
    worker: 'Dekoder gotowy',
    supported: 'obsługiwane',
    unsupported: 'brak',
    ok: 'działa',
    failed: 'nie zadziałało',
    next: 'Przejdź do scen',
  },
  scene: {
    of: (i: number, n: number) => `Scena ${i} z ${n}`,
    start: 'Start',
    stop: 'Zakończ wcześniej',
    skip: 'Pomiń',
    retry: 'Powtórz',
    next: 'Dalej',
    recording: 'NAGRYWANIE',
    ready: 'GOTOWE',
    done: 'ZAPISANE',
    remaining: (s: number) => `${s} s`,
    torchOn: 'Latarka: włącz',
    torchOff: 'Latarka: wyłącz',
    firstDecode: 'Pierwszy odczyt',
    values: 'Odczytane wartości',
    noDecode: 'brak odczytu',
    wrong: 'błędny',
    frames: 'Klatki',
    saved: 'Scena zapisana.',
    declaredMismatch: 'Odczyt różni się od wpisanych cyfr',
  },
  hud: {
    fps: 'kl/s',
    processed: 'przetworzone',
    dropped: 'pominięte',
    roundTrip: 'worker p50',
    lastValue: 'ostatni odczyt',
    streak: 'zgodne z rzędu',
    path: 'ścieżka',
  },
  diagnostics: {
    toggle: 'Diagnostyka',
    hide: 'Ukryj diagnostykę',
    transferPath: 'Ścieżka przekazania klatki do workera',
    decodeWidth: 'Rozdzielczość analizy (dłuższy bok klatki)',
    native: 'natywna (jak dostarcza aparat)',
    storage: 'Pamięć lokalna',
    session: 'Sesja',
    worker: 'Dekoder',
  },
  summary: {
    heading: 'Podsumowanie',
    export: 'Eksportuj wyniki (.zip)',
    preparing: 'Przygotowuję archiwum…',
    shared: 'Udostępniono.',
    downloaded: 'Pobrano plik.',
    cancelled: 'Anulowano udostępnianie.',
    unsupported: 'Ta przeglądarka nie potrafi zapisać pliku. Otwórz test w Safari lub Chrome.',
    download: 'Pobierz plik (.zip)',
    sendToMac: 'Wyślij na komputer (tunel)',
    sending: 'Wysyłam…',
    sent: (mb: string) => `Wysłano na komputer (${mb} MB). Dziękuję!`,
    sendFailed: 'Nie udało się wysłać na komputer — pobierz plik i wyślij go inaczej.',
    copyJson: 'Skopiuj raport (JSON)',
    copied: 'Skopiowano.',
    delete: 'Usuń dane tej sesji z telefonu',
    deleteConfirm: 'Usunąć wszystkie dane tej sesji z telefonu? Tej operacji nie można cofnąć.',
    deleted: 'Dane usunięte.',
    columns: {
      scene: 'Scena',
      verdict: 'Wynik',
      firstConfirmed: 'Potwierdzony odczyt',
      hits: 'Odczyty',
      fps: 'kl/s p50',
      worker: 'worker p95',
    },
    verdict: {
      DECODED_CONFIRMED: 'odczytano (potwierdzone)',
      DECODED_UNCONFIRMED: 'odczyt niepotwierdzony',
      MISREAD: 'BŁĘDNY ODCZYT',
      NO_DECODE: 'brak odczytu',
      NOT_APPLICABLE: 'scena bez kodu',
    } as Record<string, string>,
    sendHint:
      'Wyślij plik .zip (AirDrop, e-mail, komunikator). Nic nie zostało wysłane automatycznie.',
  },
  error: { ok: 'OK' },
  resume: { found: 'Znaleziono przerwaną sesję.', continue: 'Kontynuuj', fresh: 'Zacznij od nowa' },
} as const;
