import type { CSSProperties } from 'react';

const font = "'Manrope Variable', system-ui, -apple-system, sans-serif";

export const styles: Record<string, CSSProperties> = {
  root: {
    minHeight: '100dvh',
    background: '#0b0f14',
    color: '#f2f5f7',
    fontFamily: font,
    padding: '12px 12px 96px',
    boxSizing: 'border-box',
    maxWidth: 720,
    margin: '0 auto',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    gap: 12,
    padding: '6px 2px 12px',
  },
  title: { fontSize: 16, fontWeight: 700, letterSpacing: 0.2 },
  subtitle: { fontSize: 13, opacity: 0.8 },
  card: {
    background: '#121922',
    border: '1px solid #223041',
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
  },
  h2: { fontSize: 18, fontWeight: 700, marginBottom: 6 },
  p: { fontSize: 15, lineHeight: 1.45, margin: '6px 0' },
  hint: { fontSize: 13, opacity: 0.75, margin: '6px 0' },
  warn: {
    fontSize: 14,
    color: '#ffd166',
    background: '#3a2e0a',
    border: '1px solid #7a5f10',
    borderRadius: 10,
    padding: '8px 10px',
    margin: '8px 0',
  },
  label: { display: 'block', fontSize: 14, margin: '10px 0 4px' },
  input: {
    display: 'block',
    width: '100%',
    boxSizing: 'border-box',
    marginTop: 4,
    padding: '12px',
    fontSize: 17,
    borderRadius: 10,
    border: '1px solid #33465c',
    background: '#0b0f14',
    color: '#f2f5f7',
  },
  button: {
    minHeight: 48,
    padding: '12px 18px',
    fontSize: 17,
    fontWeight: 700,
    borderRadius: 12,
    border: 'none',
    background: '#2ee6a6',
    color: '#062016',
    marginTop: 12,
    cursor: 'pointer',
  },
  buttonSecondary: {
    minHeight: 48,
    padding: '12px 18px',
    fontSize: 16,
    fontWeight: 600,
    borderRadius: 12,
    border: '1px solid #33465c',
    background: 'transparent',
    color: '#f2f5f7',
    marginTop: 12,
    cursor: 'pointer',
  },
  row: { display: 'flex', gap: 10, flexWrap: 'wrap' },
  kv: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 12,
    fontSize: 14,
    padding: '6px 0',
    borderBottom: '1px solid #1c2733',
  },
  errorBox: {
    background: '#3b1111',
    border: '1px solid #8a2b2b',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    fontSize: 15,
  },
  resumeBox: {
    background: '#0f2a22',
    border: '1px solid #1f6b53',
    borderRadius: 12,
    padding: 12,
    margin: '10px 0',
  },
  videoWrap: {
    position: 'relative',
    width: '100%',
    aspectRatio: '3 / 4',
    background: '#000',
    borderRadius: 14,
    overflow: 'hidden',
    marginBottom: 12,
  },
  video: { position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover' },
  overlay: { position: 'absolute', inset: 0, width: '100%', height: '100%', pointerEvents: 'none' },
  hud: {
    position: 'absolute',
    left: 8,
    right: 8,
    bottom: 8,
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 6,
    fontSize: 12,
    fontFamily: "'IBM Plex Mono', ui-monospace, monospace",
  },
  hudCell: {
    background: 'rgba(11,15,20,0.78)',
    borderRadius: 8,
    padding: '6px 8px',
    lineHeight: 1.3,
  },
  badge: {
    position: 'absolute',
    top: 8,
    left: 8,
    padding: '4px 10px',
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: 1,
  },
  progress: { position: 'absolute', top: 0, left: 0, height: 4, background: '#2ee6a6' },
  torch: {
    position: 'absolute',
    top: 8,
    right: 8,
    minHeight: 40,
    padding: '8px 12px',
    borderRadius: 999,
    border: '1px solid #33465c',
    background: 'rgba(11,15,20,0.78)',
    color: '#f2f5f7',
    fontSize: 13,
  },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 13 },
  th: { textAlign: 'left', padding: '6px 4px', borderBottom: '1px solid #33465c', fontWeight: 700 },
  td: { padding: '6px 4px', borderBottom: '1px solid #1c2733', verticalAlign: 'top' },
  mono: {
    fontFamily: "'IBM Plex Mono', ui-monospace, monospace",
    fontSize: 12,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-all',
    background: '#0b0f14',
    borderRadius: 10,
    padding: 10,
    maxHeight: 260,
    overflow: 'auto',
  },
  details: { marginTop: 8 },
};
