/**
 * First ACTIVE external reference fixture (spec §16) — a verified milk-base
 * recipe transcribed VERBATIM from the external reference tool's screens.
 *
 * Provenance: every number below is the product owner's verified reference data
 * (grams, per-100 g composition profiles, per-ingredient `pod_value`/`pac_value`,
 * displayed result values and target bands). Nothing here is invented.
 *
 * Stored-value mapping (documented modeling decision, spec §8):
 *   the reference's per-ingredient `pac_value` is its NET anti-freezing power, so
 *   it is stored into the engine's net NPAC slot (`npac_value = pac_value`). The
 *   `pac_value` slot keeps the same number so a recipe PAC read is also available.
 *   This mapping is validated by the calibration report: under per_water_mass the
 *   recipe NPAC reproduces the reference's displayed 40.74 exactly.
 *
 * This fixture is DATA ONLY. It changes no formula, no config, no normalization
 * basis and no ice anchor. The calibration report (milkBaseCalibration.report.test)
 * reads it and prints the comparison; it does not enforce within-tolerance, so an
 * intentionally-uncalibrated config never turns the suite red.
 */
import type { ActiveRecipeFixture } from '../schema';

export const externalReferenceMilkBase: ActiveRecipeFixture = {
  kind: 'recipe',
  name: 'External Reference Milk Base -11C',
  status: 'active',
  category: 'milk_gelato',
  temperature_c: -11,
  batch_grams: 1000,
  input: [
    {
      ingredient_name: 'Milk 3.5%',
      grams: 523.5,
      pod_value: 0.75,
      pac_value: 5.29,
      npac_value: 5.29,
      composition: {
        kcal_per_100g: 60,
        water_percent: 88.7,
        solids_percent: 11.3,
        fat_percent: 3.5,
        saturated_fat_percent: 2,
        carbohydrate_percent: 4.7,
        sugar_percent: 4.7,
        sucrose_percent: 0,
        glucose_percent: 0,
        dextrose_percent: 0,
        fructose_percent: 0,
        lactose_percent: 4.7,
        polyol_percent: 0,
        fiber_percent: 0,
        protein_percent: 3,
        salt_percent: 0.1,
        alcohol_percent: 0,
      },
    },
    {
      ingredient_name: 'Cream 30%',
      grams: 263.5,
      pod_value: 0.51,
      pac_value: 3.67,
      npac_value: 3.67,
      composition: {
        kcal_per_100g: 292,
        water_percent: 64.42,
        solids_percent: 35.58,
        fat_percent: 30,
        saturated_fat_percent: 20,
        carbohydrate_percent: 3.2,
        sugar_percent: 3.2,
        sucrose_percent: 0,
        glucose_percent: 0,
        dextrose_percent: 0,
        fructose_percent: 0,
        lactose_percent: 3.2,
        polyol_percent: 0,
        fiber_percent: 0,
        protein_percent: 2.3,
        salt_percent: 0.08,
        alcohol_percent: 0,
      },
    },
    {
      ingredient_name: 'Skimmed milk powder',
      grams: 48.4,
      pod_value: 8.16,
      pac_value: 58.02,
      npac_value: 58.02,
      composition: {
        kcal_per_100g: 362,
        water_percent: 10.32,
        solids_percent: 89.68,
        fat_percent: 0.8,
        saturated_fat_percent: 0.54,
        carbohydrate_percent: 51.98,
        sugar_percent: 51,
        sucrose_percent: 0,
        glucose_percent: 0,
        dextrose_percent: 0,
        fructose_percent: 0,
        lactose_percent: 51,
        polyol_percent: 0,
        fiber_percent: 0,
        protein_percent: 35.7,
        salt_percent: 1.2,
        alcohol_percent: 0,
      },
    },
    {
      ingredient_name: 'Sucrose',
      grams: 123.4,
      pod_value: 100,
      pac_value: 100,
      npac_value: 100,
      composition: {
        kcal_per_100g: 400,
        water_percent: 0,
        solids_percent: 100,
        fat_percent: 0,
        saturated_fat_percent: 0,
        carbohydrate_percent: 100,
        sugar_percent: 100,
        sucrose_percent: 100,
        glucose_percent: 0,
        dextrose_percent: 0,
        fructose_percent: 0,
        lactose_percent: 0,
        polyol_percent: 0,
        fiber_percent: 0,
        protein_percent: 0,
        salt_percent: 0,
        alcohol_percent: 0,
      },
    },
    {
      ingredient_name: 'Dextrose',
      grams: 38.3,
      pod_value: 70.84,
      pac_value: 174.8,
      npac_value: 174.8,
      composition: {
        kcal_per_100g: 368,
        water_percent: 8,
        solids_percent: 92,
        fat_percent: 0,
        saturated_fat_percent: 0,
        carbohydrate_percent: 92,
        sugar_percent: 92,
        sucrose_percent: 0,
        glucose_percent: 92,
        dextrose_percent: 0,
        fructose_percent: 0,
        lactose_percent: 0,
        polyol_percent: 0,
        fiber_percent: 0,
        protein_percent: 0,
        salt_percent: 0,
        alcohol_percent: 0,
      },
    },
    {
      ingredient_name: 'Tara gum',
      grams: 1.92,
      pod_value: 0,
      pac_value: 0,
      npac_value: 0,
      composition: {
        kcal_per_100g: 180,
        water_percent: 9.5,
        solids_percent: 90.5,
        fat_percent: 0.5,
        saturated_fat_percent: 0,
        carbohydrate_percent: 1.5,
        sugar_percent: 0,
        sucrose_percent: 0,
        glucose_percent: 0,
        dextrose_percent: 0,
        fructose_percent: 0,
        lactose_percent: 0,
        polyol_percent: 0,
        fiber_percent: 86.5,
        protein_percent: 2,
        salt_percent: 0,
        alcohol_percent: 0,
      },
    },
    {
      ingredient_name: 'Salt',
      grams: 1.01,
      pod_value: 0,
      pac_value: 585,
      npac_value: 585,
      composition: {
        kcal_per_100g: 0,
        water_percent: 0,
        solids_percent: 100,
        fat_percent: 0,
        saturated_fat_percent: 0,
        carbohydrate_percent: 0,
        sugar_percent: 0,
        sucrose_percent: 0,
        glucose_percent: 0,
        dextrose_percent: 0,
        fructose_percent: 0,
        lactose_percent: 0,
        polyol_percent: 0,
        fiber_percent: 0,
        protein_percent: 0,
        salt_percent: 90,
        alcohol_percent: 0,
      },
    },
  ],
  expected: {
    pod: 15.98,
    npac: 40.74,
    ice_fraction: 50.74,
    water: 64.23,
    total_solids: 35.77,
    fat: 9.78,
    lactose: 5.77,
    aerating_protein: 3.9,
    protein_in_solids: 10.92,
    lactose_sandiness_risk: 8.99,
    cost_per_kg: 1.97,
    cost_per_serving_80g: 0.16,
  },
  bands: {
    pod: [12.0, 17.0],
    npac: [33.0, 42.0],
    ice_fraction: [45.0, 54.5],
    lactose: [4.0, 6.0],
    lactose_sandiness_risk: [5.0, 9.0],
    fat: [5.0, 12.0],
    aerating_protein: [3.0, 6.0],
    protein_in_solids: [9.0, 13.0],
    total_solids: [31.0, 45.0],
    water: [57.0, 70.0],
  },
  tolerance: 0.5,
};
