import type { SceneDefinition } from './types';

/** Owner benchmark scenes (brief of 2026-09-03). Tester-facing copy is Polish. */
export const SCENES: SceneDefinition[] = [
  {
    id: 'ean-12cm',
    kind: 'barcode',
    title: 'Kod EAN z ok. 12 cm',
    instruction:
      'Trzymaj opakowanie tak, aby kod kreskowy był ok. 12 cm od aparatu. Trzymaj spokojnie przez cały czas nagrania.',
    durationMs: 8000,
    expectsCode: true,
  },
  {
    id: 'ean-18cm',
    kind: 'barcode',
    title: 'Kod EAN z ok. 18 cm',
    instruction: 'Ten sam kod z ok. 18 cm. Trzymaj spokojnie.',
    durationMs: 8000,
    expectsCode: true,
  },
  {
    id: 'ean-25cm',
    kind: 'barcode',
    title: 'Kod EAN z ok. 25 cm',
    instruction: 'Ten sam kod z ok. 25 cm. Trzymaj spokojnie.',
    durationMs: 8000,
    expectsCode: true,
  },
  {
    id: 'ean-30cm',
    kind: 'barcode',
    title: 'Kod EAN z ok. 30 cm',
    instruction: 'Ten sam kod z ok. 30 cm. Trzymaj spokojnie.',
    durationMs: 8000,
    expectsCode: true,
  },
  {
    id: 'ean-approach-40cm',
    kind: 'barcode',
    title: 'Zbliżanie od ok. 40 cm',
    instruction:
      'Zacznij z ok. 40 cm i powoli zbliżaj telefon do kodu, aż wypełni większość kadru.',
    durationMs: 10000,
    expectsCode: true,
  },
  {
    id: 'ean-enter-edge',
    kind: 'barcode',
    title: 'Kod wjeżdża od krawędzi kadru',
    instruction:
      'Zacznij z kodem poza kadrem i powoli przesuń telefon tak, aby kod wjechał z boku do środka.',
    durationMs: 10000,
    expectsCode: true,
  },
  {
    id: 'ean-yaw-30',
    kind: 'barcode',
    title: 'Kod pod kątem ok. 30°',
    instruction: 'Obróć opakowanie ok. 30° względem aparatu (skos w poziomie). Trzymaj spokojnie.',
    durationMs: 8000,
    expectsCode: true,
  },
  {
    id: 'ean-yaw-60',
    kind: 'barcode',
    title: 'Kod pod kątem ok. 60°',
    instruction: 'Obróć opakowanie ok. 60° względem aparatu. Trzymaj spokojnie.',
    durationMs: 8000,
    expectsCode: true,
  },
  {
    id: 'ean-curved-can',
    kind: 'barcode',
    title: 'Kod na zakrzywionej puszce',
    instruction: 'Pokaż kod na puszce (walcowate opakowanie) z ok. 15–20 cm.',
    durationMs: 8000,
    expectsCode: true,
  },
  {
    id: 'ean-small-bottle',
    kind: 'barcode',
    title: 'Kod na małej butelce',
    instruction: 'Pokaż kod na małej butelce z ok. 15–20 cm.',
    durationMs: 8000,
    expectsCode: true,
  },
  {
    id: 'ean-glare',
    kind: 'barcode',
    title: 'Błyszczące opakowanie / odblask',
    instruction:
      'Wybierz błyszczące opakowanie i ustaw je tak, aby na kodzie był widoczny odblask światła.',
    durationMs: 8000,
    expectsCode: true,
  },
  {
    id: 'ean-hand-motion',
    kind: 'barcode',
    title: 'Ruch ręki',
    instruction:
      'Przesuwaj telefon nad kodem naturalnym ruchem ręki (tak jak przy skanowaniu w sklepie), bez zatrzymywania.',
    durationMs: 10000,
    expectsCode: true,
  },
  {
    id: 'ean-low-light',
    kind: 'barcode',
    title: 'Słabe światło',
    instruction: 'Przyciemnij pomieszczenie (bez latarki) i pokaż kod z ok. 15–20 cm.',
    durationMs: 8000,
    expectsCode: true,
  },
  {
    id: 'ean-low-light-torch',
    kind: 'barcode',
    title: 'Słabe światło + latarka',
    instruction:
      'To samo w słabym świetle, ale z włączoną latarką (przycisk poniżej, jeśli aparat ją obsługuje).',
    durationMs: 8000,
    expectsCode: true,
  },
  {
    id: 'ean-scratched',
    kind: 'barcode',
    title: 'Porysowany / uszkodzony kod',
    instruction: 'Pokaż kod, który jest porysowany lub częściowo uszkodzony, z ok. 15–20 cm.',
    durationMs: 8000,
    expectsCode: true,
  },
  {
    id: 'ean-human-digits',
    kind: 'barcode',
    title: 'Widoczne cyfry pod kodem',
    instruction:
      'Ustaw kadr tak, aby cały kod i cyfry pod nim były wyraźnie widoczne, z ok. 15 cm.',
    durationMs: 8000,
    expectsCode: true,
  },
  {
    id: 'ean-two-codes',
    kind: 'barcode',
    title: 'Dwa kody w kadrze',
    instruction: 'Ustaw dwa opakowania obok siebie tak, aby oba kody były w kadrze.',
    durationMs: 8000,
    expectsCode: true,
  },
  {
    id: 'ean-partial',
    kind: 'barcode',
    title: 'Częściowo ucięty kod',
    instruction: 'Ustaw kod tak, aby część kodu była poza kadrem (ok. połowa widoczna).',
    durationMs: 8000,
    expectsCode: true,
  },
  {
    id: 'ean-small',
    kind: 'barcode',
    title: 'Mały kod kreskowy',
    instruction:
      'Wybierz opakowanie z małym kodem (np. mała przyprawa, guma) i pokaż go z ok. 12–15 cm.',
    durationMs: 8000,
    expectsCode: true,
  },
  {
    id: 'obj-banana',
    kind: 'object',
    title: 'Banan',
    instruction: 'Trzymaj banana w kadrze, na wyciągnięcie ręki. Obróć go powoli raz.',
    durationMs: 8000,
    expectsCode: false,
  },
  {
    id: 'obj-apple',
    kind: 'object',
    title: 'Jabłko',
    instruction: 'Trzymaj jabłko w kadrze, na wyciągnięcie ręki. Obróć je powoli raz.',
    durationMs: 8000,
    expectsCode: false,
  },
  {
    id: 'obj-oreo',
    kind: 'object',
    title: 'Opakowanie Oreo',
    instruction: 'Pokaż przód opakowania, potem powoli obróć na bok z etykietą.',
    durationMs: 8000,
    expectsCode: false,
  },
  {
    id: 'obj-milk-carton',
    kind: 'object',
    title: 'Karton mleka',
    instruction: 'Pokaż przód kartonu, potem bok z tabelą wartości odżywczych.',
    durationMs: 8000,
    expectsCode: false,
  },
  {
    id: 'obj-can',
    kind: 'object',
    title: 'Puszka',
    instruction: 'Trzymaj puszkę w kadrze i powoli obróć ją raz.',
    durationMs: 8000,
    expectsCode: false,
  },
  {
    id: 'obj-bottle',
    kind: 'object',
    title: 'Butelka',
    instruction: 'Trzymaj butelkę w kadrze i powoli obróć ją raz, etykietą do aparatu.',
    durationMs: 8000,
    expectsCode: false,
  },
  {
    id: 'loop-60s',
    kind: 'object',
    title: 'Test ciągły 60 s',
    instruction:
      'Trzymaj telefon nad dowolnym opakowaniem z kodem przez pełną minutę, tak jak przy zwykłym skanowaniu. Mierzymy, czy aparat i dekoder zwalniają z czasem.',
    durationMs: 60000,
    expectsCode: false,
  },
];

export const SCENE_BY_ID: ReadonlyMap<string, SceneDefinition> = new Map(
  SCENES.map((s) => [s.id, s]),
);
