/**
 * All user-facing copy lives here (typed, English-only MVP).
 * Centralized for later i18n extraction — never hardcode strings in components.
 */
export const copy = {
  brand: {
    name: 'PINGÜINO',
    sub: 'INTELLIGENCE',
    full: 'PINGÜINO Intelligence',
  },
  /** PI status vocabulary (Masterplan §12.7 — full engine set + UI chip states). */
  status: {
    ideal: 'Ideal',
    good: 'Good',
    risky: 'Risky',
    tooSoft: 'Too soft',
    tooHard: 'Too hard',
    tooSweet: 'Too sweet',
    tooWeak: 'Too weak',
    tooExpensive: 'Too expensive',
    premium: 'Premium',
    needsCorrection: 'Needs correction',
    locked: 'Locked',
    pro: 'Pro',
    demo: 'Demo',
  },
  /** Ingredient confidence levels (Masterplan §16). */
  confidence: {
    verified: 'Verified',
    veryHigh: 'Very high confidence',
    high: 'High confidence',
    estimated: 'Estimated',
    needsVerification: 'Needs verification',
  },
  /** Gating + upgrade teaser catalog (Masterplan §6, §10). */
  gate: {
    proLabel: 'PINGÜINO Pro',
    unlockCta: 'Unlock Pro',
    prompts: {
      exactGrams: 'Unlock Pro to see exact correction grams.',
      exactAmount: 'PINGÜINO Pro calculates the exact amount to add.',
      labelExport: 'Label export is available in Pro.',
    },
  },
  landing: {
    eyebrow: 'Gelato Intelligence Platform',
    headline: 'From idea to production-ready gelato.',
    subline:
      'PINGÜINO Intelligence pairs a deterministic recipe engine with AI guidance — taste, structure, serving temperature, cost and production reality, balanced in one workspace.',
    ctaPrimary: 'Start PI Demo',
    ctaSecondary: 'Explore the four modes',
    pillars: [
      {
        title: 'Deterministic engine',
        body: 'Formula-based, reproducible calculations. Same recipe in, same numbers out — always. AI explains; it never replaces the math.',
      },
      {
        title: 'PI Profile Indicators',
        body: 'Structure, sweetness, freezing stability and cost — read at a glance on one laboratory panel while you build.',
      },
      {
        title: 'Exact corrections',
        body: '“Add 34.7 g sucrose and 178.0 g milk 3.5 %.” PINGÜINO Pro tells you precisely how to rebalance — even mid-production.',
      },
    ],
    modesEyebrow: 'Product Modes',
    modesHeadline: 'Four ways to balance a recipe. One engine.',
    modes: [
      {
        name: 'ECO',
        body: 'Lowest cost, technically stable. Built for hotels, buffets and high-volume production.',
      },
      {
        name: 'CLASSIC',
        body: 'The balanced gelato-shop product. Good taste, good cost, reliable structure.',
      },
      {
        name: 'PREMIUM',
        body: 'High flavor intensity. The recipe is rebalanced around the main ingredient — never against it.',
      },
      {
        name: 'SIGNATURE',
        body: 'Maximum perceived flavor, boosters where needed. Technically stable, worthy of your name.',
      },
    ],
  },
  /** AI-first Home (Step 6A) — the clean white first screen. */
  home: {
    eyebrow: 'PINGÜINO Intelligence',
    prompt: 'What are we making today?',
    placeholder: 'Describe a flavor idea…',
    voiceHint: 'Voice coming soon',
    submit: 'Continue',
    restart: 'Start over',
  },
  /** Top-left hamburger menu. */
  menu: {
    title: 'PINGÜINO',
    newRecipe: 'New',
    advancedStudio: 'Advanced Studio',
    soon: 'Soon',
    items: {
      myRecipes: 'My Recipes',
      production: 'Production',
      saved: 'Saved',
    },
    activeEngine: 'Active engine',
    account: 'Account',
    signIn: 'Sign in',
    signOut: 'Sign out',
    signedInAs: 'Signed in',
    authUnavailable: 'Sign-in unavailable in this build',
  },
  /** Auth modal (Phase 2A). */
  auth: {
    titleSignIn: 'Sign in to PINGÜINO',
    titleSignUp: 'Create your PINGÜINO account',
    email: 'Email',
    password: 'Password',
    submitSignIn: 'Sign in',
    submitSignUp: 'Create account',
    busy: 'Working…',
    toSignUp: 'New here? Create an account',
    toSignIn: 'Have an account? Sign in',
    checkEmail: 'Almost there — check your email to confirm your account.',
    unavailable: 'Sign-in is not available in this build yet.',
    close: 'Close',
  },
  /** Guided conversation copy. */
  chat: {
    productQuestion: 'What kind of product is this?',
    servingQuestion: 'Where will it be served?',
    servingPreviewNote: 'Preview — calculations currently use the −11°C Engine.',
    batchQuestion: 'What batch size?',
    batchDefault: 'Keep 1000 g',
    batchScale: 'Scale it',
    batchUnit: 'g',
    summaryEyebrow: 'Demo preview',
    heroLabel: 'Hero flavor',
    heroFallback: 'your idea',
    productLabel: 'Product',
    servingLabel: 'Serving',
    batchLabel: 'Batch',
    processLabel: 'How PINGÜINO builds it',
    process: [
      'Choose the base for this product direction.',
      'Balance sweetness and freezing stability on the −11°C Engine.',
      'Protect the hero flavor — rebalance everything around it.',
    ],
    demoNote: 'This is the approach. Exact grams, scaling and corrections are part of PI Pro.',
    unlockCta: 'Unlock PI Pro for the exact recipe',
    hintsLabel: 'What the −11°C Engine sees',
    balanced: 'Already balanced on the −11°C Engine — the hero leads.',
    areas: {
      sweetness: 'Sweetness',
      freezing_stability: 'Freezing stability',
      texture: 'Texture & body',
      alcohol: 'Alcohol',
      main_ingredient: 'Main ingredient',
      profile_fit: 'Profile fit',
    },
    directions: {
      improve: 'Improve',
      rebalance: 'Rebalance',
      protect: 'Protect',
      reduce_risk: 'Reduce risk',
    },
    confidence: { high: 'High', medium: 'Medium', low: 'Low', tradeoff: 'Trade-off' },
    productHints: {
      gelato: ['Dairy base — we balance fat, lactose and protein for a creamy body.'],
      sorbet: ['The fruit stays the hero.', 'We balance water and sugar for clean scoopability.'],
      granita: ['Kept intentionally icy and crystalline — not creamy.'],
      vegan: ['No animal-derived ingredients — plant-based body and balance.'],
      protein: ['Higher protein lifted while we protect the texture.'],
    },
  },
  /** Product directions (recipe profiles, not engines). */
  productTypes: {
    gelato: { label: 'Gelato', tagline: 'Dairy base — classic and creamy.' },
    sorbet: { label: 'Sorbet', tagline: 'Non-dairy — the fruit is the hero.' },
    granita: { label: 'Granita', tagline: 'Intentionally icy and crystalline.' },
    vegan: { label: 'Vegan', tagline: 'No animal-derived ingredients.' },
    protein: { label: 'Protein', tagline: 'Higher protein, texture preserved.' },
  },
  /** Serving / production profiles (preferences, not engines). */
  servingProfiles: {
    fresh: { label: 'Fresh' },
    'display-minus-11': { label: 'Display −11°C' },
    'display-minus-12': { label: 'Display −12°C' },
    'display-minus-13': { label: 'Display −13°C' },
    'storage-minus-18': { label: 'Storage / Retail −18°C' },
  },
  studio: {
    eyebrow: 'Advanced Studio',
    engineTag: '−11°C Engine',
    back: 'Back to landing',
    presets: {
      label: 'Demo scenarios',
      items: {
        'milk-base': {
          label: 'Milk Base',
          blurb: 'A clean classic base — read the live profile at a glance.',
        },
        'raspberry-premium': {
          label: 'Raspberry Premium',
          blurb: 'We rebalance around the fruit — never against it.',
        },
        'actual-batch-rescue': {
          label: 'Actual Batch Rescue',
          blurb: 'Over-poured mid-production? Rescue the batch by adding, never removing.',
        },
        'jim-beam': {
          label: 'Jim Beam',
          blurb: 'Alcohol shifts freezing — we flag what cannot always be fixed.',
        },
        'pistachio-high-fat': {
          label: 'Pistachio High Fat',
          blurb: 'Rich nut paste protected while the rest rebalances.',
        },
      },
    },
    internalToggle: {
      label: 'Internal preview',
      note: 'Internal preview — not a subscription.',
      demo: 'Demo',
      pro: 'Pro · test',
    },
    goal: {
      title: 'Recipe goal',
      modeLabel: 'Product mode',
      modes: {
        eco: { name: 'ECO', body: 'Lowest cost, technically stable.' },
        classic: { name: 'CLASSIC', body: 'Balanced taste, cost and structure.' },
        premium: { name: 'PREMIUM', body: 'Stronger main ingredient, better mouthfeel.' },
        signature: { name: 'SIGNATURE', body: 'Maximum perceived flavor, kept stable.' },
      },
      modeFocus: { eco: 'Cost', classic: 'Balance', premium: 'Mouthfeel', signature: 'Flavor' },
      categoryLabel: 'Category',
      categories: {
        milk_gelato: 'Milk gelato',
        fruit_gelato: 'Fruit gelato',
        nut_gelato: 'Nut gelato',
        chocolate_gelato: 'Chocolate gelato',
        alcohol_gelato: 'Alcohol gelato',
        sorbet: 'Sorbet',
        vegan_gelato: 'Vegan gelato',
        custom: 'Custom',
      },
      temperatureLabel: 'Serving temperature',
      temperatureHelp: 'Colder serves firmer at the cabinet.',
      batchLabel: 'Batch size',
      machineLabel: 'Machine capacity',
      machineNone: 'No limit',
      machineHelp: 'Optional — warns if a batch will not fit.',
      flavorLabel: 'Flavor intensity',
      flavorOptions: { light: 'Light', balanced: 'Balanced', strong: 'Strong', maximum: 'Maximum' },
      costLabel: 'Cost priority',
      costOptions: { low: 'Low cost', balanced: 'Balanced', premium: 'Premium' },
    },
    overall: {
      eyebrow: 'Overall score',
      modeSuffix: 'mode',
      empty: 'Add ingredients to score the recipe.',
    },
    builder: {
      title: 'Ingredients',
      addLabel: 'Add ingredient',
      planned: 'Planned',
      actual: 'Actual',
      share: 'Share',
      lock: 'Lock',
      mark_main: 'Set as main',
      main_short: 'Main',
      remove: 'Remove',
      unit: 'g',
      batchTotal: 'Batch total',
      target: 'Target',
      ingredientGroups: {
        sugar: 'Sugars',
        dairy: 'Dairy',
        fat: 'Fats',
        fruit: 'Fruit',
        nut_paste: 'Nut pastes',
        chocolate_cocoa: 'Chocolate & cocoa',
        stabilizer: 'Stabilizers',
        flavor: 'Flavor',
        alcohol: 'Alcohol',
        water: 'Water',
        egg: 'Egg',
        other: 'Other',
      },
      empty: 'Add ingredients to begin — the PI panel updates live.',
      lockTypes: {
        unlocked: 'Unlocked',
        grams: 'Locked · grams',
        percent: 'Locked · %',
        main: 'Main ingredient',
        already_added: 'Already added',
        required: 'Required',
      },
    },
    pi: {
      title: 'PI Profile Indicators',
      note: 'Live values from the deterministic engine.',
      calibration: 'Calibration',
      groups: {
        freezing: 'Freezing & structure',
        balance: 'Balance',
        risk: 'Risk',
      },
      fallbackCategory:
        'Targets estimated from milk-gelato bands — calibration pending for this category.',
      fallbackTemperature: 'Targets approximated from the nearest calibrated temperature.',
      indicators: {
        pod: 'Sweetness · POD',
        npac: 'Freezing stability · NPAC',
        ice_fraction: 'Structure · Ice fraction',
        water: 'Water balance',
        total_solids: 'Total solids',
        fat: 'Fat balance',
        aerating_protein: 'Aerating protein',
        protein_in_solids: 'Protein in solids',
        lactose: 'Lactose',
        lactose_sandiness_risk: 'Sandiness risk',
        alcohol: 'Alcohol',
      },
    },
    warnings: {
      alcohol_above_safe_range: 'Alcohol is above the stable range for this gelato.',
      machine_capacity_exceeded: 'Batch exceeds the machine capacity.',
      batch_mass_mismatch: 'Batch mass differs from the target.',
      composition_invalid: 'An ingredient composition looks inconsistent.',
      low_confidence_ingredient: 'Some ingredient values are estimated, not verified.',
      cost_incomplete: 'Cost is incomplete — some ingredient prices are unknown.',
    },
    metrics: {
      title: 'Nutrition · Cost',
      nutritionTitle: 'Per 100 g',
      kcal: 'Energy',
      fat: 'Fat',
      saturated: 'of which saturated',
      carbs: 'Carbohydrate',
      sugars: 'of which sugars',
      protein: 'Protein',
      salt: 'Salt',
      fiber: 'Fibre',
      alcohol: 'Alcohol',
      unavailable: 'Add ingredients to see values.',
      costTitle: 'Cost',
      costPerKg: 'Per kg',
      serving60: 'Per 60 g',
      serving70: 'Per 70 g',
      serving80: 'Per 80 g',
      costIncomplete: 'Add ingredient prices for a complete cost.',
      scoreTitle: 'Scores',
      technical: 'Technical',
      flavor: 'Flavor',
      cost: 'Cost',
      overall: 'Overall',
      scoreUnavailable: '—',
    },
    corrections: {
      title: 'Corrections',
      none: 'Balanced — no corrections needed.',
      demoPreviewNote: 'Demo preview — exact grams hidden.',
      demoDirections: {
        add: 'Add a balancing ingredient',
        reduce: 'Reduce an ingredient',
        rebalance: 'Rebalance the mix',
      },
      demoArea: 'Suggested area',
      add: 'Add',
      reduce: 'Reduce',
      before: 'Now',
      after: 'After',
      confidenceLabel: 'Confidence',
      tradeoffTitle: 'Trade-off',
      impossibleTitle: 'Cannot fully balance',
      blocking: {
        locked_ingredient: 'A locked ingredient is the main cause — unlock it to allow a fix.',
        already_added:
          'An already-added ingredient is the cause — it cannot be reduced, so rebalance by adding.',
        main_ingredient_floor:
          'Fixing this would reduce the main ingredient below its floor — protected in this mode.',
        machine_capacity: 'A fix would exceed the machine capacity.',
        no_candidate: 'No suitable correction is available with the current ingredients.',
      },
      confidence: { high: 'High', medium: 'Medium', low: 'Low', tradeoff: 'Trade-off' },
    },
  },
  notFound: {
    code: '404',
    headline: 'This page does not exist.',
    back: 'Back to landing',
  },
  footer: {
    line: 'PINGÜINO Intelligence — precision gelato intelligence.',
  },
} as const;
