/**
 * All user-facing copy lives here (typed, English-only MVP).
 * Centralized for later i18n extraction — never hardcode strings in components.
 */
export const copy = {
  brand: {
    name: 'PINGÜINO',
    sub: 'INTELLIGENCE',
    full: 'PINGÜINO Intelligence',
  },
  /** PI status vocabulary (Masterplan §12.7 — full engine set + UI chip states). */
  status: {
    ideal: 'Ideal',
    good: 'Good',
    risky: 'Risky',
    tooSoft: 'Too soft',
    tooHard: 'Too hard',
    tooSweet: 'Too sweet',
    tooWeak: 'Too weak',
    tooExpensive: 'Too expensive',
    premium: 'Premium',
    needsCorrection: 'Needs correction',
    locked: 'Locked',
    pro: 'Pro',
    // Customer-facing tier chip — never "Demo" (Phase 6C rebrand).
    demo: 'Free Preview',
  },
  /** Ingredient confidence levels (Masterplan §16). */
  confidence: {
    verified: 'Verified',
    veryHigh: 'Very high confidence',
    high: 'High confidence',
    estimated: 'Estimated',
    needsVerification: 'Needs verification',
  },
  /** Gating + upgrade teaser catalog (Masterplan §6, §10). */
  gate: {
    proLabel: 'PI Pro',
    unlockCta: 'Unlock PI Pro',
    prompts: {
      exactGrams: 'Unlock Pro to see exact correction grams.',
      exactAmount: 'PINGÜINO Pro calculates the exact amount to add.',
      labelExport: 'Label export is available in Pro.',
    },
  },
  landing: {
    eyebrow: 'Gelato Intelligence Platform',
    headline: 'From idea to production-ready gelato.',
    subline:
      'PINGÜINO Intelligence pairs a deterministic recipe engine with AI guidance — taste, structure, serving temperature, cost and production reality, balanced in one workspace.',
    ctaPrimary: 'Start Free Preview',
    ctaSecondary: 'Explore the four modes',
    pillars: [
      {
        title: 'Deterministic engine',
        body: 'Formula-based, reproducible calculations. Same recipe in, same numbers out — always. AI explains; it never replaces the math.',
      },
      {
        title: 'PI Profile Indicators',
        body: 'Structure, sweetness, freezing stability and cost — read at a glance on one laboratory panel while you build.',
      },
      {
        title: 'Exact corrections',
        body: '“Add 34.7 g sucrose and 178.0 g milk 3.5 %.” PINGÜINO Pro tells you precisely how to rebalance — even mid-production.',
      },
    ],
    modesEyebrow: 'Product Modes',
    modesHeadline: 'Four ways to balance a recipe. One engine.',
    modes: [
      {
        name: 'ECO',
        body: 'Lowest cost, technically stable. Built for hotels, buffets and high-volume production.',
      },
      {
        name: 'CLASSIC',
        body: 'The balanced gelato-shop product. Good taste, good cost, reliable structure.',
      },
      {
        name: 'PREMIUM',
        body: 'High flavor intensity. The recipe is rebalanced around the main ingredient — never against it.',
      },
      {
        name: 'SIGNATURE',
        body: 'Maximum perceived flavor, boosters where needed. Technically stable, worthy of your name.',
      },
    ],
  },
  /** AI-first Home (Step 6A) — the clean white first screen. */
  home: {
    eyebrow: 'PINGÜINO Intelligence',
    prompt: 'What are we making today?',
    placeholder: 'Describe a flavor idea…',
    voiceHint: 'Voice coming soon',
    submit: 'Continue',
    restart: 'Start over',
  },
  /** Top-left hamburger menu. */
  menu: {
    title: 'PINGÜINO',
    newRecipe: 'New',
    advancedStudio: 'Advanced Studio',
    soon: 'Soon',
    items: {
      myRecipes: 'My Recipes',
      production: 'Production',
      saved: 'Saved',
    },
    activeEngine: 'Active engine',
    account: 'Account',
    signIn: 'Sign in',
    signOut: 'Sign out',
    signedInAs: 'Signed in',
    authUnavailable: 'Sign-in unavailable in this build',
  },
  /**
   * Top navigation — the premium black shell + Tesla-style mega menus (Phase 6C).
   * Eight centered top-level items; each menu has its own size/layout (see navConfig).
   * Customer-facing — never "Demo": use "Free Preview" / "PI Preview" / "Unlock PI Pro".
   */
  nav: {
    skipToContent: 'Skip to content',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    account: 'Account',
    signIn: 'Sign in',
    signOut: 'Sign out',
    previewTier: 'Free Preview',
    previewExperience: 'PI Preview',
    unlockPro: 'Unlock PI Pro',
    comingSoon: 'Coming soon',
    learnMore: 'Learn more',
    engineLabel: '−11°C Engine',
    /** Top-level labels — order is the source of truth in navConfig. */
    items: {
      start: 'Start',
      calculator: 'PI Calculator',
      recipes: 'Recipes',
      label: 'Create Label',
      api: 'API',
      work: 'Work With Us',
      subscription: 'Subscription',
      ingredient: 'Create Ingredient',
    },
    start: {
      blurb: 'Back to the AI talking space.',
      talk: 'Return to PI',
      new: 'Start a new recipe',
      continue: 'Continue last recipe',
      how: 'How PI Preview works',
    },
    calculator: {
      title: 'PI Calculator',
      blurb: 'Build and balance on the deterministic engine.',
      manual: 'Manual PI Calculator',
      studio: 'Advanced Studio',
      builder: 'Ingredient builder',
      panel: 'PI indicator panel',
      rescue: 'Production rescue',
      engineNote: 'Active engine',
    },
    recipes: {
      title: 'Recipes',
      blurb: 'Start from a balanced base.',
      mine: 'My Recipes',
      pinguino: 'PINGÜINO Recipes',
      featured: 'Featured Recipes',
      recent: 'Recently Added',
      gelato: 'Gelato',
      sorbet: 'Sorbet',
      vegan: 'Vegan',
      protein: 'Protein',
      startFrom: 'Start from a recipe',
      browse: 'Browse',
      categories: 'Categories',
      note: 'Curated PINGÜINO recipes and your saved work, all balanced on the −11°C Engine.',
    },
    label: {
      title: 'Create Label',
      blurb: 'Compliant labels from your recipe.',
      nutrition: 'Nutrition label',
      production: 'Production label',
      statement: 'Ingredient statement',
      allergen: 'Allergen information',
      export: 'Export / print',
      note: 'An EU nutrition declaration, ingredient statement and cost breakdown, generated from your recipe. Export the recipe as CSV or print the label — all in your browser.',
      /** Standalone label page (Labels & Exports) — reads a fixed sample recipe. */
      sampleHeading: 'Sample recipe',
      sampleNote: 'The values below come straight from the −11°C Engine for a balanced sample recipe. Build your own in the calculator to label it.',
      declarationTitle: 'Nutrition declaration',
      statementNote: 'Ingredients in descending order of weight (EU QUID).',
      notAvailable: 'Not available',
      downloadCsv: 'Download CSV',
      print: 'Print label',
      csvFilename: 'pinguino-sample-label.csv',
      allergenNote:
        'Allergen information is not generated automatically — the engine holds no allergen data. Check allergens against your ingredient labels before publishing.',
    },
    api: {
      title: 'API',
      blurb: 'Bring PINGÜINO intelligence into your stack.',
      overview: 'API overview',
      shops: 'API for gelato shops',
      machines: 'API for machines',
      partner: 'Partner access',
      docs: 'Documentation',
      status: 'Integration status',
      note: 'Programmatic access for gelato shops and machines, plus partner integrations. Documentation lands as the API opens.',
    },
    work: {
      title: 'Work With Us',
      blurb: 'Four ways to bring PINGÜINO into your shop.',
      includedLabel: 'What’s included',
      forWhomLabel: 'Who it’s for',
      cta: 'Talk to PINGÜINO',
      ctaHref: 'mailto:pinguinointelligence@gmail.com',
      offers: {
        app: {
          title: 'App only',
          body: 'PINGÜINO Intelligence for your team — recipes, balance and corrections.',
          included: 'Recipe design, live PI Profile Indicators, AI guidance, cost and nutrition per recipe.',
          forWhom: 'Gelato shops and recipe developers who want the full workspace.',
        },
        machinesApp: {
          title: 'Machines + App',
          body: 'Production machines paired with the app for end-to-end control.',
          included: 'Everything in App only, plus connected production machines for end-to-end control.',
          forWhom: 'Production-focused makers upgrading to connected hardware.',
        },
        machineMixtures: {
          title: 'Machine + ready mixtures',
          body: 'A machine plus ready-to-run mixtures formulated by PINGÜINO.',
          included: 'A production machine and ready-to-run mixtures formulated by PINGÜINO.',
          forWhom: 'New shops and turnkey setups that want calibrated products from day one.',
        },
        ingredients: {
          title: 'Ingredients / powder packs',
          body: 'Calibrated ingredient and powder packs for consistent results.',
          included: 'Curated ingredient and powder packs with consistent, calibrated sourcing.',
          forWhom: 'High-volume producers and franchises that need standardised results.',
        },
      },
    },
    subscription: {
      title: 'Subscription',
      blurb: 'Preview free — unlock the full engine with PI Pro.',
      free: 'Free Preview',
      pro: 'PI Pro',
      team: 'Shop / Team plan',
      manage: 'Manage billing',
      change: 'Change / cancel billing',
      freeTagline: 'Explore PINGÜINO, free.',
      proTagline: 'The full engine, unlocked.',
      freeCta: 'Start Free Preview',
      comingSoonNote: 'Billing and checkout arrive in a later release.',
      whatUnlocks: 'PI Pro unlocks the full workspace.',
      futureLabel: 'On the roadmap',
      freeFeatures: [
        'PI Preview — directional engine guidance',
        'Profile indicators, read-only',
        'No exact grams',
        'No PI Base ingredient library',
        'No exact corrections',
      ],
      proFeatures: [
        'Exact grams',
        'Full calculator',
        'Full PI panel',
        'PI Base ingredient library',
        'Exact corrections',
        'Saved recipes',
        'Production rescue (coming soon)',
      ],
    },
    ingredient: {
      title: 'Create Ingredient',
      blurb: 'Add your own ingredient from a description or a label photo.',
      describe: 'Describe product',
      photo: 'Add food label photo',
      camera: 'Take picture',
      review: 'Review extracted data',
      add: 'Add to ingredients',
      note: 'Build a custom ingredient from a description or a food-label photo. Capture and extraction arrive with PI Pro.',
    },
  },
  /** Reusable placeholder surface for not-yet-built nav destinations (Phase 6C, Slice 1). */
  comingSoon: {
    eyebrow: 'Coming soon',
    headline: 'In the works.',
    body: 'This space is part of the PINGÜINO roadmap. The navigation is live — the destination lands in a later release.',
    back: 'Back to home',
  },
  /** Auth modal (Phase 2A). */
  auth: {
    titleSignIn: 'Sign in to PINGÜINO',
    titleSignUp: 'Create your PINGÜINO account',
    email: 'Email',
    password: 'Password',
    submitSignIn: 'Sign in',
    submitSignUp: 'Create account',
    busy: 'Working…',
    toSignUp: 'New here? Create an account',
    toSignIn: 'Have an account? Sign in',
    checkEmail: 'Almost there — check your email to confirm your account.',
    unavailable: 'Sign-in is not available in this build yet.',
    close: 'Close',
  },
  /** Saved recipes + My Recipes (Phase 2A.2). */
  recipes: {
    save: 'Save recipe',
    saveAs: 'Save as new',
    saveTitle: 'Save recipe',
    nameLabel: 'Recipe name',
    namePlaceholder: 'e.g. House Milk Base',
    descriptionLabel: 'Notes (optional)',
    saving: 'Saving…',
    cancel: 'Cancel',
    signInToSave: 'Sign in to save',
    title: 'My Recipes',
    empty: 'No saved recipes yet — build one in Advanced Studio and save it.',
    signInToView: 'Sign in to see your saved recipes.',
    unavailable: 'Saving is not available in this build.',
    open: 'Open',
    delete: 'Delete',
    confirmDelete: 'Delete this recipe? This cannot be undone.',
    loading: 'Loading…',
    back: 'Back to home',
    columns: {
      product: 'Product',
      serving: 'Serving',
      engine: 'Engine',
      batch: 'Batch',
      updated: 'Updated',
    },
  },
  /** PRO CORE — real recipe-version / production / cost surfaces (orchestrator integration). */
  proCore: {
    title: 'Recipe versions',
    blurb:
      'Save the current Studio draft as a Pro recipe, keep an immutable version history, compare versions and restore an older one as a new latest version.',
    devPersona: 'Persona (dev):',
    backendUnavailable: 'Recipe versions need a configured backend. Not available in this build.',
    localMode:
      'Local dev mode — versions are kept in memory only and are not durable (a reload clears them).',
    demoCannotSave: 'This plan cannot save recipe versions.',
    saveDraftAsRecipe: 'Save current draft as recipe',
    saveNewVersion: 'Save new version',
    restoreV1: 'Restore v1 → new version',
    recipesHeading: 'Recipes',
    historyHeading: 'Version history',
    noRecipes: 'No Pro recipes yet — save the current Studio draft to start a version history.',
    selectRecipe: 'Select a recipe to see its versions.',
    archived: 'archived',
    fromVersion: 'from',
    draftTitlePrefix: 'Studio draft',
  },
  /** PI Pro subscription / billing (Phase 2B.1 — checkout wired in a later slice). */
  billing: {
    proActive: 'PI Pro active',
    upgrade: 'Upgrade to PI Pro',
    comingSoon: 'Coming soon',
  },
  /** Guided conversation copy. */
  chat: {
    productQuestion: 'What kind of product is this?',
    servingQuestion: 'Where will it be served?',
    servingPreviewNote: 'Preview — calculations currently use the −11°C Engine.',
    batchQuestion: 'What batch size?',
    batchDefault: 'Keep 1000 g',
    batchScale: 'Scale it',
    batchUnit: 'g',
    summaryEyebrow: 'PI Preview',
    heroLabel: 'Hero flavor',
    heroFallback: 'your idea',
    productLabel: 'Product',
    servingLabel: 'Serving',
    batchLabel: 'Batch',
    processLabel: 'How PINGÜINO builds it',
    process: [
      'Choose the base for this product direction.',
      'Balance sweetness and freezing stability on the −11°C Engine.',
      'Protect the hero flavor — rebalance everything around it.',
    ],
    demoNote: 'This is the approach. Exact grams, scaling and corrections are part of PI Pro.',
    unlockCta: 'Unlock PI Pro for the exact recipe',
    hintsLabel: 'What the −11°C Engine sees',
    balanced: 'Already balanced on the −11°C Engine — the hero leads.',
    areas: {
      sweetness: 'Sweetness',
      freezing_stability: 'Freezing stability',
      texture: 'Texture & body',
      alcohol: 'Alcohol',
      main_ingredient: 'Main ingredient',
      profile_fit: 'Profile fit',
    },
    directions: {
      improve: 'Improve',
      rebalance: 'Rebalance',
      protect: 'Protect',
      reduce_risk: 'Reduce risk',
    },
    confidence: { high: 'High', medium: 'Medium', low: 'Low', tradeoff: 'Trade-off' },
    productHints: {
      gelato: ['Dairy base — we balance fat, lactose and protein for a creamy body.'],
      sorbet: ['The fruit stays the hero.', 'We balance water and sugar for clean scoopability.'],
      granita: ['Kept intentionally icy and crystalline — not creamy.'],
      vegan: ['No animal-derived ingredients — plant-based body and balance.'],
      protein: ['Higher protein lifted while we protect the texture.'],
    },
  },
  /** Product directions (recipe profiles, not engines). */
  productTypes: {
    gelato: { label: 'Gelato', tagline: 'Dairy base — classic and creamy.' },
    sorbet: { label: 'Sorbet', tagline: 'Non-dairy — the fruit is the hero.' },
    granita: { label: 'Granita', tagline: 'Intentionally icy and crystalline.' },
    vegan: { label: 'Vegan', tagline: 'No animal-derived ingredients.' },
    protein: { label: 'Protein', tagline: 'Higher protein, texture preserved.' },
  },
  /** Serving / production profiles (preferences, not engines). */
  servingProfiles: {
    fresh: { label: 'Fresh' },
    'display-minus-11': { label: 'Display −11°C' },
    'display-minus-12': { label: 'Display −12°C' },
    'display-minus-13': { label: 'Display −13°C' },
    'storage-minus-18': { label: 'Storage / Retail −18°C' },
  },
  studio: {
    eyebrow: 'Advanced Studio',
    engineTag: '−11°C Engine',
    back: 'Back to landing',
    /** Locked Free Preview panels (Phase 6C Slice 2B) — decorative, no exact values. */
    locked: {
      chip: 'PI Preview',
      note: 'Exact values are part of PI Pro.',
      cta: 'Unlock PI Pro for exact grams, full calculator and production rescue.',
    },
    presets: {
      label: 'Demo scenarios',
      items: {
        'milk-base': {
          label: 'Milk Base',
          blurb: 'A clean classic base — read the live profile at a glance.',
        },
        'raspberry-premium': {
          label: 'Raspberry Premium',
          blurb: 'We rebalance around the fruit — never against it.',
        },
        'actual-batch-rescue': {
          label: 'Actual Batch Rescue',
          blurb: 'Over-poured mid-production? Rescue the batch by adding, never removing.',
        },
        'jim-beam': {
          label: 'Jim Beam',
          blurb: 'Alcohol shifts freezing — we flag what cannot always be fixed.',
        },
        'pistachio-high-fat': {
          label: 'Pistachio High Fat',
          blurb: 'Rich nut paste protected while the rest rebalances.',
        },
      },
    },
    internalToggle: {
      label: 'Internal preview',
      note: 'Internal preview — not a subscription.',
      demo: 'Demo',
      pro: 'Pro · test',
    },
    goal: {
      title: 'Recipe goal',
      modeLabel: 'Product mode',
      modes: {
        eco: { name: 'ECO', body: 'Lowest cost, technically stable.' },
        classic: { name: 'CLASSIC', body: 'Balanced taste, cost and structure.' },
        premium: { name: 'PREMIUM', body: 'Stronger main ingredient, better mouthfeel.' },
        signature: { name: 'SIGNATURE', body: 'Maximum perceived flavor, kept stable.' },
      },
      modeFocus: { eco: 'Cost', classic: 'Balance', premium: 'Mouthfeel', signature: 'Flavor' },
      categoryLabel: 'Category',
      categories: {
        milk_gelato: 'Milk gelato',
        fruit_gelato: 'Fruit gelato',
        nut_gelato: 'Nut gelato',
        chocolate_gelato: 'Chocolate gelato',
        alcohol_gelato: 'Alcohol gelato',
        sorbet: 'Sorbet',
        vegan_gelato: 'Vegan gelato',
        custom: 'Custom',
      },
      temperatureLabel: 'Serving temperature',
      temperatureHelp: 'Colder serves firmer at the cabinet.',
      batchLabel: 'Batch size',
      machineLabel: 'Machine capacity',
      machineNone: 'No limit',
      machineHelp: 'Optional — warns if a batch will not fit.',
      flavorLabel: 'Flavor intensity',
      flavorOptions: { light: 'Light', balanced: 'Balanced', strong: 'Strong', maximum: 'Maximum' },
      costLabel: 'Cost priority',
      costOptions: { low: 'Low cost', balanced: 'Balanced', premium: 'Premium' },
    },
    overall: {
      eyebrow: 'Overall score',
      modeSuffix: 'mode',
      empty: 'Add ingredients to score the recipe.',
    },
    builder: {
      title: 'Ingredients',
      addLabel: 'Add ingredient',
      searchLabel: 'Search ingredients',
      searchPlaceholder: 'Search ingredients, category, brand or ID…',
      noMatches: 'No ingredient found. Try another name or category.',
      resultUnitOne: 'ingredient',
      resultUnitMany: 'ingredients',
      resultFoundSuffix: 'found',
      loadingLibrary: 'Loading PI Base library…',
      fallbackNote: 'PI Base library unavailable — showing preview ingredients.',
      planned: 'Planned',
      actual: 'Actual',
      share: 'Share',
      lock: 'Lock',
      mark_main: 'Set as main',
      main_short: 'Main',
      remove: 'Remove',
      unit: 'g',
      batchTotal: 'Batch total',
      target: 'Target',
      ingredientGroups: {
        sugar: 'Sugars',
        dairy: 'Dairy',
        fat: 'Fats',
        fruit: 'Fruit',
        nut_paste: 'Nut pastes',
        chocolate_cocoa: 'Chocolate & cocoa',
        stabilizer: 'Stabilizers',
        flavor: 'Flavor',
        alcohol: 'Alcohol',
        water: 'Water',
        egg: 'Egg',
        other: 'Other',
      },
      empty: 'Add ingredients to begin — the PI panel updates live.',
      lockTypes: {
        unlocked: 'Unlocked',
        grams: 'Locked · grams',
        percent: 'Locked · %',
        main: 'Main ingredient',
        already_added: 'Already added',
        required: 'Required',
      },
    },
    pi: {
      title: 'PI Profile Indicators',
      note: 'Live values from the deterministic engine.',
      calibration: 'Calibration',
      groups: {
        freezing: 'Freezing & structure',
        balance: 'Balance',
        risk: 'Risk',
      },
      fallbackCategory:
        'Targets estimated from milk-gelato bands — calibration pending for this category.',
      fallbackTemperature: 'Targets approximated from the nearest calibrated temperature.',
      indicators: {
        pod: 'Sweetness · POD',
        npac: 'Freezing stability · NPAC',
        ice_fraction: 'Structure · Ice fraction',
        water: 'Water balance',
        total_solids: 'Total solids',
        fat: 'Fat balance',
        aerating_protein: 'Aerating protein',
        protein_in_solids: 'Protein in solids',
        lactose: 'Lactose',
        lactose_sandiness_risk: 'Sandiness risk',
        alcohol: 'Alcohol',
      },
    },
    warnings: {
      alcohol_above_safe_range: 'Alcohol is above the stable range for this gelato.',
      machine_capacity_exceeded: 'Batch exceeds the machine capacity.',
      batch_mass_mismatch: 'Batch mass differs from the target.',
      composition_invalid: 'An ingredient composition looks inconsistent.',
      low_confidence_ingredient: 'Some ingredient values are estimated, not verified.',
      cost_incomplete: 'Cost is incomplete — some ingredient prices are unknown.',
    },
    metrics: {
      title: 'Nutrition · Cost',
      nutritionTitle: 'Per 100 g',
      kcal: 'Energy',
      fat: 'Fat',
      saturated: 'of which saturated',
      carbs: 'Carbohydrate',
      sugars: 'of which sugars',
      protein: 'Protein',
      salt: 'Salt',
      fiber: 'Fibre',
      alcohol: 'Alcohol',
      unavailable: 'Add ingredients to see values.',
      costTitle: 'Cost',
      costPerKg: 'Per kg',
      serving60: 'Per 60 g',
      serving70: 'Per 70 g',
      serving80: 'Per 80 g',
      costIncomplete: 'Add ingredient prices for a complete cost.',
      scoreTitle: 'Scores',
      technical: 'Technical',
      flavor: 'Flavor',
      cost: 'Cost',
      overall: 'Overall',
      scoreUnavailable: '—',
    },
    corrections: {
      title: 'Corrections',
      none: 'Balanced — no corrections needed.',
      demoPreviewNote: 'PI Preview — exact grams hidden.',
      demoDirections: {
        add: 'Add a balancing ingredient',
        reduce: 'Reduce an ingredient',
        rebalance: 'Rebalance the mix',
      },
      demoArea: 'Suggested area',
      add: 'Add',
      reduce: 'Reduce',
      before: 'Now',
      after: 'After',
      confidenceLabel: 'Confidence',
      tradeoffTitle: 'Trade-off',
      impossibleTitle: 'Cannot fully balance',
      blocking: {
        locked_ingredient: 'A locked ingredient is the main cause — unlock it to allow a fix.',
        already_added:
          'An already-added ingredient is the cause — it cannot be reduced, so rebalance by adding.',
        main_ingredient_floor:
          'Fixing this would reduce the main ingredient below its floor — protected in this mode.',
        machine_capacity: 'A fix would exceed the machine capacity.',
        no_candidate: 'No suitable correction is available with the current ingredients.',
      },
      confidence: { high: 'High', medium: 'Medium', low: 'Low', tradeoff: 'Trade-off' },
    },
  },
  /**
   * Product catalog intake — the unified CSV upload UI (Mapper Slice D5C4). ONE flow
   * for every source (generic / Mercadona / Colin); the selector only stamps
   * source_type, there is no separate Colin system. Customer-facing — never "Demo".
   */
  productsImport: {
    eyebrow: 'Product Intake',
    title: 'Import product catalog',
    blurb:
      'Upload or paste a CSV catalog and turn rows into product records in the shared products layer.',
    sourceLabel: 'Catalog source',
    sources: {
      generic: 'Generic catalog',
      mercadona: 'Mercadona catalog',
      colin: 'Colin / internal catalog',
    },
    inputLabel: 'Paste or upload CSV',
    pastePlaceholder: 'Paste CSV rows here — the first line is the header…',
    fileLabel: 'Choose a .csv file',
    parse: 'Parse CSV',
    import: 'Import products',
    signIn: 'Sign in to import',
    signInNote: 'Parsing is open — sign in to import rows into the products layer.',
    unavailable: 'Importing is not available in this build.',
    previewLabel: 'Parse preview',
    warningsLabel: 'Warnings',
    skippedLabel: 'Skipped rows',
    resultLabel: 'Import result',
    rowResultsLabel: 'Row results',
    emptyPreview: 'Paste or upload a CSV, then Parse to preview the rows.',
    noWarnings: 'No warnings.',
    noSkipped: 'No skipped rows.',
    codesCreated: 'Product codes assigned',
    importError: 'Import could not complete.',
    counts: {
      total: 'Total rows',
      valid: 'Valid',
      warnings: 'Warnings',
      skipped: 'Skipped',
      created: 'Created',
      existing: 'Existing duplicates',
      inBatch: 'In-batch duplicates',
      failed: 'Failed',
    },
    outcomes: {
      created: 'Created',
      existing: 'Existing',
      in_batch_duplicate: 'In-batch duplicate',
      skipped: 'Skipped',
      failed: 'Failed',
    },
  },
  notFound: {
    code: '404',
    headline: 'This page does not exist.',
    back: 'Back to landing',
  },
  footer: {
    line: 'PINGÜINO Intelligence — precision gelato intelligence.',
  },
} as const;
