/**
 * AGENT 2 — ENGINE AUTHENTICITY drift detectors (owner tests T1–T20).
 *
 * Pins what `buildOptimizePreview` + `calculateRecipe` ACTUALLY return today
 * (staging nightly/integration) for the owner's 20 offline tests — any future
 * formula/config/template change that shifts a verdict, a score, an iteration
 * count or a 4-decimal metric fails here first. These are DRIFT DETECTORS and
 * authenticity proofs, not judgments of scientific correctness; no engine
 * value is changed by this suite.
 *
 * Full structured results live in docs/engine-validation/
 * ENGINE_AUTHENTICITY_TESTS.{json,csv} (regenerated by the artifacts test) and
 * docs/engine-validation/AGENT2_ENGINE_AUTHENTICITY_LEDGER.md.
 */
import { beforeAll, describe, expect, it } from 'vitest';
import type { EngineIngredient, RecipeInput } from '@/engine';
import { findDemoIngredient } from '@/data/demoIngredients';
import { useRecipeStore } from '@/stores/recipeStore';
import { buildRecipeInput } from '@/features/studio/buildRecipeInput';
import { useConstraintStudioStore } from '@/features/constraint-studio/constraintStudioStore';
import {
  AUTHENTICITY_CASES,
  engineHasStabilizerMetric,
  runAllAuthenticityCases,
  runDeterminismBattery,
  type AuthenticityRecord,
} from './authenticityCases';

/* ── one shared battery run (the runner is pure and deterministic) ─────────── */

let records: AuthenticityRecord[] = [];
const byId = (id: string): AuthenticityRecord => {
  const found = records.find((record) => record.testId === id);
  if (!found) throw new Error(`missing record ${id}`);
  return found;
};

beforeAll(() => {
  records = runAllAuthenticityCases();
});

/* ── the pinned outcome table (observed 2026-07-24, ENGINE 0.4.0 / CONFIG 0.7.0) ── */

interface Pin {
  id: string;
  verdict: AuthenticityRecord['verdict'];
  outcome: string;
  ten: number | null;
  overall: number | null;
  iter: number | null;
  stop: string;
  npac: number | null;
  ice: number | null;
  pod: number | null;
  viol: number;
  hardSafe: boolean;
  batch: number;
}

const PINS: Pin[] = [
  { id: 'T1', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 9, overall: 85.4404, iter: 2, stop: 'fixed_point_no_proposal', npac: 36.9081, ice: 50.3748, pod: 14.1499, viol: 1, hardSafe: true, batch: 1000 },
  { id: 'T2', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 9, overall: 86.6823, iter: 1, stop: 'all_bands_in_range', npac: 36.4926, ice: 50.8133, pod: 14.7724, viol: 0, hardSafe: true, batch: 1000 },
  { id: 'T3', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 8, overall: 83.2104, iter: 1, stop: 'no_improving_move', npac: 39.24, ice: 47.9134, pod: 16.8284, viol: 1, hardSafe: true, batch: 1000 },
  { id: 'T4', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 8, overall: 76.3612, iter: 1, stop: 'no_improving_move', npac: 34.0578, ice: 53.3835, pod: 15.2134, viol: 4, hardSafe: true, batch: 1000 },
  { id: 'T5', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 7, overall: 73.7782, iter: 3, stop: 'fixed_point_no_proposal', npac: 37.1273, ice: 50.1434, pod: 13.6733, viol: 5, hardSafe: true, batch: 1000 },
  { id: 'T6', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 7, overall: 68.4243, iter: 3, stop: 'fixed_point_no_proposal', npac: 34.4739, ice: 52.9442, pod: 12.4016, viol: 5, hardSafe: true, batch: 1000 },
  { id: 'T7', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 7, overall: 69.09, iter: 2, stop: 'no_improving_move', npac: 38.5686, ice: 48.6221, pod: 14.4442, viol: 7, hardSafe: true, batch: 1000 },
  { id: 'T8', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 6, overall: 64.3631, iter: 2, stop: 'fixed_point_no_proposal', npac: 33.6056, ice: 53.8608, pod: 12.7948, viol: 7, hardSafe: true, batch: 1000 },
  { id: 'T9', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 5, overall: 53.8735, iter: 12, stop: 'iteration_cap', npac: 31.897, ice: 55.6643, pod: 11.8586, viol: 10, hardSafe: true, batch: 1000 },
  { id: 'T10', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 8, overall: 82.1399, iter: 1, stop: 'fixed_point_no_proposal', npac: 36.6001, ice: 50.6999, pod: 16.0209, viol: 1, hardSafe: true, batch: 1000 },
  { id: 'T11', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 8, overall: 81.777, iter: 2, stop: 'no_improving_move', npac: 40.8515, ice: 46.2124, pod: 15.2472, viol: 2, hardSafe: true, batch: 1000 },
  { id: 'T12', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 8, overall: 81.777, iter: 2, stop: 'no_improving_move', npac: 40.8515, ice: 46.2124, pod: 15.2472, viol: 2, hardSafe: true, batch: 1000 },
  { id: 'T13', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 8, overall: 82.1399, iter: 1, stop: 'fixed_point_no_proposal', npac: 36.6001, ice: 50.6999, pod: 16.0209, viol: 1, hardSafe: true, batch: 1000 },
  { id: 'T14', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 7, overall: 70.8265, iter: 1, stop: 'fixed_point_no_proposal', npac: 36.6327, ice: 50.6655, pod: 18.8193, viol: 1, hardSafe: false, batch: 1000 },
  { id: 'T15', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 7, overall: 72.6138, iter: 4, stop: 'fixed_point_no_proposal', npac: 34.6228, ice: 52.787, pod: 12.5526, viol: 5, hardSafe: true, batch: 1000 },
  { id: 'T16', verdict: 'HONEST-IMPOSSIBLE', outcome: 'missing_required_role', ten: null, overall: null, iter: null, stop: 'missing_required_role', npac: null, ice: null, pod: null, viol: 0, hardSafe: true, batch: 0 },
  { id: 'T17', verdict: 'AUTHENTIC-OPTIMAL', outcome: 'preview', ten: 9, overall: 88.1667, iter: 0, stop: 'all_bands_in_range', npac: 47.4851, ice: 50.3291, pod: 14.9362, viol: 0, hardSafe: true, batch: 1000 },
  { id: 'T18', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 9, overall: 86.1457, iter: 1, stop: 'fixed_point_no_proposal', npac: 54.7373, ice: 49.644, pod: 15.7262, viol: 1, hardSafe: false, batch: 1000 },
  { id: 'T19', verdict: 'AUTHENTIC-BEST-ACHIEVABLE', outcome: 'preview', ten: 7, overall: 71.0051, iter: 1, stop: 'fixed_point_no_proposal', npac: 36.4884, ice: 50.8178, pod: 17.7759, viol: 1, hardSafe: false, batch: 1000 },
];

describe('T1–T19 — pinned engine outcomes (drift detectors)', () => {
  it('runs exactly the 19 direct cases (+ T20 battery separately)', () => {
    expect(AUTHENTICITY_CASES).toHaveLength(19);
    expect(records).toHaveLength(19);
  });

  for (const pin of PINS) {
    it(`${pin.id}: ${pin.verdict} — score ${pin.ten ?? '—'}/10, ${pin.viol} violation(s), stop=${pin.stop}`, () => {
      const record = byId(pin.id);
      expect(record.verdict).toBe(pin.verdict);
      expect(record.outcome).toBe(pin.outcome);
      expect(record.score.tenPoint).toBe(pin.ten);
      expect(record.score.overall0to100).toBe(pin.overall);
      expect(record.iterations).toBe(pin.iter);
      expect(record.stopReason).toBe(pin.stop);
      expect(record.metrics.npacPoints).toBe(pin.npac);
      expect(record.metrics.iceFractionPercent).toBe(pin.ice);
      expect(record.metrics.podPoints).toBe(pin.pod);
      expect(record.violations).toHaveLength(pin.viol);
      expect(record.hardSafe).toBe(pin.hardSafe);
      expect(record.batchTotalG).toBe(pin.batch);
      expect(record.engineVersion).toBe('0.4.0');
      expect(record.configVersion).toBe('0.7.0');
    });
  }
});

describe('structural invariants — locks, batch, identity (no fixture can fake these)', () => {
  it('T1–T9: the strawberry EXACT lock is byte-exact and the batch returns to 1000 g', () => {
    for (let i = 1; i <= 9; i += 1) {
      const record = byId(`T${i}`);
      const straw = record.finalLines!.find((row) => row.ingredientId === 'PI-ING-001553')!;
      expect(Object.is(straw.grams, i * 100), `T${i} strawberry ${straw.grams}`).toBe(true);
      expect(Math.abs(record.batchTotalG! - 1000)).toBeLessThanOrEqual(0.1);
      const ids = record.finalLines!.map((row) => row.ingredientId);
      expect(new Set(ids).size).toBe(ids.length); // one row per canonical identity
    }
  });

  it('T1–T9 cross-table: the composition REALLY changes as the fruit rises (anti-constant proof)', () => {
    const rows = Array.from({ length: 9 }, (_, i) => byId(`T${i + 1}`));
    const npacs = rows.map((r) => r.metrics.npacPoints);
    const ices = rows.map((r) => r.metrics.iceFractionPercent);
    const scores = rows.map((r) => r.score.overall0to100);
    expect(new Set(npacs).size).toBeGreaterThanOrEqual(8);
    expect(new Set(ices).size).toBeGreaterThanOrEqual(8);
    expect(new Set(scores).size).toBeGreaterThanOrEqual(8);
    // fat falls as fruit displaces dairy: T1 (100 g) vs T9 (900 g)
    expect(rows[0]!.metrics.fatPercent!).toBeGreaterThan(rows[8]!.metrics.fatPercent!);
    // T9 (the owner's suspected false positive) is NOT a 10/10 — it is the
    // honest capped best-achievable state with 10 residual violations.
    expect(byId('T9').score.tenPoint).toBeLessThanOrEqual(5);
    expect(byId('T9').bestAchievableProof).toContain('CAP HIT');
  });

  it('T11/T12: milk exactly 500 g; the rest is NOT proportionally scaled (dextrose factor diverges)', () => {
    for (const id of ['T11', 'T12']) {
      const record = byId(id);
      const milk = record.finalLines!.find((row) => row.ingredientId === 'milk_3_5')!;
      expect(Object.is(milk.grams, 500)).toBe(true);
      expect(record.proportionalScaling.detected).toBe(false);
      const factors = new Map(record.proportionalScaling.factors.map((f) => [f.lineId, f.factor]));
      // strawberry & co. share ~0.72 while dextrose moved by ~2.19 — a real
      // per-line decision, impossible under one shared scale factor.
      expect(Math.abs(factors.get('l-dex')! - factors.get('l-straw')!)).toBeGreaterThan(1);
    }
  });

  it('T13: the range 250–400 g is honored strictly inside the band', () => {
    const record = byId('T13');
    const straw = record.finalLines!.find((row) => row.ingredientId === 'PI-ING-001553')!;
    expect(straw.grams).toBeGreaterThanOrEqual(250);
    expect(straw.grams).toBeLessThanOrEqual(400);
  });

  it('T14: inulin stays EXACTLY 0 (never re-added); proportional projection is named AND justified', () => {
    const record = byId('T14');
    const inulin = record.finalLines!.find((row) => row.ingredientId === 'inulin')!;
    expect(Object.is(inulin.grams, 0)).toBe(true);
    expect(record.finalLines!.filter((row) => row.ingredientId === 'inulin')).toHaveLength(1);
    expect(record.proportionalScaling.detected).toBe(true);
    expect(record.verdictReason).toContain('PROPORTIONAL SCALING DETECTED');
    expect(record.verdictReason).toContain('legitimate HERE');
  });

  it('T15: SMP stays EXACTLY 0 and the milk-solids gap surfaces as protein violations, not silence', () => {
    const record = byId('T15');
    const smp = record.finalLines!.find((row) => row.ingredientId === 'smp')!;
    expect(Object.is(smp.grams, 0)).toBe(true);
    const metrics = record.violations.map((violation) => violation.metric);
    expect(metrics).toContain('protein_in_solids');
    expect(metrics).toContain('aerating_protein');
  });

  it('T16: sucrose exclusion is a refusal naming sweetener_sucrose — never a silent substitution', () => {
    const record = byId('T16');
    expect(record.outcome).toBe('missing_required_role');
    expect(record.outcomeDetail).toContain('sweetener_sucrose');
    expect(record.finalLines).toBeNull(); // nothing was fabricated
  });

  it('T17/T18 differ from −11 and from each other where physics requires (dextrose, NPAC)', () => {
    const t17 = byId('T17');
    const t18 = byId('T18');
    const dex17 = t17.finalLines!.find((row) => row.ingredientId === 'dextrose')!.grams;
    const dex18 = t18.finalLines!.find((row) => row.ingredientId === 'dextrose')!.grams;
    expect(dex18).toBeGreaterThan(dex17); // colder serving → more freezing-control sugar
    expect(t18.metrics.npacPoints!).toBeGreaterThan(t17.metrics.npacPoints!);
    // both native profiles — no category fallback
    expect(t17.targetBandSource).toContain('native');
    expect(t18.targetBandSource).toContain('native');
    expect(t17.score.provisionalBands).toBe(false);
    expect(t18.score.provisionalBands).toBe(false);
  });

  it('T19: sorbet contains NO dairy line and no dairy was invented', () => {
    const record = byId('T19');
    const dairyIds = ['milk_3_5', 'cream_30', 'smp'];
    expect(record.finalLines!.some((row) => dairyIds.includes(row.ingredientId))).toBe(false);
  });
});

describe('tara / stabilizer provenance (owner requirement c)', () => {
  it('the engine has NO stabilizer target metric — the dose can never be engine-optimized', () => {
    expect(engineHasStabilizerMetric()).toBe(false);
  });

  it('every gelato/sorbet output carries the honest template-dose note', () => {
    for (const record of records) {
      if (!record.stabilizer.present) continue;
      expect(record.stabilizer.optimizedByEngine).toBe(false);
      expect(record.stabilizer.notePl).toBe(
        'Dawka stabilizatora pochodzi z szablonu referencyjnego i nie została zoptymalizowana przez Engine.',
      );
      expect(record.stabilizer.grams).not.toBeNull();
      expect(record.stabilizer.percentOfMix).not.toBeNull();
    }
  });
});

describe('10/10 contract (owner requirement e)', () => {
  it('a provisional (fallback-band) profile is never classified as a validated native optimum', () => {
    for (const record of records) {
      if (record.score.provisionalBands) {
        expect(record.verdict).not.toBe('AUTHENTIC-OPTIMAL');
      }
    }
  });

  it('the only AUTHENTIC-OPTIMAL is a native profile with 0 violations (T17)', () => {
    const optimal = records.filter((record) => record.verdict === 'AUTHENTIC-OPTIMAL');
    expect(optimal.map((record) => record.testId)).toEqual(['T17']);
    expect(optimal[0]!.violations).toHaveLength(0);
    expect(optimal[0]!.score.provisionalBands).toBe(false);
  });
});

/* ── T20 — repeatability / anti-fixture (direct + store reload halves) ────── */

describe('T20 — repeatability / anti-fixture', () => {
  it('10 fresh direct runs (unrelated calcs interleaved) are byte-identical', () => {
    const battery = runDeterminismBattery();
    expect(battery.directSignatures).toHaveLength(10);
    expect(new Set(battery.directSignatures).size).toBe(1);
    expect(battery.allDirectIdentical).toBe(true);
    expect(battery.record.verdict).toBe('AUTHENTIC-BEST-ACHIEVABLE');
  });

  it('the live store path produces the same grams before AND after save/reload (no contamination)', () => {
    const STRAWBERRIES: EngineIngredient = {
      ...findDemoIngredient('raspberry')!,
      id: 'PI-ING-001553',
      name: 'STRAWBERRIES · Fresh Fruit',
      category: 'fruit',
    };
    const seed = () => {
      useRecipeStore.setState({
        mode: 'classic',
        category: 'fruit_gelato',
        visibleProductType: 'gelato',
        target_temperature_c: -11,
        target_batch_grams: 1000,
        machine_capacity_grams: null,
        flavor_intensity: 'balanced',
        cost_priority: 'balanced',
        items: [
          { id: 'l-milk', ingredient: findDemoIngredient('milk_3_5')!, planned_grams: 0, actual_grams: null, lock_type: 'unlocked' },
          { id: 'l-straw', ingredient: STRAWBERRIES, planned_grams: 0, actual_grams: null, lock_type: 'unlocked' },
        ],
        excludedIngredientIds: [],
      });
      useConstraintStudioStore.getState().resetForTests();
    };
    const gramsSignature = (input: RecipeInput): string =>
      JSON.stringify(input.items.map((item) => [item.id, item.ingredient.id, item.planned_grams]));

    seed();
    useConstraintStudioStore.getState().createOptimizePreview();
    const first = useConstraintStudioStore.getState().preview;
    expect(first).not.toBeNull();
    const beforeReload = gramsSignature(first!.proposedInput);

    // save the DRAFT and reload it through the real store action, then re-preview
    const savedDraft = buildRecipeInput(useRecipeStore.getState());
    useRecipeStore.getState().loadRecipeInput(savedDraft, { savedId: 'r-t20', savedName: 'T20' });
    useConstraintStudioStore.getState().resetForTests();
    useConstraintStudioStore.getState().createOptimizePreview();
    const second = useConstraintStudioStore.getState().preview;
    expect(second).not.toBeNull();
    expect(gramsSignature(second!.proposedInput)).toBe(beforeReload);

    // the store path agrees with the pure direct path line-for-line
    const direct = byId('T10');
    const directPairs = direct.finalLines!.map((row) => [row.ingredientId, row.grams]);
    const storePairs = first!.proposedInput.items.map((item) => [
      item.ingredient.id,
      Math.round(item.planned_grams * 1e4) / 1e4,
    ]);
    expect(new Map(storePairs.map(([a, b]) => [String(a), b]))).toEqual(
      new Map(directPairs.map(([a, b]) => [String(a), b])),
    );
  });
});

/* ── science freeze ────────────────────────────────────────────────────────── */

describe('science freeze', () => {
  it('ENGINE 0.4.0 + CONFIG 0.7.0 unchanged across the whole battery', () => {
    for (const record of records) {
      expect(record.engineVersion).toBe('0.4.0');
      expect(record.configVersion).toBe('0.7.0');
    }
  });
});
