/**
 * AGENT 2 — ENGINE AUTHENTICITY drift detectors (owner tests T1–T20).
 *
 * Pins what `buildOptimizePreview` + `calculateRecipe` ACTUALLY return today
 * (staging nightly/integration) for the owner's 20 offline tests — any future
 * formula/config/template change that shifts a verdict, a score, an iteration
 * count or a 4-decimal metric fails here first. These are DRIFT DETECTORS and
 * authenticity proofs, not judgments of scientific correctness; no engine
 * value is changed by this suite.
 *
 * Full structured results live in docs/engine-validation/
 * ENGINE_AUTHENTICITY_TESTS.{json,csv} (regenerated by the artifacts test) and
 * docs/engine-validation/AGENT2_ENGINE_AUTHENTICITY_LEDGER.md.
 */
import { beforeAll, describe, expect, it } from 'vitest';
import type { EngineIngredient, RecipeInput } from '@/engine';
import { findDemoIngredient } from '@/data/demoIngredients';
import { useRecipeStore } from '@/stores/recipeStore';
import { buildRecipeInput } from '@/features/studio/buildRecipeInput';
import { useConstraintStudioStore } from '@/features/constraint-studio/constraintStudioStore';
import { buildOptimizePreview } from '@/features/constraint-studio/applyPipeline';
import {
  AUTHENTICITY_CASES,
  engineHasStabilizerMetric,
  runAllAuthenticityCases,
  runDeterminismBattery,
  type AuthenticityRecord,
} from './authenticityCases';

/* ── one shared battery run (the runner is pure and deterministic) ─────────── */

let records: AuthenticityRecord[] = [];
const byId = (id: string): AuthenticityRecord => {
  const found = records.find((record) => record.testId === id);
  if (!found) throw new Error(`missing record ${id}`);
  return found;
};

beforeAll(() => {
  records = runAllAuthenticityCases();
});

/* ── the pinned outcome table (observed 2026-08-20, ENGINE 0.4.0 / CONFIG 0.7.0) ── */

interface Pin {
  id: string;
  verdict: AuthenticityRecord['verdict'];
  outcome: string;
  ten: number | null;
  overall: number | null;
  iter: number | null;
  stop: string;
  npac: number | null;
  ice: number | null;
  pod: number | null;
  viol: number;
  hardSafe: boolean;
  batch: number;
}

const PINS: Pin[] = [
  // OWNER FORMULATION POLICY RE-PIN (2026-08-20): exact PI-ING-000456 is
  // optional and is never inserted silently; the Gelato stabilizer system is
  // now generated at the owner-preferred whole-gram target (3 g / 1000 g).
  // T11 therefore honestly remains BEST-FOUND with one hard residual instead
  // of regaining feasibility through an unrequested Inulin insertion.
  // ─────────────────────────────────────────────────────────────────────────
  // OWNER FINAL INTEGRATION ADDENDUM items 1+2+3 (2026-07-25) — DELIBERATE
  // full re-pin. The previous table (CURRENT-DRAFT OPTIMIZATION P0, quoted in
  // docs/product-completion/CURRENT_DRAFT_OPTIMIZATION_LEDGER.md) measured the
  // T1–T13/T15/T16 cases on SUBSTITUTED bands: they declared `fruit_gelato`,
  // an UNSEEDED cell, so `selectTargetBand` silently handed them the
  // milk_gelato bands with `category_fallback: true` and the 10/10 contract
  // barred them from AUTHENTIC-OPTIMAL forever.
  //
  // Item 1 makes the harness build only states runtime can produce (the
  // declared category goes through the same canonicalization as the engine
  // seam), so these dairy fruit cases are now `milk_gelato` — the SAME band
  // VALUES, now NATIVE — seeded from the APPROVED `milk_base_v1` instead of
  // the quarantined `fruit_gelato_ref_v1` (item 2). Consequences, all visible
  // in this table:
  //   · 15 cases stop being provisional (T1–T13, T15, T16);
  //   · 10 of them newly reach AUTHENTIC-OPTIMAL (0 violations on NATIVE
  //     approved bands) — the verdict provisional bands made unreachable —
  //     taking the total from 4 to 14;
  //   · T7/T8/T15/T9/T16 turn `hardSafe: false`: their residual violations are
  //     the SAME numbers, now classified HARD (native) instead of SOFT
  //     (provisional), so the addendum-3 door makes those previews
  //     DIAGNOSTIC-ONLY. Nothing got worse — the honesty got stricter.
  // Item 3 renames the verdict AUTHENTIC-BEST-ACHIEVABLE → AUTHENTIC-BEST-FOUND
  // (coordinate descent proves a local fixed point, never a global optimum).
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'T1',
    verdict: 'AUTHENTIC-OPTIMAL',
    outcome: 'preview',
    ten: 9,
    overall: 87,
    iter: 1,
    stop: 'all_bands_in_range',
    npac: 38.1861,
    ice: 49.0258,
    pod: 16.6263,
    viol: 0,
    hardSafe: true,
    batch: 1000,
  },
  {
    id: 'T2',
    verdict: 'AUTHENTIC-OPTIMAL',
    outcome: 'preview',
    ten: 9,
    overall: 86.9479,
    iter: 3,
    stop: 'all_bands_in_range',
    npac: 38.9457,
    ice: 48.224,
    pod: 13.9068,
    viol: 0,
    hardSafe: true,
    batch: 1000,
  },
  {
    id: 'T3',
    verdict: 'AUTHENTIC-OPTIMAL',
    outcome: 'preview',
    ten: 8,
    overall: 84.8362,
    iter: 3,
    stop: 'all_bands_in_range',
    npac: 38.5955,
    ice: 48.5936,
    pod: 13.1183,
    viol: 0,
    hardSafe: true,
    batch: 1000,
  },
  {
    id: 'T4',
    verdict: 'AUTHENTIC-OPTIMAL',
    outcome: 'preview',
    ten: 8,
    overall: 81.3516,
    iter: 3,
    stop: 'all_bands_in_range',
    npac: 41.962,
    ice: 45.0401,
    pod: 13.6106,
    viol: 0,
    hardSafe: true,
    batch: 1000,
  },
  {
    id: 'T5',
    verdict: 'AUTHENTIC-OPTIMAL',
    outcome: 'preview',
    ten: 8,
    overall: 78.6718,
    iter: 3,
    stop: 'all_bands_in_range',
    npac: 41.2366,
    ice: 45.8058,
    pod: 12.3127,
    viol: 0,
    hardSafe: true,
    batch: 1000,
  },
  {
    id: 'T6',
    verdict: 'AUTHENTIC-OPTIMAL',
    outcome: 'preview',
    ten: 8,
    overall: 78.2807,
    iter: 6,
    stop: 'all_bands_in_range',
    npac: 39.3964,
    ice: 47.7482,
    pod: 12.6154,
    viol: 0,
    hardSafe: true,
    batch: 1000,
  },
  {
    id: 'T7',
    verdict: 'AUTHENTIC-BEST-FOUND',
    outcome: 'preview',
    ten: 8,
    overall: 75.7592,
    iter: 12,
    stop: 'fixed_point_no_proposal',
    npac: 37.2247,
    ice: 50.0406,
    pod: 12.2488,
    viol: 1,
    hardSafe: false,
    batch: 1000,
  },
  {
    id: 'T8',
    verdict: 'AUTHENTIC-BEST-FOUND',
    outcome: 'preview',
    ten: 7,
    overall: 72.958,
    iter: 8,
    stop: 'fixed_point_no_proposal',
    npac: 37.6463,
    ice: 49.5955,
    pod: 13.0902,
    viol: 3,
    hardSafe: false,
    batch: 1000,
  },
  {
    id: 'T9',
    verdict: 'HONEST-IMPOSSIBLE',
    outcome: 'impossible_under_constraints',
    ten: 5,
    overall: 45.4655,
    iter: 12,
    stop: 'iteration_cap',
    npac: 9.7209,
    ice: 79.0724,
    pod: 5.632,
    viol: 10,
    hardSafe: false,
    batch: 900,
  },
  {
    id: 'T10',
    verdict: 'AUTHENTIC-OPTIMAL',
    outcome: 'preview',
    ten: 8,
    overall: 84.959,
    iter: 3,
    stop: 'all_bands_in_range',
    npac: 39.7817,
    ice: 47.3415,
    pod: 13.4481,
    viol: 0,
    hardSafe: true,
    batch: 1000,
  },
  {
    id: 'T11',
    verdict: 'AUTHENTIC-BEST-FOUND',
    outcome: 'preview',
    ten: 8,
    overall: 83.2408,
    iter: 6,
    stop: 'no_improving_move',
    npac: 41.8855,
    ice: 45.1209,
    pod: 14.674,
    viol: 1,
    hardSafe: false,
    batch: 1000,
  },
  {
    id: 'T12',
    verdict: 'AUTHENTIC-OPTIMAL',
    outcome: 'preview',
    ten: 9,
    overall: 86.2123,
    iter: 3,
    stop: 'all_bands_in_range',
    npac: 39.3714,
    ice: 47.7747,
    pod: 14.2128,
    viol: 0,
    hardSafe: true,
    batch: 1000,
  },
  {
    id: 'T13',
    verdict: 'AUTHENTIC-OPTIMAL',
    outcome: 'preview',
    ten: 9,
    overall: 86.0242,
    iter: 3,
    stop: 'all_bands_in_range',
    npac: 38.8891,
    ice: 48.2837,
    pod: 13.4914,
    viol: 0,
    hardSafe: true,
    batch: 1000,
  },
  {
    id: 'T14',
    verdict: 'AUTHENTIC-OPTIMAL',
    outcome: 'preview',
    ten: 7,
    overall: 73.7897,
    iter: 1,
    stop: 'all_bands_in_range',
    npac: 36.0237,
    ice: 51.3083,
    pod: 18.5605,
    viol: 0,
    hardSafe: true,
    batch: 1000,
  },
  {
    id: 'T15',
    verdict: 'AUTHENTIC-BEST-FOUND',
    outcome: 'preview',
    ten: 8,
    overall: 81.837,
    iter: 7,
    stop: 'fixed_point_no_proposal',
    npac: 38.4715,
    ice: 48.7246,
    pod: 12.7985,
    viol: 3,
    hardSafe: false,
    batch: 1000,
  },
  {
    id: 'T16',
    verdict: 'HONEST-IMPOSSIBLE',
    outcome: 'missing_required_role',
    ten: 5,
    overall: 45.4655,
    iter: null,
    stop: 'missing_required_role',
    npac: 9.7209,
    ice: 79.0724,
    pod: 5.632,
    viol: 10,
    hardSafe: false,
    batch: 350,
  },
  {
    id: 'T17',
    verdict: 'AUTHENTIC-OPTIMAL',
    outcome: 'preview',
    ten: 9,
    overall: 88.1667,
    iter: 0,
    stop: 'all_bands_in_range',
    npac: 47.684,
    ice: 50.3275,
    pod: 15.7748,
    viol: 0,
    hardSafe: true,
    batch: 1000,
  },
  {
    id: 'T18',
    verdict: 'AUTHENTIC-OPTIMAL',
    outcome: 'preview',
    ten: 9,
    overall: 87.1667,
    iter: 1,
    stop: 'all_bands_in_range',
    npac: 52.7521,
    ice: 49.7015,
    pod: 15.8201,
    viol: 0,
    hardSafe: true,
    batch: 1000,
  },
  {
    id: 'T19',
    verdict: 'AUTHENTIC-OPTIMAL',
    outcome: 'preview',
    ten: 7,
    overall: 73.7897,
    iter: 1,
    stop: 'all_bands_in_range',
    npac: 36.0237,
    ice: 51.3083,
    pod: 18.5605,
    viol: 0,
    hardSafe: true,
    batch: 1000,
  },
];

describe('T1–T19 — pinned engine outcomes (drift detectors)', () => {
  it('runs exactly the 19 direct cases (+ T20 battery separately)', () => {
    expect(AUTHENTICITY_CASES).toHaveLength(19);
    expect(records).toHaveLength(19);
  });

  for (const pin of PINS) {
    it(`${pin.id}: ${pin.verdict} — score ${pin.ten ?? '—'}/10, ${pin.viol} violation(s), stop=${pin.stop}`, () => {
      const record = byId(pin.id);
      expect(record.verdict).toBe(pin.verdict);
      expect(record.outcome).toBe(pin.outcome);
      expect(record.score.tenPoint).toBe(pin.ten);
      expect(record.score.overall0to100).toBe(pin.overall);
      expect(record.iterations).toBe(pin.iter);
      expect(record.stopReason).toBe(pin.stop);
      expect(record.metrics.npacPoints).toBe(pin.npac);
      expect(record.metrics.iceFractionPercent).toBe(pin.ice);
      expect(record.metrics.podPoints).toBe(pin.pod);
      expect(record.violations).toHaveLength(pin.viol);
      expect(record.hardSafe).toBe(pin.hardSafe);
      expect(record.batchTotalG).toBe(pin.batch);
      expect(record.engineVersion).toBe('0.4.0');
      expect(record.configVersion).toBe('0.7.0');
    });
  }
});

describe('structural invariants — locks, batch, identity (no fixture can fake these)', () => {
  it('T1–T8: the strawberry EXACT lock is byte-exact and the batch returns to 1000 g', () => {
    // ADDENDUM (1): T9 no longer yields a proposed state (honest impossible) —
    // the byte-exact-lock invariant is pinned on the eight feasible locks.
    for (let i = 1; i <= 8; i += 1) {
      const record = byId(`T${i}`);
      const straw = record.finalLines!.find((row) => row.ingredientId === 'PI-ING-001553')!;
      expect(Object.is(straw.grams, i * 100), `T${i} strawberry ${straw.grams}`).toBe(true);
      expect(Math.abs(record.batchTotalG! - 1000)).toBeLessThanOrEqual(0.1);
      const ids = record.finalLines!.map((row) => row.ingredientId);
      expect(new Set(ids).size).toBe(ids.length); // one row per canonical identity
    }
  });

  it('T9 (ADDENDUM 1): the capped 900 g lock is the honest impossible — nothing fabricated', () => {
    const record = byId('T9');
    expect(record.outcome).toBe('impossible_under_constraints');
    expect(record.finalLines).toBeNull(); // no proposed state exists
    expect(record.stopReason).toBe('iteration_cap');
    expect(record.verdict).toBe('HONEST-IMPOSSIBLE');
  });

  it('T1–T9 cross-table: the composition REALLY changes as the fruit rises (anti-constant proof)', () => {
    const rows = Array.from({ length: 9 }, (_, i) => byId(`T${i + 1}`));
    const npacs = rows.map((r) => r.metrics.npacPoints);
    const ices = rows.map((r) => r.metrics.iceFractionPercent);
    const scores = rows.map((r) => r.score.overall0to100);
    expect(new Set(npacs).size).toBeGreaterThanOrEqual(8);
    expect(new Set(ices).size).toBeGreaterThanOrEqual(8);
    expect(new Set(scores).size).toBeGreaterThanOrEqual(8);
    // fat falls as fruit displaces dairy: T1 (100 g) vs T9 (900 g)
    expect(rows[0]!.metrics.fatPercent!).toBeGreaterThan(rows[8]!.metrics.fatPercent!);
    // T9 (the owner's suspected false positive) is NOT a 10/10 — it is the
    // honest capped best-found state with 10 residual violations.
    expect(byId('T9').score.tenPoint).toBeLessThanOrEqual(5);
    expect(byId('T9').bestFoundProof).toContain('CAP HIT');
  });

  it('T11 (EXACT 500): milk byte-held; the rest is NOT proportionally scaled (dextrose factor diverges)', () => {
    const record = byId('T11');
    const milk = record.finalLines!.find((row) => row.ingredientId === 'milk_3_5')!;
    expect(Object.is(milk.grams, 500)).toBe(true);
    expect(record.proportionalScaling.detected).toBe(false);
    const factors = new Map(record.proportionalScaling.factors.map((f) => [f.lineId, f.factor]));
    // strawberry & co. share ~0.72 while dextrose moved by ~2.19 — a real
    // per-line decision, impossible under one shared scale factor.
    expect(Math.abs(factors.get('l-dex')! - factors.get('l-straw')!)).toBeGreaterThan(1);
  });

  it('T12 (MAX 500 — ADDENDUM 4): milk lands STRICTLY BELOW the max at the template proportion', () => {
    // The max bound is a RANGE, never an exact hold: the solver chose 380 g
    // (< 500) — different solver freedom than T11's byte-held exact lock.
    const record = byId('T12');
    const milk = record.finalLines!.find((row) => row.ingredientId === 'milk_3_5')!;
    expect(milk.grams).toBeLessThan(500);
    expect(milk.grams).toBeGreaterThan(0);
    expect(
      Object.is(
        milk.grams,
        byId('T11').finalLines!.find((r) => r.ingredientId === 'milk_3_5')!.grams,
      ),
    ).toBe(false);
    expect(record.proportionalScaling.detected).toBe(false);
  });

  it('T13: the range 250–400 g is honored strictly inside the band', () => {
    const record = byId('T13');
    const straw = record.finalLines!.find((row) => row.ingredientId === 'PI-ING-001553')!;
    expect(straw.grams).toBeGreaterThanOrEqual(250);
    expect(straw.grams).toBeLessThanOrEqual(400);
  });

  it('T14: inulin stays EXACTLY 0 (never re-added) and the result is NOT a projection', () => {
    const record = byId('T14');
    const inulin = record.finalLines!.find((row) => row.ingredientId === 'inulin')!;
    expect(Object.is(inulin.grams, 0)).toBe(true);
    expect(record.finalLines!.filter((row) => row.ingredientId === 'inulin')).toHaveLength(1);
    // CURRENT-DRAFT OPTIMIZATION P0 (owner, 2026-07-25) — DELIBERATE update:
    // T14 used to END on the proportional projection of the template seed
    // (nothing the engine could move). With the current-draft candidate vector
    // the draft's own unlocked lines really move, so the presented state is a
    // worked engine result — the projection detector must now read FALSE.
    expect(record.proportionalScaling.detected).toBe(false);
    expect(record.violations).toHaveLength(0);
  });

  it('T15: SMP stays EXACTLY 0 and the milk-solids gap surfaces as protein violations, not silence', () => {
    const record = byId('T15');
    const smp = record.finalLines!.find((row) => row.ingredientId === 'smp')!;
    expect(Object.is(smp.grams, 0)).toBe(true);
    const metrics = record.violations.map((violation) => violation.metric);
    expect(metrics).toContain('protein_in_solids');
    expect(metrics).toContain('aerating_protein');
  });

  it('T16: sucrose exclusion is a refusal naming sweetener_sucrose — never a silent substitution', () => {
    const record = byId('T16');
    expect(record.outcome).toBe('missing_required_role');
    expect(record.outcomeDetail).toContain('sweetener_sucrose');
    expect(record.finalLines).toBeNull(); // nothing was fabricated
  });

  it('T17/T18 differ from −11 and from each other where physics requires (dextrose, NPAC)', () => {
    const t17 = byId('T17');
    const t18 = byId('T18');
    const dex17 = t17.finalLines!.find((row) => row.ingredientId === 'dextrose')!.grams;
    const dex18 = t18.finalLines!.find((row) => row.ingredientId === 'dextrose')!.grams;
    expect(dex18).toBeGreaterThan(dex17); // colder serving → more freezing-control sugar
    expect(t18.metrics.npacPoints!).toBeGreaterThan(t17.metrics.npacPoints!);
    // both native profiles — no category fallback
    expect(t17.targetBandSource).toContain('native');
    expect(t18.targetBandSource).toContain('native');
    expect(t17.score.provisionalBands).toBe(false);
    expect(t18.score.provisionalBands).toBe(false);
  });

  it('T19: sorbet contains NO dairy line and no dairy was invented', () => {
    const record = byId('T19');
    const dairyIds = ['milk_3_5', 'cream_30', 'smp'];
    expect(record.finalLines!.some((row) => dairyIds.includes(row.ingredientId))).toBe(false);
  });
});

describe('tara / stabilizer provenance (owner requirement c)', () => {
  it('the engine has NO stabilizer target metric — the dose can never be engine-optimized', () => {
    expect(engineHasStabilizerMetric()).toBe(false);
  });

  it('every gelato/sorbet output carries the honest template-dose note', () => {
    for (const record of records) {
      if (!record.stabilizer.present) continue;
      expect(record.stabilizer.optimizedByEngine).toBe(false);
      expect(record.stabilizer.notePl).toBe(
        'Dawka stabilizatora pochodzi z szablonu referencyjnego i nie została zoptymalizowana przez Engine.',
      );
      expect(record.stabilizer.grams).not.toBeNull();
      expect(record.stabilizer.percentOfMix).not.toBeNull();
    }
  });
});

describe('10/10 contract (owner requirement e)', () => {
  it('a provisional (fallback-band) profile is never classified as a validated native optimum', () => {
    for (const record of records) {
      if (record.score.provisionalBands) {
        expect(record.verdict).not.toBe('AUTHENTIC-OPTIMAL');
      }
    }
  });

  it('AUTHENTIC-OPTIMAL is EXACTLY the native profiles with 0 violations', () => {
    // OWNER FINAL INTEGRATION ADDENDUM item 1 (2026-07-25) — DELIBERATE update:
    // the set grew from {T14, T17, T18, T19} to also include every dairy fruit
    // case, because those cases are no longer scored on SUBSTITUTED bands. They
    // were barred from this verdict by the provisional-band rule alone, never
    // by their numbers. The CONTRACT is unchanged (native bands + zero
    // violations). T11 is deliberately absent after the 2026-08-20 optional
    // Inulin rule: it now reports one hard residual instead of silently adding
    // the missing ingredient.
    const optimal = records.filter((record) => record.verdict === 'AUTHENTIC-OPTIMAL');
    expect(optimal.map((record) => record.testId)).toEqual([
      'T1',
      'T2',
      'T3',
      'T4',
      'T5',
      'T6',
      'T10',
      'T12',
      'T13',
      'T14',
      'T17',
      'T18',
      'T19',
    ]);
    for (const record of optimal) {
      expect(record.violations, record.testId).toHaveLength(0);
      expect(record.score.provisionalBands, record.testId).toBe(false);
    }
    // …and nothing outside that set may claim it.
    for (const record of records) {
      if (record.verdict === 'AUTHENTIC-OPTIMAL') continue;
      expect(
        record.violations.length > 0 ||
          record.score.provisionalBands ||
          record.outcome !== 'preview',
        record.testId,
      ).toBe(true);
    }
  });
});

/* ── T20 — repeatability / anti-fixture (direct + store reload halves) ────── */

describe('T20 — repeatability / anti-fixture', () => {
  it('10 fresh direct runs (unrelated calcs interleaved) are byte-identical', () => {
    const battery = runDeterminismBattery();
    expect(battery.directSignatures).toHaveLength(10);
    expect(new Set(battery.directSignatures).size).toBe(1);
    expect(battery.allDirectIdentical).toBe(true);
    // Addendum item 1: the battery case is now scored on NATIVE bands and
    // reaches every one of them — the verdict it was BARRED from before.
    expect(battery.record.verdict).toBe('AUTHENTIC-OPTIMAL');
  });

  it('the live store path produces the same grams before AND after save/reload (no contamination)', () => {
    const STRAWBERRIES: EngineIngredient = {
      ...findDemoIngredient('raspberry')!,
      id: 'PI-ING-001553',
      name: 'STRAWBERRIES · Fresh Fruit',
      category: 'fruit',
    };
    const seed = () => {
      useRecipeStore.setState({
        mode: 'classic',
        category: 'milk_gelato', // canonical family (addendum item 1)
        visibleProductType: 'gelato',
        target_temperature_c: -11,
        target_batch_grams: 1000,
        machine_capacity_grams: null,
        flavor_intensity: 'balanced',
        cost_priority: 'balanced',
        items: [
          {
            id: 'l-milk',
            ingredient: findDemoIngredient('milk_3_5')!,
            planned_grams: 0,
            actual_grams: null,
            lock_type: 'unlocked',
          },
          // Addendum items 1+2: the fruit carries an amount — no APPROVED
          // template has a fruit role for a dairy gelato, so a 0 g fruit is the
          // honest stop (pinned in the formulation suites), not a preview.
          {
            id: 'l-straw',
            ingredient: STRAWBERRIES,
            planned_grams: 350,
            actual_grams: null,
            lock_type: 'unlocked',
          },
        ],
        excludedIngredientIds: [],
      });
      useConstraintStudioStore.getState().resetForTests();
    };
    const gramsSignature = (input: RecipeInput): string =>
      JSON.stringify(input.items.map((item) => [item.id, item.ingredient.id, item.planned_grams]));

    seed();
    useConstraintStudioStore.getState().createOptimizePreview();
    const first = useConstraintStudioStore.getState().preview;
    expect(first).not.toBeNull();
    const beforeReload = gramsSignature(first!.proposedInput);

    // save the DRAFT and reload it through the real store action, then re-preview
    const savedDraft = buildRecipeInput(useRecipeStore.getState());
    useRecipeStore.getState().loadRecipeInput(savedDraft, { savedId: 'r-t20', savedName: 'T20' });
    useConstraintStudioStore.getState().resetForTests();
    useConstraintStudioStore.getState().createOptimizePreview();
    const second = useConstraintStudioStore.getState().preview;
    expect(second).not.toBeNull();
    expect(gramsSignature(second!.proposedInput)).toBe(beforeReload);

    // The store path agrees with the pure direct executable Preview
    // line-for-line. Authenticity pins intentionally retain the exact Engine
    // candidate; operator paths consume the separately audited whole-gram
    // vector.
    const pure = buildOptimizePreview(savedDraft, { byLineId: {} }, 'T20-DIRECT');
    expect(pure.ok).toBe(true);
    if (!pure.ok) return;
    const directPairs = pure.preview.proposedInput.items.map((item) => [
      item.ingredient.id,
      item.planned_grams,
    ]);
    const storePairs = first!.proposedInput.items.map((item) => [
      item.ingredient.id,
      Math.round(item.planned_grams * 1e4) / 1e4,
    ]);
    expect(new Map(storePairs.map(([a, b]) => [String(a), b]))).toEqual(
      new Map(directPairs.map(([a, b]) => [String(a), b])),
    );
  });
});

/* ── science freeze ────────────────────────────────────────────────────────── */

describe('science freeze', () => {
  it('ENGINE 0.4.0 + CONFIG 0.7.0 unchanged across the whole battery', () => {
    for (const record of records) {
      expect(record.engineVersion).toBe('0.4.0');
      expect(record.configVersion).toBe('0.7.0');
    }
  });
});
